bcgov/alcs

- alcs-api/package.json
- alcs-api/src/app.service.spec.ts
exclude migrations and app root files from code coverage
> exclude migrations from code cov

- alcs-api/.gitignore
- alcs-api/config/default.json
- alcs-api/docker-compose.yml
- alcs-api/package-lock.json
- alcs-api/package.json
- alcs-api/src/app.controller.spec.ts
- alcs-api/src/app.controller.ts
- alcs-api/src/app.module.ts
- alcs-api/src/common/authorization/authorization.module.ts
- alcs-api/src/common/authorization/role.guard.spec.ts
- alcs-api/src/common/authorization/role.guard.ts
- alcs-api/src/common/authorization/roles.decorator.ts
- alcs-api/src/common/base.entity.ts
- alcs-api/src/common/config/config.module.ts
- alcs-api/src/providers/keycloak/keycloak-config.service.spec.ts
- alcs-api/src/providers/keycloak/keycloak-config.service.ts
- alcs-api/src/providers/typeorm/orm.config.ts
- alcs-api/src/providers/typeorm/typeorm.service.spec.ts
- alcs-api/src/providers/typeorm/typeorm.service.ts
- alcs-api/src/user/user.entity.ts
- alcs-api/src/user/user.module.ts
- alcs-api/src/user/user.service.spec.ts
- alcs-api/src/user/user.service.ts
- alcs-api/tsconfig.json
* Add user entity to back it
* Add tests and config
> Add Keycloak AuthGuard

- alcs-frontend/src/app/services/authentication/authentication.service.ts
* If user has no token also force them to login
> Always try to authenticate even when token is not present

- alcs-api/src/common/authorization/authorization.controller.spec.ts
- alcs-api/src/common/authorization/authorization.controller.ts
- alcs-frontend/package-lock.json
- alcs-frontend/package.json
- alcs-frontend/src/app/features/authorization/authorization.component.ts
- alcs-frontend/src/app/services/authentication/auth-interceptor.service.ts
- alcs-frontend/src/app/services/authentication/auth.guard.spec.ts
- alcs-frontend/src/app/services/authentication/auth.guard.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
* Send refresh token to front end
* Store expiry and when expired use refresh token to refresh
> Add token refresh flow

- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/admin/admin.component.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.spec.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-item.interface.ts
- alcs-frontend/src/app/shared/drag-drop-board/status-filter.pipe.ts
* Add component for card
* Refactor board to use new component
* Basic styling
> First pass of Card Component

- alcs-api/package-lock.json
- alcs-api/package.json
- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.module.ts
- alcs-api/src/providers/business-days/business-day.module.ts
- alcs-api/src/providers/business-days/business-day.service.spec.ts
- alcs-api/src/providers/business-days/business-day.service.ts
- alcs-api/src/providers/business-days/holiday.entity.ts
- alcs-api/src/providers/typeorm/migrations/1658946848971-seed_holidays.ts
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/admin/admin.component.ts
- alcs-frontend/src/app/features/application/application.dto.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.spec.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
- alcs-frontend/src/styles.scss
* First pass of active days, only considers days from creation and no pauses
> Add active business days based on creation time

- alcs-api/src/application/application-history.entity.ts
- alcs-api/src/application/application-paused.entity.ts
- alcs-api/src/application/application-paused.service.spec.ts
- alcs-api/src/application/application-time-tracking.service.spec.ts
- alcs-api/src/application/application-time-tracking.service.ts
- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/application/application.module.ts
- alcs-api/src/application/application.service.ts
- alcs-api/src/application/application.subscriber.spec.ts
- alcs-api/src/application/application.subscriber.ts
- alcs-api/src/common/entities/audit.subscriber.ts
- alcs-api/src/common/entities/base.entity.ts
- alcs-api/src/common/utils/test-helpers/mockEntities.ts
- alcs-api/src/providers/typeorm/migrations/1658946848971-seed_holidays.ts
- alcs-api/src/providers/typeorm/migrations/1659032043316-paused_calculation_function.ts
- alcs-frontend/src/app/features/admin/admin.component.ts
- alcs-frontend/src/app/features/application/application.dto.ts
- alcs-frontend/src/app/features/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/card-detail-dialog/card-detail-dialog.component.ts
- alcs-frontend/src/app/services/authentication/auth.guard.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.spec.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
* Add new ApplicationTimeTrackingService to track active and paused days
* Add to controller and enrich returned Applications with paused and active day counts
> Add Paused Feature

- alcs-api/src/application/application.service.ts
- alcs-api/src/application/application.subscriber.ts
- alcs-api/src/common/entities/base.entity.ts
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/admin/admin.component.spec.ts
- alcs-frontend/src/app/features/admin/admin.component.ts
- alcs-frontend/src/app/features/application/application.service.spec.ts
- alcs-frontend/src/app/features/application/application.service.ts
- alcs-frontend/src/app/features/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/card-detail-dialog/card-detail-dialog.component.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- alcs-frontend/src/app/services/toast/toast.service.spec.ts
- alcs-frontend/src/app/services/toast/toast.service.ts
- alcs-frontend/src/styles.scss
- alcs-frontend/src/styles/colors.scss
- alcs-frontend/src/styles/toast.scss
* Set refresh token into refresh token instead of access token
* Remove update false flag from auditUpdatedAt so we can update the value
* Set AuditUpdateAt manually for Update query
> Add Toast Service + Bug Fixes

- alcs-api/src/providers/typeorm/migrations/1659047420726-seed_application_types.ts
* Update App Type Short codes to match provided requirements
> Update App Type Short Codes

- alcs-api/README.md
- alcs-api/docker-compose.yml
- alcs-api/test/pgtap/test_calculate_paused_time.sql
- alcs-api/test/pgtap/test_schema.sql
- pgtap docker-compose
- db schema tests
- tests for calculate_paused_time
> introduce pgtap tests

- alcs-api/config/default.json
- alcs-api/config/test.json
- alcs-api/src/providers/email/email.module.ts
- alcs-api/src/providers/email/email.service.spec.ts
- alcs-api/src/providers/email/email.service.ts
* Add email service using CHES
> Add CHES Email Service

- alcs-api/src/app.module.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/comment/comment.controller.spec.ts
- alcs-api/src/comment/comment.controller.ts
- alcs-api/src/comment/comment.dto.ts
- alcs-api/src/comment/comment.entity.ts
- alcs-api/src/comment/comment.module.ts
- alcs-api/src/comment/comment.service.spec.ts
- alcs-api/src/comment/comment.service.ts
- alcs-api/src/common/automapper/comment.automapper.profile.ts
- alcs-api/src/common/entities/audit.subscriber.ts
- alcs-frontend/package-lock.json
- alcs-frontend/package.json
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/services/comment/comment.dto.ts
- alcs-frontend/src/app/services/comment/comment.service.spec.ts
- alcs-frontend/src/app/services/comment/comment.service.ts
- alcs-frontend/src/app/shared/commenting/comment.component.html
- alcs-frontend/src/app/shared/commenting/comment.component.scss
- alcs-frontend/src/app/shared/commenting/comment.component.spec.ts
- alcs-frontend/src/app/shared/commenting/comment.component.ts
- alcs-frontend/src/app/shared/commenting/comments.component.html
- alcs-frontend/src/app/shared/commenting/comments.component.scss
- alcs-frontend/src/app/shared/commenting/comments.component.spec.ts
- alcs-frontend/src/app/shared/commenting/comments.component.ts
* Add commenting system for applications
* Add dayjs to frontend for formatting
* Create comment and comments component to load and display comments
* Add backend entity, controller, service with unit tests
> Add Commenting

- alcs-api/src/comment/comment.controller.spec.ts
- alcs-api/src/comment/comment.controller.ts
- alcs-api/src/comment/comment.service.spec.ts
- alcs-api/src/comment/comment.service.ts
- alcs-api/src/common/authorization/role.guard.spec.ts
- alcs-api/src/common/authorization/role.guard.ts
- alcs-frontend/src/app/features/board/board.component.ts
* Clean up comment controller
* Resize card detail and create dialogs
> Add user entity to request object

- alcs-api/src/app.module.ts
- alcs-api/src/application/application-code/application-code.controller.spec.ts
- alcs-api/src/application/application-code/application-code.controller.ts
- alcs-api/src/logout/logout.controller.spec.ts
- alcs-api/src/logout/logout.controller.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- alcs-frontend/src/app/shared/header/header.component.html
- alcs-frontend/src/app/shared/header/header.component.scss
- alcs-frontend/src/app/shared/header/header.component.spec.ts
- alcs-frontend/src/app/shared/header/header.component.ts
* Add logout button and endpoint to load it
> Add logout button

- alcs-frontend/src/app/services/toast/toast.service.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.ts
- alcs-frontend/src/styles/toast.scss
* Simple front end rule for now until we get more rule requirements
* Fix error toast to have dismiss button by default, change button font color to grey
> Prevent card from going to decision release when its paused

- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/application/application.service.ts
- alcs-api/src/common/utils/test-helpers/mockEntities.ts
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.scss
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.spec.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.scss
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.spec.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.service.spec.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.service.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
- alcs-frontend/src/styles/toast.scss
* Add toggleable priority to cards
* Add confirmation dialog service for easily producing confirmation dialogs
* Fix toast error styling for smaller messages
*
> Add High Priority Feature

- alcs-api/src/providers/typeorm/datasource.cli.orm.config.ts
- alcs-api/src/providers/typeorm/migrations/1658160165558-migrations.ts
- alcs-api/src/providers/typeorm/orm.config.ts
* Set synhronize false
* Generate initial migration
* Update CLI config to use snake case
> Move off synchronize

- .github/workflows/schemaspy.yml
* Run on all master merges
* Setup DB and publish schemaspy results
> Add SchemaSpy job that publishes to Github Pages

- alcs-api/src/app.module.ts
- alcs-api/src/application/application-status/application-status.service.spec.ts
- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.service.spec.ts
- alcs-api/src/application/application.service.ts
- alcs-api/src/home/home.controller.spec.ts
- alcs-api/src/home/home.controller.ts
- alcs-api/src/home/home.module.ts
- alcs-frontend/src/app/app-routing.module.ts
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.html
- alcs-frontend/src/app/features/home/assigned/assigned.component.scss
- alcs-frontend/src/app/features/home/assigned/assigned.component.spec.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/features/home/home.component.html
- alcs-frontend/src/app/features/home/home.component.scss
- alcs-frontend/src/app/features/home/home.module.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/home/home.service.ts
- alcs-frontend/src/app/shared/header/header.component.ts
- alcs-frontend/src/styles/colors.scss
* Refactor Home to its own lazy loaded module
* Change board from /admin to /board
* Update colors to match new spec from UX
* Remove decisionMaker being optional on application for now
> Add Assigned to Me on Home Page

- .github/workflows/schemaspy.yml
> Fix Schemaspy 2

- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/board/board.service.spec.ts
- alcs-api/src/board/board.service.ts
- alcs-api/src/common/entities/base.code.entity.ts
- alcs-api/src/providers/typeorm/migrations/1661535512988-add_received_date.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.html
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.ts
- alcs-frontend/src/app/services/application/application.dto.ts
* Add Received date to apps and add date picker in create dialog
* Improve logging on board controller
> Add Received Date to Apps

- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.service.ts
- alcs-api/src/common/automapper/application.automapper.profile.ts
- alcs-api/src/providers/typeorm/migrations/1658160165559-seed_application_status.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.spec.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.ts
- alcs-frontend/src/styles/typography.scss
* adjust board styles according to design
* added decision meeting date on card
> ALCS-75 display decision meeting date on board

- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/providers/typeorm/migrations/1661538726897-add_intake_dates.ts
- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.spec.ts
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/intake/intake.component.scss
- alcs-frontend/src/app/features/application/intake/intake.component.spec.ts
- alcs-frontend/src/app/features/application/intake/intake.component.ts
- alcs-frontend/src/app/features/application/nav/nav.component.html
- alcs-frontend/src/app/features/application/overview/overview.component.spec.ts
- alcs-frontend/src/app/features/application/review/review.component.ts
- alcs-frontend/src/app/services/application/application-detail.service.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/application/application.service.ts
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.html
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.scss
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.spec.ts
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.ts
* Create inline edit for date picker
* Add new ApplicationDetailService to share Application across all pages
> Add Intake Page

- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/services/user/user.dto.ts
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.html
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.scss
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.spec.ts
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/header/header.component.html
- alcs-frontend/src/app/shared/header/header.component.scss
- alcs-frontend/src/app/shared/shared.module.ts
- alcs-frontend/src/styles/typography.scss
* Add avatar dropdown menu to header
* Move avatar circle to its own component
* Change typography to only bold flat and stroke buttons
> Add Avatar Menu

- alcs-frontend/src/app/features/application/review/decision-meeting-dialog/decision-meeting-dialog.component.html
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.scss
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.html
- alcs-frontend/src/app/shared/commenting/comment.component.scss
- alcs-frontend/src/app/shared/commenting/comments.component.scss
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- alcs-frontend/src/app/shared/mention-textarea/mention-textarea.component.html
- alcs-frontend/src/app/shared/mention-textarea/mention-textarea.component.scss
- alcs-frontend/src/index.html
- alcs-frontend/src/styles.scss
- alcs-frontend/src/styles/buttons.scss
- alcs-frontend/src/styles/colors.scss
* Apply button styling in most places
* Add scrollbar when card has lots of comments
> Add button styling

- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/overview/overview.component.html
- alcs-frontend/src/app/features/application/processing/processing.component.html
- alcs-frontend/src/app/features/application/review/review.component.html
- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/board.component.scss
- alcs-frontend/src/app/features/home/assigned/assigned.component.scss
- alcs-frontend/src/app/features/home/home.component.html
- alcs-frontend/src/app/features/home/home.component.scss
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.scss
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/header/header.component.html
- alcs-frontend/src/app/shared/header/header.component.scss
- alcs-frontend/src/styles.scss
- alcs-frontend/src/styles/buttons.scss
- alcs-frontend/src/styles/colors.scss
* Apply 80px side margins on all pages across site
* Fix buttons to only titlecase for strokes/flat
> Add app header section

- alcs-api/src/application/application-subtask/application-subtask.service.ts
- alcs-api/src/common/automapper/application.automapper.profile.ts
- alcs-api/src/home/home.controller.ts
- alcs-frontend/src/app/features/application/intake/intake.component.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.scss
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.scss
* Replace null with isNull to only fetch incomplete subtasks
* Change alignment of row to better align dropdowns
* Add min-width to assignee to prevent it from getting squished on smaller screens
> GIS Subtask Fixes

- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/overview/overview.component.html
- alcs-frontend/src/app/features/application/overview/overview.component.scss
- alcs-frontend/src/app/features/application/overview/overview.component.spec.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/shared/timeline/timeline.component.html
- alcs-frontend/src/app/shared/timeline/timeline.component.scss
- alcs-frontend/src/app/shared/timeline/timeline.component.spec.ts
- alcs-frontend/src/app/shared/timeline/timeline.component.ts
* Create generic timeline component
* Add to Overview and add mapping logic
> Add Timeline to Overview

- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/providers/typeorm/migrations/1663271568051-make_region_required.ts
- alcs-frontend/package-lock.json
- alcs-frontend/package.json
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/intake/intake.component.ts
- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.html
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.scss
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.ts
- alcs-frontend/src/app/features/home/home.module.ts
- alcs-frontend/src/app/services/application/application-decision-meeting/application-decision-meeting.service.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/commenting/comment.component.ts
- alcs-frontend/src/app/shared/header/notifications/notifications.component.ts
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- alcs-frontend/src/app/shared/utils/api-date-formatter.ts
- alcs-frontend/src/app/shared/utils/date-format.ts
- alcs-frontend/src/app/shared/utils/matheo-datepicker-formatter.ts
- alcs-frontend/src/environments/environment.prod.ts
- alcs-frontend/src/environments/environment.ts
* Add date format and provider to shared module
* Remove dayjs and use moment everywhere
* Update UI for create card
* Add !important for small fix on board UI
* Make region required in UI and DB
> Update Create Card UI and Standardize Dates

- alcs-frontend/src/app/features/application/application-document/application-document.component.html
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.html
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.scss
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.ts
- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
* added reasons with description
* adjusted validation
* styling fix for application document when no data in table
> Feature/alcs 96: Site Visit/Applicant Meeting

- alcs-api/src/common/authorization/roles.ts
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/home/home.component.html
- alcs-frontend/src/app/features/home/home.component.spec.ts
- alcs-frontend/src/app/features/home/home.component.ts
- alcs-frontend/src/app/features/meeting/meeting.module.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- alcs-frontend/src/app/shared/header/header.component.html
- alcs-frontend/src/app/shared/header/header.component.scss
- alcs-frontend/src/app/shared/header/header.component.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.spec.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
* Move meeting-overview to shared components
> Add Meeting Overview to Commissioner home page

- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.html
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.scss
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.ts
- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.scss
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.scss
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.html
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.scss
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.ts
- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.scss
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.service.ts
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.scss
- alcs-frontend/src/app/shared/timeline/timeline.component.scss
- alcs-frontend/src/environments/environment.prod.ts
- alcs-frontend/src/styles.scss
* Add paused message to dialog
* Style save and cancel buttons
* Unify imports to not have .scss
* Improve error message to include meeting type
* Remove line from timeline if only a single entry
* Add Other: to radio input
* Move info request to 3rd menu position
* Fix date format in prod env
> All the bug fixes

- alcs-api/src/application/application-meeting/application-meeting.entity.ts
- alcs-api/src/providers/typeorm/migrations/1663886615921-nullable_pause.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
* Should remove vett instead of exec
* Make application_pause nullable so we can delete meetings
> Make pause nullable, filter correct boards

- alcs-frontend/.eslintrc.json
- alcs-frontend/angular.json
- alcs-frontend/package-lock.json
- alcs-frontend/package.json
- alcs-frontend/src/app/features/errors/not-found/not-found.component.ts
- alcs-frontend/src/app/features/provision/provision.component.ts
- alcs-frontend/src/app/services/application/application-subtask/application-subtask.service.ts
- alcs-frontend/src/app/services/comment/comment.service.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.ts
- alcs-frontend/src/app/shared/inline-edit/inline-edit.component.ts
* Add ESLint and add in accessbility rules set to warning for now
* Fix existing ESLint errors
> Add ESlint + Fixes

- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/shared/timeline/timeline.component.ts
* Add report dates into timeline if they are present
> Add report dates into timeline

- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.scss
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.html
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.ts
- alcs-frontend/src/app/features/home/home.component.html
- alcs-frontend/src/app/features/home/home.component.ts
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.html
- alcs-frontend/src/app/shared/shared.module.ts
* Use matToolTip instead of title and add missing tooltips
* Change dialogs to be wider, add maxHeight so they overflow properly
* Remove overflow from comments as its now scrolling the whole card
* Add fullName to GIS subtask circles
* Change home page to show multiple components if user has multiple roles
> Card Bug Fixes

- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.ts
- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.ts
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.service.ts
* Update app header to remove old dead fields
* Use new LG field
* Update styling / display of business days
* Fix services to destroy properly
* Update services to re-fetch application on changes, not just the meetings
> Update App Header

- alcs-api/src/application/application.controller.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.entity.ts
- alcs-api/src/providers/typeorm/migrations/1664830683364-add_app_summary.ts
- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/overview/overview.component.html
- alcs-frontend/src/app/features/application/overview/overview.component.scss
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/shared/inline-edit/inline-edit.component.html
- alcs-frontend/src/app/shared/inline-edit/inline-edit.component.scss
- alcs-frontend/src/app/shared/inline-edit/inline-edit.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
* Add summary to application
* Update inline-edit component to newer styling
* Add to Overview page and adjust margins
> Add Proposal Summary

- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/common/automapper/application.automapper.profile.ts
- alcs-frontend/package-lock.json
- alcs-frontend/package.json
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.html
- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/card/card.dto.ts
- alcs-frontend/src/app/shared/utils/api-date-formatter.ts
* Change startOfDay to use actual pacific start of day time
* Remove duplicated assignee from application, use one on card
* Remove accidental highPriority from applicationdto and use one from card
> Bug Fixes + Cleanups

- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.ts
- alcs-frontend/src/app/features/board/recon-card-detail-dialog/recon-card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/recon-card-detail-dialog/recon-card-detail-dialog.component.ts
* Use the board statuses instead of all application statues so we only see statuses for the current board
> Change dialog to use boardStatuses

- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.html
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.html
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.scss
- alcs-frontend/src/app/features/application/review/decision-meeting-dialog/decision-meeting-dialog.component.ts
- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.ts
- alcs-frontend/src/app/features/board/create-card-detail-dialog/create-card-dialog.component.ts
- alcs-frontend/src/app/features/board/recon-create-card-dialog/recon-create-card-dialog.component.ts
- alcs-frontend/src/app/services/application/application-decision/application-decision.service.ts
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.service.ts
- alcs-frontend/src/app/services/application/application.service.ts
- alcs-frontend/src/app/services/toast/toast.service.ts
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.html
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/styles/buttons.scss
- alcs-frontend/src/styles/toast.scss
* Unify toast messages
* Auto open inline datepicker
* Other small changes
> UX Updates Part 1

- alcs-api/src/application/application-meeting/application-meeting.dto.ts
- alcs-api/src/common/automapper/application.automapper.profile.ts
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.ts
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.dto.ts
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.service.ts
* UI allows user to specify end date when creating but it was not being persisted
> Add end date to creation dto

- alcs-api/src/application/application-decision/application-decision.service.ts
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.html
- alcs-frontend/src/app/features/application/overview/overview.component.spec.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/services/application/application-decision/application-decision.service.ts
- alcs-frontend/src/styles/buttons.scss
* Load applications relation to fix bug when editing
* Fix toast messages
* Change icon highlight to use darker gray with opacity so it can be safely applied to different background
> Add Decision Events to Timeline

- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/application.component.spec.ts
- alcs-frontend/src/app/features/application/application.component.ts
* Currently no recons since they aren't added yet
> Add Back to Card button

- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/recon-card-detail-dialog/recon-card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/recon-card-detail-dialog/recon-card-detail-dialog.component.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
* Write them as html instead of plain text
> Handle board statuses being HTML

- alcs-api/src/providers/typeorm/migrations/1665597484462-update_holidays.ts
- alcs-api/src/providers/typeorm/migrations/1665598666114-add_cancel_vetting.ts
* Add / fix holidays
* Add Cancelled status to vetting board
> SQL Migrations for Holidays and New Board Status

- alcs-api/src/main.ts
Apply fastify workaround to prevent denial of service attacks using specific content headers.
> Add fastify workaround

- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/card-detail-dialog/card-detail-dialog.component.scss
- alcs-frontend/src/app/features/board/recon-card-detail-dialog/recon-card-detail-dialog.component.html
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.html
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.scss
- alcs-frontend/src/app/features/home/assigned/assigned.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
- alcs-frontend/src/styles/ngselect.scss
* Change app card and recon card selectors to outline style
* Rename Status to Workflow Stage in various places
* Add No Sub-Tasks indicator
> UX Updates Pt2

- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/board/recon-card-detail-dialog/recon-card-detail-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.spec.ts
- alcs-frontend/src/app/services/authentication/auth-interceptor.service.spec.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- alcs-frontend/src/app/services/authentication/token-refresh.service.spec.ts
- alcs-frontend/src/app/services/authentication/token-refresh.service.ts
- alcs-frontend/src/app/services/user/user.service.spec.ts
- alcs-frontend/src/app/shared/commenting/comments.component.spec.ts
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.spec.ts
- alcs-frontend/src/app/shared/mention-textarea/mention-textarea.component.spec.ts
* Auto refresh token every 4 minutes as long as refresh token isnt expired
* If refresh token becomes expired, redirect user to login
> Improve Token Handling

- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/application/create/create-application-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/planning-review/create/create-planning-review-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/planning-review/planning-review-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/create/create-reconsideration-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.ts
* Since the status is set to the board default, we need to reload the application to update the dropdown value and its options
* Update recon card to have Go to Boar similar to app dialog
> Reload application and board statuses after moving boards

- alcs-api/src/common/authorization/authorization.controller.spec.ts
- alcs-api/src/common/authorization/authorization.service.spec.ts
- alcs-api/src/common/authorization/authorization.service.ts
- alcs-api/src/user/user.module.ts
- alcs-api/src/user/user.service.spec.ts
- alcs-api/src/user/user.service.ts
* send an email on register user if no roles
* added await in exchangeCodeForToken
> ALCS-177: send email on register user if no roles

- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
* fix scrolling to searched item in Scheduled column
> fix meetings scrolling

- alcs-api/src/providers/typeorm/migrations/1666372536278-new_ceo_status.ts
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.ts
* Also fix clicking on cards not working
> Update CEO Boards Status

- alcs-api/src/application/application-decision/application-decision.service.ts
- alcs-frontend/src/app/app.component.scss
- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/decision/decision.component.html
- alcs-frontend/src/app/features/application/decision/decision.component.scss
- alcs-frontend/src/app/features/application/decision/decision.component.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/dialogs/planning-review/planning-review-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.ts
- alcs-frontend/src/app/features/meeting/meeting.component.html
- alcs-frontend/src/app/services/application/application-code.dto.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.spec.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/commenting/comment.component.scss
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.spec.ts
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.html
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.ts
- alcs-frontend/src/app/shared/header/header.component.html
- alcs-frontend/src/styles.scss
* Change layout overflow so that board and sticky headers scroll bar nicely
* Add border color to labels so we have more visual options
* Add loading indicator to decisions for attach/delete file/delete decision
* Change comments white-space so it preserves line breaks
* Add disable-able tooltips to Favourite button
> UX Updates

- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.ts
- alcs-frontend/src/app/shared/application-header/application-header.component.html
- alcs-frontend/src/app/shared/application-header/application-header.component.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
* Change meetings page to go directly to review page if not a comissioner
* Use setters so that when the input changes the logic is re-ran
> Commissioner Fixes

- alcs-api/src/application-amendment/application-amendment.controller.ts
- alcs-api/src/application-reconsideration/application-reconsideration.controller.ts
- alcs-api/src/application/application-decision/application-decision.controller.ts
- alcs-api/src/application/application-document/application-document.controller.ts
- alcs-api/src/card/card-subtask/card-subtask.controller.ts
- alcs-frontend/src/app/features/application/overview/overview.component.spec.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.html
* Clean up deleted responses
* Fix casing to be consistent on overview timeline
> Add Amendments to overview timeline

- alcs-api/src/commissioner/commissioner.controller.spec.ts
- alcs-api/src/commissioner/commissioner.controller.ts
- alcs-api/src/commissioner/commissioner.dto.ts
- alcs-api/src/commissioner/commissioner.module.ts
- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.ts
- alcs-frontend/src/app/services/commissioner/commissioner.dto.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
- alcs-frontend/src/app/shared/application-header/application-header.component.html
- alcs-frontend/src/app/shared/application-header/application-header.component.ts
* Add recon and amendment flags to show pills in header
* Fix issue with lazy loaded application not causing documents table to re-load
* Fix variable used to create decision meetings
> Bug Fixes for Commissioners

- alcs-api/src/common/automapper/user.automapper.profile.ts
- alcs-api/src/user/user.controller.ts
- alcs-frontend/src/app/features/board/dialogs/amendment/amendment-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.scss
- alcs-frontend/src/app/services/user/user.service.ts
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.html
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.scss
- alcs-frontend/src/app/shared/avatar-circle/avatar-circle.component.ts
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.scss
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.ts
- alcs-frontend/src/app/shared/header/header.component.html
- alcs-frontend/src/app/shared/header/header.component.scss
- alcs-frontend/src/app/shared/header/notifications/notifications.component.html
- alcs-frontend/src/app/shared/header/notifications/notifications.component.scss
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.scss
- alcs-frontend/src/assets/images/ALC-logo.svg
- alcs-frontend/src/index.html
- alcs-frontend/src/styles.scss
- alcs-frontend/src/styles/colors.scss
- alcs-frontend/src/styles/typography.scss
* Fix favourite to work
* Update header and logo
* Update favourite star icon colour
* Change to outlined icons
> New Header + Bug fixes

- alcs-api/src/application/application-decision-meeting/application-decision-meeting.controller.ts
- alcs-api/src/application/application-decision-meeting/application-decision-meeting.service.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.scss
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.scss
* Remove previous filter
* Fix minor CSS issues on home page
> Show apps with decision on meetings page

- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/shared/application-header/application-header.component.html
* Was showing single button due to lack of check on Amendments
* Bonus fixes
> Show dropdown if amendments are present

- alcs-api/package.json
- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.dto.ts
- alcs-api/src/application/application.service.ts
- alcs-api/src/common/automapper/application.automapper.profile.ts
- alcs-api/src/import/import.service.spec.ts
- alcs-api/src/import/import.service.ts
- alcs-frontend/package.json
* Set imported times to beginning of Vancouver day
* Fix ApplicationDto mapping to use numbers
> Set Import Dates to Vancouver Time

- alcs-api/src/common/automapper/amendment.automapper.profile.ts
- alcs-api/src/common/automapper/reconsideration.automapper.profile.ts
- alcs-api/src/decision/application-amendment/application-amendment.dto.ts
- alcs-api/src/decision/application-amendment/application-amendment.entity.ts
- alcs-api/src/decision/application-amendment/application-amendment.service.spec.ts
- alcs-api/src/decision/application-amendment/application-amendment.service.ts
- alcs-api/src/decision/application-decision/application-decision.entity.ts
- alcs-api/src/decision/application-reconsideration/application-reconsideration.dto.ts
- alcs-api/src/decision/application-reconsideration/application-reconsideration.entity.ts
- alcs-api/src/decision/application-reconsideration/application-reconsideration.service.spec.ts
- alcs-api/src/decision/application-reconsideration/application-reconsideration.service.ts
- alcs-api/src/providers/typeorm/migrations/1668105252152-regenerate_amends_decisions_fks.ts
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.ts
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.spec.ts
- alcs-frontend/src/app/services/application/application-amendment/application-amendment.dto.ts
- alcs-frontend/src/app/services/application/application-reconsideration/application-reconsideration.dto.ts
* Update entities to have links both ways and use OneToOne
* Regenerate FKs to add in Unique constraints
* Filter list of post decisions to ones that are not refuse and are not already linked to a Decision
> Add link from Amends/Recons -> Resulting Decision

- alcs-api/src/queues/scheduler/scheduler.service.spec.ts
- alcs-api/src/queues/scheduler/scheduler.service.ts
- alcs-frontend/src/app/features/application/decision/decision.component.html
Fix extra space on decisions component
> Disable notifications job

- alcs-api/src/common/automapper/application-decision.automapper.profile.ts
- alcs-api/src/decision/application-decision/application-decision.dto.ts
- alcs-api/src/decision/application-decision/application-decision.service.ts
- alcs-frontend/src/app/features/application/decision/decision.component.html
- alcs-frontend/src/app/features/application/decision/decision.component.scss
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.html
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.scss
- alcs-frontend/src/app/services/application/application-decision/application-decision.dto.ts
* Add UI to indicate if a decisions has been modified or amended
> Show if a decision was recond/amended by another decision

- alcs-api/src/providers/typeorm/migrations/1668468834615-rename_card_status.ts
- alcs-frontend/src/app/app-routing.module.ts
- alcs-frontend/src/app/features/application/review/decision-meeting-dialog/decision-meeting-dialog.component.ts
- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.html
- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.ts
- alcs-frontend/src/app/shared/header/header.component.html
* Review page + New Meeting -> + New Discussion
* Toasts on Review page  Review Meeting > Review Discussion
* Schedule page URL /meeting -> /schedule
* kanban column update
> rename meeting to schedule/discussion

- alcs-api/src/decision/application-decision/application-decision.service.ts
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision.component.html
- alcs-frontend/src/app/features/application/decision/decision.component.scss
- alcs-frontend/src/app/features/application/decision/decision.component.ts
* Fix query to load sibling decisions
* Change filter to include the already selected modification / reconsideration so it shows in the dropdown
> Add Type Pill to Decisions

- alcs-api/src/application/application.controller.spec.ts
- alcs-api/src/application/application.controller.ts
- alcs-api/src/common/automapper/application-decision.automapper.profile.ts
- alcs-api/src/decision/application-decision/application-decision.dto.ts
- alcs-api/src/decision/application-decision/application-decision.entity.ts
- alcs-api/src/decision/application-decision/application-decision.service.ts
- alcs-api/src/providers/typeorm/migrations/1668472960811-add_other_to_decision.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.scss
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision.component.html
- alcs-frontend/src/app/services/application/application-decision/application-decision.dto.ts
* User can now select either or both, one must be selected
* Update form control to use multi select instead of toggle group
* Add new column is_other to track new boolean
* Add more tests to application controller to improve coverage
> Change Time Extention or Other to Multi-select

- alcs-frontend/src/app/features/application/decision/decision.component.html
- alcs-frontend/src/app/features/application/decision/decision.component.scss
- alcs-frontend/src/app/features/application/decision/decision.component.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.scss
- alcs-frontend/src/app/shared/application-header/application-header.component.html
- alcs-frontend/src/app/shared/application-header/application-header.component.scss
- alcs-frontend/src/app/shared/application-time-tracker/application-time-tracker.component.html
- alcs-frontend/src/app/shared/application-time-tracker/application-time-tracker.component.scss
- alcs-frontend/src/app/shared/application-time-tracker/application-time-tracker.component.spec.ts
- alcs-frontend/src/app/shared/application-time-tracker/application-time-tracker.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
* Show time on first decision card and overview timeline
> Move application time to its own component

- alcs-api/src/common/automapper/modification.automapper.profile.ts
- alcs-api/src/decision/application-modification/application-modification.dto.ts
- alcs-api/src/decision/application-modification/application-modification.service.spec.ts
- alcs-api/src/decision/application-modification/application-modification.service.ts
- alcs-frontend/src/app/features/board/board.component.ts
* Ensure that front end and back end are using same name variables
* Map Card manually as AutoMapper stopped doing it
> Fix Modification Creation and Cards

- alcs-api/src/common/automapper/application-decision.automapper.profile.ts
- alcs-api/src/decision/application-decision/application-decision.dto.ts
- alcs-api/src/decision/application-decision/application-decision.entity.ts
- alcs-api/src/decision/application-decision/application-decision.service.spec.ts
- alcs-api/src/decision/application-decision/application-decision.service.ts
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision.component.ts
- alcs-frontend/src/app/services/application/application-decision/application-decision.service.ts
- added validation of resolution number and year on create/update
- added ability to update resolution year and number
- fixed issue with the wrong chair review outcome
- fixed issue with wrong resolution year on update
- do not close dialogue if update/create failed
> added validation of resolution number on create

- alcs-api/src/decision/application-decision/application-decision.dto.ts
- alcs-api/src/decision/application-decision/application-decision.service.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- fixed inline edit on decision meeting
- changed scheduled discussion sorting
> update meeting sorting, fix inline edit on decision

- alcs-api/src/providers/typeorm/migrations/1669403592926-rename_card_status_and_update_app_type_color.ts
- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/board.component.scss
- alcs-frontend/src/app/shared/application-header/application-header.component.scss
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/commenting/comment.component.html
- alcs-frontend/src/app/shared/commenting/comment.component.scss
- alcs-frontend/src/app/shared/commenting/comments.component.html
- alcs-frontend/src/app/shared/commenting/comments.component.scss
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/favorite-button/favorite-button.component.scss
- alcs-frontend/src/app/shared/header/header.component.scss
- alcs-frontend/src/app/shared/header/notifications/notifications.component.scss
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.scss
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/styles/buttons.scss
- alcs-frontend/src/styles/colors.scss
- alcs-frontend/src/styles/ngselect.scss
- alcs-frontend/src/styles/typography.scss
* Paused card
* Date card
* Paused date card
* Header nav menu
* Application detail side nav
* Ng-select border colours
* Button transition
* Schedule card
* Kanban board header + column
* Comments
> ALCS-201: UX/UI Update

- alcs-frontend/src/app/features/home/home.component.html
- alcs-frontend/src/app/features/home/home.component.spec.ts
- alcs-frontend/src/app/features/home/home.component.ts
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- alcs-frontend/src/app/services/user/user.dto.ts
- services/apps/alcs/src/common/automapper/user.automapper.profile.ts
- services/apps/alcs/src/user/user.dto.ts
update display format of IDIR username
> fix for IDIR user

- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/application/create/create-application-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/covenant/covenant-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/covenant/covenant-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/covenant/create/create-covenant-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/create/create-reconsideration-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/create/create-reconsideration-dialog.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.scss
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.html
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.scss
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/styles.scss
Some more UX updates after QA:
* Add hover effects to application panels in schedule page
* Increase font weight to bold search button text in schedule page
* Add card subtask tooltip
* Update application, recon, and cov dialogs icon button styling
* Update all create dialog paddings
> ALCS-201: More UX Updates

- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/commissioner/commissioner.component.ts
- alcs-frontend/src/app/features/home/home.component.ts
- alcs-frontend/src/app/features/meeting/meeting.component.ts
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- alcs-frontend/src/environments/environment.prod.ts
- alcs-frontend/src/environments/environment.ts
* Fix search on schedule page not scrolling / highlighting
* Fix search bar not showing warning when search fails
* Add dynamic titles per page
> UI Fixes and Titles

- alcs-frontend/src/app/features/home/home.component.ts
- services/apps/alcs/src/application/application.dto.ts
- services/apps/alcs/src/application/application.entity.ts
- services/apps/alcs/src/common/automapper/application-decision.automapper.profile.ts
- services/apps/alcs/src/common/automapper/application-subtask.automapper.profile.ts
- services/apps/alcs/src/common/automapper/application.automapper.profile.ts
- services/apps/alcs/src/common/automapper/modification.automapper.profile.ts
- services/apps/alcs/src/common/automapper/reconsideration.automapper.profile.ts
- services/apps/alcs/src/decision/application-decision/application-decision.dto.ts
- services/apps/alcs/src/decision/application-decision/application-decision.entity.ts
* Add () => Boolean to remove need to manually map, same with string
> Automapper Cleanup

- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.html
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.scss
- alcs-frontend/src/app/features/application/intake/intake.component.scss
- alcs-frontend/src/app/features/application/overview/overview.component.scss
- alcs-frontend/src/app/features/application/review/decision-meeting/decision-meeting.component.html
- alcs-frontend/src/app/features/application/review/review.component.scss
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.html
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.scss
- alcs-frontend/src/app/features/home/assigned/assigned.component.html
- alcs-frontend/src/app/features/home/audit/audit-subtasks.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.scss
- alcs-frontend/src/app/shared/inline-edit/inline-edit.component.scss
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/styles/colors.scss
Some more UX updates to address QA feedback:
- Add back sticky column header on vertical scroll
- Change application side nav icons and hover effects
- Update all table elevations and app detail headings
- Update search input and proposal component styling
- Update app card subtask UI + hover effect
> ALCS-201: More UX Updates 2

- .github/workflows/ci.yml
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- services/apps/alcs/src/document/document.service.ts
- services/config/default.json
* Set meeting scroll to center element
> Add file upload

- services/apps/alcs/src/decision/application-decision-meeting/application-decision-meeting.service.ts
* Do not show in meetings view
> Hide Decision Released Cards

- portal-frontend/src/app/features/edit-application/edit-application.component.html
- portal-frontend/src/app/features/edit-application/edit-application.component.ts
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
* Add type=button to prevent enter from doing anything
* Sort local governments alphabetically
> Bug Fixes for Create Application

- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/covenant/covenant-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/covenant/covenant-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/modification/modification-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/modification/modification-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/planning-review/planning-review-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/planning-review/planning-review-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.ts
- alcs-frontend/src/app/features/board/subtasks/subtasks.component.html
- alcs-frontend/src/app/features/home/audit/audit-subtasks.component.html
- alcs-frontend/src/app/features/home/audit/audit-subtasks.component.ts
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.ts
- alcs-frontend/src/app/services/user/user.dto.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html
- services/apps/alcs/src/common/automapper/user.automapper.profile.ts
- services/apps/alcs/src/user/user.dto.ts
Replace usages of name to prettyName
> Add PrettyName to AssigneeDto

- docs/jobs.md
* Add comment for namespace
* Move conditions to proper place
> Minor yml fixes

- .github/workflows/schemaspy.yml
- README.md
- Add flag to scan alcs and portal schema
- Update URLs to new Locations
> Re-enable Schemaspy

- alcs-frontend/angular.json
- alcs-frontend/nginx.conf
- docker/postgres-schemas.sql
- portal-frontend/angular.json
- portal-frontend/nginx.conf
- services/apps/alcs/src/providers/typeorm/datasource.cli.orm.config.ts
- services/apps/alcs/src/providers/typeorm/migrations/1560859890135-add-freeze.ts
- services/apps/alcs/src/providers/typeorm/orm.config.ts
- services/config/default.json
* Add Missing Migration
* Set angular to not inline CSS
> Add Nginx Security Headers

- services/apps/alcs/src/application/application-document/application-document.service.ts
- services/apps/alcs/src/document/document.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1671063267807-update_document_table_add_default_source.ts
* add default value for existing docs
> add default value for existing docs

- .github/workflows/zap_api.yml
- .github/workflows/zap_frontend.yml
- .zap/frontend.tsv
- alcs-frontend/nginx.conf
- alcs-frontend/src/index.html
- portal-frontend/nginx.conf
- portal-frontend/src/index.html
* Add two actions, one for api one for backend
* Set to manual dispatch
* Prepare initial rules file
> Add Zap in Manual Dispatch Mode

- services/apps/alcs/src/card/card-status/card-status.entity.ts
- services/apps/alcs/src/decision/application-decision-meeting/application-decision-meeting.service.ts
- services/apps/alcs/src/home/home.controller.spec.ts
- services/apps/alcs/src/home/home.controller.ts
* Add enum for statuses and re-use in meeting components
> Add filter to assigned tasks to exclude cancelled and decision released

- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.entity.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1671209228391-add_business_guid.ts
- services/apps/portal/src/alcs/local-government/local-government.service.ts
- services/apps/portal/src/application/application.controller.spec.ts
- services/apps/portal/src/application/application.controller.ts
- services/apps/portal/src/application/application.service.ts
- services/apps/portal/src/common/authorization/authorization.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1671209262404-add_business_guid_user.ts
- services/apps/portal/src/user/user.entity.ts
* Add business beid guid column to local governments
* Load in Portal and if user has matching share applications among those users
> Add Business Lookup by Shared Guids

- portal-frontend/src/app/app.module.ts
- portal-frontend/src/app/features/edit-application/edit-application.component.html
- portal-frontend/src/app/features/edit-application/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-entry/parcel-entry.component.scss
- portal-frontend/src/app/features/edit-application/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/edit-application/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/services/parcel/parcel.dto.ts
- portal-frontend/src/app/services/parcel/parcel.service.spec.ts
- portal-frontend/src/app/services/parcel/parcel.service.ts
- services/apps/portal/src/parcel/parcel-lookup.entity.ts
- services/apps/portal/src/parcel/parcel.controller.spec.ts
- services/apps/portal/src/parcel/parcel.controller.ts
- services/apps/portal/src/parcel/parcel.dto.ts
- services/apps/portal/src/parcel/parcel.module.ts
- services/apps/portal/src/parcel/parcel.service.spec.ts
- services/apps/portal/src/parcel/parcel.service.ts
- services/apps/portal/src/portal.module.ts
- services/apps/portal/src/providers/typeorm/migrations/1672774940651-add_parcel_lookup.ts
* Add ParcelLookup entity that matches GIS teams export
* Add controller / service to perform lookups
* Add front end form / component for performing lookup
> Add ParcelLookups and Controller

- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.html
- alcs-frontend/src/app/features/home/gis/gis-subtasks.component.ts
- alcs-frontend/src/app/shared/pipes/safe.pipe.ts
- alcs-frontend/src/app/shared/shared.module.ts
- alcs-frontend/src/environments/environment.prod.ts
- alcs-frontend/src/environments/environment.ts
> Add embedded GIS Dashboard to GIS Home Page

- alcs-frontend/src/app/features/application/overview/overview.component.ts
- services/apps/alcs/src/common/automapper/application-decision.automapper.profile.ts
* Fix decision date being sent as a string instead of number
> Add sorting to overview component

- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.controller.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.dto.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.entity.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.service.ts
- services/apps/alcs/src/application/application.controller.spec.ts
- services/apps/alcs/src/providers/typeorm/migrations/1672962786580-first_nations_government.ts
- services/apps/portal/src/alcs/code/code.controller.spec.ts
- services/apps/portal/src/alcs/local-government/local-government.service.ts
- services/apps/portal/src/application/application.controller.spec.ts
- services/apps/portal/src/portal.module.ts
> added isFirstNation

- portal-frontend/src/app/features/edit-application/edit-application.component.ts
- portal-frontend/src/app/features/home/application-list/application-list.component.html
- portal-frontend/src/app/features/home/application-list/application-list.component.scss
- portal-frontend/src/app/services/application/application.dto.ts
- services/apps/portal/src/alcs/local-government/local-government.service.ts
- services/apps/portal/src/application/application-document/application-document.controller.spec.ts
- services/apps/portal/src/application/application-document/application-document.controller.ts
- services/apps/portal/src/application/application-document/application-document.entity.ts
- services/apps/portal/src/application/application-document/application-document.service.spec.ts
- services/apps/portal/src/application/application-status/application-status.dto.ts
- services/apps/portal/src/application/application-status/application-status.entity.ts
- services/apps/portal/src/application/application.controller.spec.ts
- services/apps/portal/src/application/application.controller.ts
- services/apps/portal/src/application/application.dto.ts
- services/apps/portal/src/application/application.service.spec.ts
- services/apps/portal/src/application/application.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1669680170073-seed_app_status.ts
- services/apps/portal/src/providers/typeorm/migrations/1673042070216-update_app_statuses.ts
* Add new flags to control which actions can be taken on the inbox page to applications
* Add loading of submitted to LG applications to attached accounts
* Add new Submitted to L/FNG Status
> Add loading of submitted applications to Governments

- portal-frontend/src/app/app-routing.module.ts
- portal-frontend/src/app/app.module.ts
- portal-frontend/src/app/features/edit-application/edit-application.component.ts
- portal-frontend/src/app/features/home/application-list/application-list.component.html
- portal-frontend/src/app/features/home/application-list/application-list.component.ts
- portal-frontend/src/app/features/view-application/view-application.component.html
- portal-frontend/src/app/features/view-application/view-application.component.scss
- portal-frontend/src/app/features/view-application/view-application.component.spec.ts
- portal-frontend/src/app/features/view-application/view-application.component.ts
- portal-frontend/src/app/services/document/document.dto.ts
- portal-frontend/src/styles/buttons.scss
- services/apps/portal/src/application/application.controller.spec.ts
- services/apps/portal/src/application/application.controller.ts
- services/apps/portal/src/application/application.service.spec.ts
- services/apps/portal/src/application/application.service.ts
* Add View page accessible by LGs and Applicants
* Move edit/cancel/review buttons to new page
* Update getApplication to allow LGs to fetch submitted applications
> Add Application View Page

- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
* fixed decision date
* updated timeline label
> fix decision date

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.ts
- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.html
- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.ts
* fix read more inconsistent behaviour
* do not remove selected type value on navigating between steps
* refactor read more in create dialog
> fix read more

- portal-frontend/src/app/features/review-application/review-application.component.html
- portal-frontend/src/app/features/review-application/review-application.component.ts
- portal-frontend/src/app/features/review-application/review-application.module.ts
- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.html
- portal-frontend/src/app/features/review-application/review-contact-information/review-contact-information.component.html
- portal-frontend/src/app/features/review-application/review-contact-information/review-contact-information.component.ts
- portal-frontend/src/app/features/review-application/review-resolution/review-resolution.component.html
- portal-frontend/src/app/features/review-application/review-resolution/review-resolution.component.ts
- portal-frontend/src/app/features/review-application/review-submit-fng/review-submit-fng.component.html
- portal-frontend/src/app/features/review-application/review-submit-fng/review-submit-fng.component.scss
- portal-frontend/src/app/features/review-application/review-submit-fng/review-submit-fng.component.spec.ts
- portal-frontend/src/app/features/review-application/review-submit-fng/review-submit-fng.component.ts
- portal-frontend/src/app/services/application-review/application-review.dto.ts
- services/apps/portal/src/alcs/application-grpc/alcs-application.message.interface.ts
- services/apps/portal/src/application-review/application-review.controller.spec.ts
- services/apps/portal/src/application-review/application-review.controller.ts
- services/apps/portal/src/application-review/application-review.dto.ts
- services/apps/portal/src/application-review/application-review.service.spec.ts
- services/apps/portal/src/application-review/application-review.service.ts
* Slightly different labels and different flow
> Add First Nation Government Review

- services/apps/alcs/src/providers/typeorm/migrations/1674082002832-adjust_board_statuses.ts
* Rename and add new CEO statuses
* Add new status for Soil/fill
> Adjust Board Statuses

- portal-frontend/src/app/features/home/application-list/application-list.component.scss
* Update mapping so that all statuses have a colour
> Update Application Status Colors

- alcs-frontend/src/app/features/board/dialogs/modification/modification-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/modification/modification-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.scss
- alcs-frontend/src/app/shared/application-header/application-header.component.html
- alcs-frontend/src/app/shared/application-header/application-header.component.scss
- alcs-frontend/src/app/shared/application-type-pill/application-type-pill.component.scss
* Add wrapping to type pills when multiple are present
> Update Cards / Application Page to Wrap Type Pills

- services/apps/alcs/src/providers/typeorm/migrations/1674082002832-adjust_board_statuses.ts
* Column should be 3rd column, not second
> Fix Column Ordering for Soil/Fill

- alcs-frontend/package-lock.json
- alcs-frontend/package.json
- portal-frontend/package-lock.json
- portal-frontend/package.json
* Add jest-preset-angular, not needed in alcs-frontend for some reason
* Match jest types to installed jest version
> Fix Portal CI

- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- services/apps/portal/src/parcel/parcel-lookup.entity.ts
- services/apps/portal/src/parcel/parcel.controller.spec.ts
- services/apps/portal/src/parcel/parcel.controller.ts
- services/apps/portal/src/parcel/parcel.dto.ts
- services/apps/portal/src/parcel/parcel.service.spec.ts
- services/apps/portal/src/parcel/parcel.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1674586420544-parcel_lookup_v2.ts
* Re-do table to match new export
* Remove checking for 0 since its now correctly null
* Fix column names
* Change to string input so it doesnt removing leading 0s
> Parce Lookup V2

- portal-frontend/src/app/features/edit-application/select-government/select-government.component.html
- portal-frontend/src/app/features/edit-application/select-government/select-government.component.ts
- portal-frontend/src/app/shared/warning-banner/warning-banner.component.html
- portal-frontend/src/app/shared/warning-banner/warning-banner.component.scss
- portal-frontend/src/app/shared/warning-banner/warning-banner.component.ts
* Hide warning if LG has guid
* Change CSS class names to resolve conflicts
* Update save and exit / next step buttons
> Clean up LG Page

- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.html
- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.scss
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.html
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.scss
- alcs-frontend/src/app/shared/application-header/application-header.component.scss
- alcs-frontend/src/app/shared/application-type-pill/application-type-pill.component.scss
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.html
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.scss
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss
- alcs-frontend/src/styles.scss
- alcs-frontend/src/styles/buttons.scss
- alcs-frontend/src/styles/ngselect.scss
- portal-frontend/src/styles/buttons.scss
- portal-frontend/src/styles/form-controls.scss
* inline date picker
* replace mtx date picker with material date picker
* part 1 overall styling fixes
> Bugfix/alcs 390 - style fixes

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.scss
- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.html
- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.scss
- portal-frontend/src/app/features/edit-application/edit-application.component.ts
- portal-frontend/src/app/features/home/home.component.ts
- portal-frontend/src/styles.scss
- portal-frontend/src/styles/dialog.scss
* fix scroll when 500% zoom,
* fix radio buttons in modals
> fix scroll when 500 zoom, fix radio buttons in modals

- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/covenant/covenant-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/covenant/covenant-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/modification/modification-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/modification/modification-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/planning-review/planning-review-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/planning-review/planning-review-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.ts
- alcs-frontend/src/app/services/comment/comment.dto.ts
- alcs-frontend/src/app/services/comment/comment.service.spec.ts
- alcs-frontend/src/app/shared/commenting/comment.component.html
- alcs-frontend/src/app/shared/commenting/comment.component.ts
- alcs-frontend/src/app/shared/commenting/comments.component.html
- alcs-frontend/src/app/shared/commenting/comments.component.ts
- alcs-frontend/src/app/shared/header/notifications/notifications.component.scss
- alcs-frontend/src/app/shared/mention-textarea/mention-textarea.component.ts
- services/apps/alcs/src/application/application.controller.spec.ts
- services/apps/alcs/src/card/card.service.ts
- services/apps/alcs/src/comment/comment.controller.spec.ts
- services/apps/alcs/src/comment/comment.controller.ts
- services/apps/alcs/src/comment/comment.dto.ts
- services/apps/alcs/src/comment/comment.service.spec.ts
- services/apps/alcs/src/comment/comment.service.ts
- services/apps/alcs/src/notification/notification.service.ts
* Comments are not always on applications
* Add it in to the DTO so that the backend doesn't need to understand each entity type
> Accept notification title as param instead of loading application

- services/apps/alcs/src/application/application-meeting/application-meeting.service.ts
* Null values are already handled below
> Remove null values from creating meeting pause

- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.ts
- portal-frontend/src/styles/dialog.scss
* Remove dialog change until we can fix differently
> Fix added parcels not showing owners

- portal-frontend/src/styles/dialog.scss
- portal-frontend/src/styles/typography.scss
* Move scrolling to inside the dialog to prevent issues
* Remove button line-height as it was breaking buttons with wrapped text
> Move dialog scrollbar to its contents

- portal-frontend/src/app/features/edit-application/edit-application.component.ts
- portal-frontend/src/app/services/application/application.service.ts
- services/apps/portal/src/application/application.service.ts
* Remove DTO that is no longer accepted
> Hard-code applicant to fileNumber

- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.html
- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.html
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.ts
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.scss
- services/apps/portal/src/application-review/application-review.service.spec.ts
- services/apps/portal/src/application-review/application-review.service.ts
- services/apps/portal/src/application/application-document/application-document.service.spec.ts
- services/apps/portal/src/application/application-document/application-document.service.ts
* Make staff report optional when app is not authorized
* Fix number
* Open Step 4 panel when its not valid
* Add No data to optional attachments
* Delete staff report and resolution document if application is no ocp/zoning
> Fixes for ALCS-100

- portal-frontend/src/app/features/edit-application/other-attachments/other-attachments.component.spec.ts
- portal-frontend/src/app/features/edit-application/other-parcels/other-parcels.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/application-owner-dialog/application-owner-dialog.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/application-owners-dialog/application-owners-dialog.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.spec.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-owners/parcel-owners.component.ts
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.ts
- portal-frontend/src/app/services/application-owner/application-owner.dto.ts
- portal-frontend/src/app/services/application-owner/application-owner.service.spec.ts
- portal-frontend/src/app/services/application-parcel/application-parcel.dto.ts
- services/apps/portal/src/application/application-owner/application-owner.controller.spec.ts
- services/apps/portal/src/application/application-owner/application-owner.controller.ts
- services/apps/portal/src/application/application-owner/application-owner.dto.ts
- services/apps/portal/src/application/application-owner/application-owner.service.spec.ts
- services/apps/portal/src/application/application-owner/application-owner.service.ts
- services/apps/portal/src/application/application-parcel/application-parcel.controller.spec.ts
- services/apps/portal/src/application/application-parcel/application-parcel.dto.ts
- services/apps/portal/src/application/application-parcel/application-parcel.service.spec.ts
- services/apps/portal/src/application/application-parcel/application-parcel.service.ts
- services/apps/portal/src/application/application.service.ts
* Change code to no longer re-load the application but just owners
* Only link owners to parcels when pressing save
> Make owners only save on parcel when parcel saves

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.scss
- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.html
- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.scss
- portal-frontend/src/app/features/edit-application/parcel-details/delete-parcel/delete-parcel-dialog.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/delete-parcel/delete-parcel-dialog.component.scss
- portal-frontend/src/app/shared/warning-banner/warning-banner.component.scss
- portal-frontend/src/styles/dialog.scss
- portal-frontend/src/styles/form-controls.scss
Update dialogs to angular 15 style and remove old scroll fix
> Dialog Fixes

- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/features/review-application/review-contact-information/review-contact-information.component.html
- portal-frontend/src/app/features/review-application/review-resolution/review-resolution.component.html
- portal-frontend/src/app/features/review-application/review-submit-fng/review-submit-fng.component.html
- portal-frontend/src/app/features/review-application/review-submit-fng/review-submit-fng.component.scss
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.html
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.scss
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.ts
- portal-frontend/src/app/features/view-application/view-application.component.html
- portal-frontend/src/app/features/view-application/view-application.component.scss
- portal-frontend/src/app/features/view-application/view-application.component.ts
* Add new text when user has not answered step2/3 questions for step 4
* Fix errors for step 2/3 first questions
* stop angular from moving the icon to the left of the button by wrapping it in a div
> ALCS-100 Bug Fixes

- portal-frontend/src/app/features/edit-application/edit-application.component.scss
- portal-frontend/src/app/features/edit-application/land-use/land-use.component.html
- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/edit-application/other-attachments/other-attachments.component.html
- portal-frontend/src/app/features/edit-application/other-attachments/other-attachments.component.scss
- portal-frontend/src/app/features/edit-application/other-attachments/other-attachments.component.ts
- portal-frontend/src/app/features/edit-application/other-parcels/other-parcels.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.html
- portal-frontend/src/app/features/edit-application/select-government/select-government.component.html
- portal-frontend/src/app/services/application-document/application-document.service.ts
* Add previous step to all existing steps missing it
* Save before adding/removing files
> File Upload Fixes

- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.html
- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.html
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.ts
Add new text that explains to user to complete earlier steps before doing uploads
> Conditional Text for LG Review

- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
* Add/Added was not being updated as it was being selected, introduce a new function with the shared logic and use it wherever we update the parcels owners
> Update internal owners array when selecting/deselecting owners

- alcs-frontend/src/app/features/admin/holiday/holiday.component.html
- alcs-frontend/src/app/features/admin/holiday/holiday.component.scss
- alcs-frontend/src/app/features/admin/holiday/holiday.component.ts
- alcs-frontend/src/app/services/stat-holiday/holiday.service.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.service.ts
- services/apps/alcs/src/admin/holiday/holiday.controller.ts
- services/apps/alcs/src/admin/holiday/holiday.service.spec.ts
- services/apps/alcs/src/admin/holiday/holiday.service.ts
* Load all year values and use a dropdown
> Change stat holiday filter to use dropdown instead of input

- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/services/parcel/parcel.dto.ts
- services/apps/portal/src/parcel/parcel.controller.ts
- services/apps/portal/src/parcel/parcel.dto.ts
- services/apps/portal/src/parcel/parcel.service.ts
* set max date for purchasedDate
* lookup improvements:
* search if dashes provided in search field
* add leading 0 if needed for pid
* based on lookup result populate pid
* reset only lookup related fields
> lookup improvements

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.ts
Was being called both in service and component
> Remove duplicate showSpinner

- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/application/application.service.spec.ts
- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/features/review-application/review-submit/review-submit.component.ts
- services/apps/alcs/src/application-grpc/alcs-application.controller.spec.ts
- services/apps/alcs/src/application-grpc/alcs-application.controller.ts
- services/apps/alcs/src/application-grpc/alcs-application.message.interface.ts
- services/apps/alcs/src/application-grpc/alcs-application.proto
- services/apps/alcs/src/application/application.dto.ts
- services/apps/alcs/src/application/application.entity.ts
- services/apps/alcs/src/application/application.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1676487035977-add_status_history_to_alcs.ts
- services/apps/portal/src/alcs/application-grpc/alcs-application.message.interface.ts
- services/apps/portal/src/alcs/application-grpc/alcs-application.proto
- services/apps/portal/src/application-review/application-review.controller.ts
- services/apps/portal/src/application/application-status.subscriber.spec.ts
- services/apps/portal/src/application/application-status.subscriber.ts
- services/apps/portal/src/application/application.controller.ts
- services/apps/portal/src/application/application.entity.ts
- services/apps/portal/src/application/application.module.ts
- services/apps/portal/src/application/application.service.spec.ts
- services/apps/portal/src/application/application.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1676410924348-add_portal_app_history.ts
* Add new columns to hold JSON data
* Add subscriber to track any status changes in the portal
* Send to ALCS and show in Overview timeline
> Track portal statuses and send to ALCS

- portal-frontend/src/app/app.component.html
* This allows all popups to scroll when scrolling appBody
> Enable scroll event detection on main body

- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.ts
- portal-frontend/src/app/services/application/application.dto.ts
- services/apps/portal/src/application/application.dto.ts
- services/apps/portal/src/application/application.entity.ts
- services/apps/portal/src/application/application.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1676592772371-update_nfu_duration.ts
- services/apps/portal/src/utils/column-numeric-transform.ts
* Re-organize page
* Change dropdown at bottom to size and units
* Allow decimals on all numeric fields
* Add transformer as typeorm returns decimals as strings
> Step 6 Updates

- alcs-frontend/src/app/features/application/application-meeting/application-meeting-dialog/application-meeting-dialog.component.ts
- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.html
- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.html
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.ts
- alcs-frontend/src/app/features/application/info-requests/info-rquest-dialog/info-request-dialog.component.ts
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.service.spec.ts
- alcs-frontend/src/app/services/application/application-meeting/application-meeting.service.ts
- portal-frontend/src/app/features/edit-application/land-use/land-use.component.html
- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/edit-application/other-parcels/other-parcels.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.html
- portal-frontend/src/app/features/edit-application/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/edit-application/select-government/select-government.component.html
* Update toast messages on meeting service to show type dynamically
* Add required message to portal steps 1-6
* Change volume placeholder
> Various changes

- portal-frontend/src/app/features/edit-application/edit-application.component.html
- portal-frontend/src/app/features/edit-application/edit-application.component.scss
- portal-frontend/src/app/features/edit-application/primary-contact/primary-contact.component.ts
* Load owners directly from service when loading primary contact page
* Fix CSS
> Load owners when loading primary contact page

- services/apps/portal/src/application/application-owner/application-owner.entity.ts
- services/apps/portal/src/application/application-owner/application-owner.service.spec.ts
- services/apps/portal/src/application/application-owner/application-owner.service.ts
- services/apps/portal/src/application/application-parcel/application-parcel.service.spec.ts
- services/apps/portal/src/application/application-parcel/application-parcel.service.ts
* Set applicant name on application using the first alphabetical owner of the first parcel
* Needs to trigger when parcel is deleted, owner is updated/linked/deleted to parcel
> Set applicant name on application

- services/apps/portal/src/application/application-owner/application-owner.service.spec.ts
- services/apps/portal/src/application/application-owner/application-owner.service.ts
- services/apps/portal/src/application/application.service.ts
> Add et al to applicant name if there is more than one owner

- portal-frontend/src/app/features/edit-application/parcel-details/application-owners-dialog/application-owners-dialog.component.ts
- portal-frontend/src/app/features/edit-application/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/edit-application/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.scss
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.ts
* Do not show agent owners after editing in all owners dialog
* Prevent duplicate saving, was happening on both button click and onDestroy
* Properly set ownerUuid so component doesn't keep creating new owners
> Add file error message + bug fixes

- portal-frontend/src/app/features/edit-application/select-government/select-government.component.ts
* Add log statement to confirm the issue
* Increase timeout as a suspect
> Increase timeout and add log statement for debug

- portal-frontend/src/app/features/view-application/view-application.component.html
- portal-frontend/src/app/features/view-application/view-application.component.scss
- portal-frontend/src/app/services/application/application.dto.ts
- services/apps/portal/src/application/application.dto.ts
- services/apps/portal/src/application/application.service.spec.ts
- services/apps/portal/src/common/automapper/application.automapper.profile.ts
* Use absolute and non-absolute trick for positioning
* Add lastStatusUpdate to application dto
> Add banner to view application page

- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.html
- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.spec.ts
- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.ts
- services/apps/alcs/src/admin/local-government/local-government.controller.spec.ts
- services/apps/alcs/src/admin/local-government/local-government.dto.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.entity.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.service.spec.ts
- services/apps/alcs/src/application/application-code/application-local-government/application-local-government.service.ts
* add preferred region dropdown
* fix issue with required bceid in dto
> fix local government create dialog

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.component.scss
- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/shared/pipes/emailValid.pipe.ts
- portal-frontend/src/app/shared/pipes/phoneValid.pipe.ts
- portal-frontend/src/app/shared/shared.module.ts
- portal-frontend/src/app/shared/validation-error/validation-error.component.ts
- services/apps/portal/src/alcs/code/code.controller.spec.ts
- services/apps/portal/src/alcs/local-government/local-government.service.spec.ts
- services/apps/portal/src/alcs/local-government/local-government.service.ts
- services/apps/portal/src/application-review/application-review.controller.spec.ts
- services/apps/portal/src/application-review/application-review.controller.ts
- services/apps/portal/src/application-review/application-review.service.spec.ts
- services/apps/portal/src/application/application-validator.service.spec.ts
- services/apps/portal/src/application/application-validator.service.ts
- services/apps/portal/src/application/application.controller.spec.ts
- services/apps/portal/src/application/application.controller.ts
- services/apps/portal/src/application/application.module.ts
- services/apps/portal/src/application/application.service.spec.ts
- services/apps/portal/src/application/application.service.ts
* UI Improvements to Frontend
* Add new validator service and unit tests
* Add invalid format errors to front end
> Add Application backend validation + UI Improvements

- portal-frontend/src/app/app.module.ts
- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.component.ts
- portal-frontend/src/app/features/application-details/nfu-details/nfu-details.component.html
- portal-frontend/src/app/features/application-details/nfu-details/nfu-details.component.ts
- portal-frontend/src/app/features/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/edit-application/review-and-submit/review-and-submit.component.html
- portal-frontend/src/app/features/edit-application/review-and-submit/review-and-submit.component.spec.ts
- portal-frontend/src/app/features/edit-application/review-and-submit/review-and-submit.component.ts
- portal-frontend/src/app/features/view-application/view-application.component.html
- portal-frontend/src/app/features/view-application/view-application.component.scss
- portal-frontend/src/app/features/view-application/view-application.component.ts
* Add ability to hide errors and edit buttons
> Show application details component on view application page

- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/edit-application/select-government/select-government.component.html
- portal-frontend/src/app/features/edit-application/select-government/select-government.component.ts
* ALCS-452 - Add error message for missing owners on Parcel entry
* ALCS-453 - Make government red when it is not valid
> Add new error messages for Applicants

- portal-frontend/src/app/features/edit-application/edit-application.module.ts
- portal-frontend/src/app/features/edit-application/other-parcels/other-parcels.component.html
- portal-frontend/src/app/features/edit-application/other-parcels/other-parcels.component.scss
- portal-frontend/src/app/features/edit-application/other-parcels/other-parcels.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/application-crown-owner-dialog/application-crown-owner-dialog.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/application-crown-owner-dialog/application-crown-owner-dialog.component.scss
- portal-frontend/src/app/features/edit-application/parcel-details/application-crown-owner-dialog/application-crown-owner-dialog.component.spec.ts
- portal-frontend/src/app/features/edit-application/parcel-details/application-crown-owner-dialog/application-crown-owner-dialog.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.scss
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-owners/parcel-owners.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-owners/parcel-owners.component.ts
- portal-frontend/src/app/services/application-owner/application-owner.dto.ts
- portal-frontend/src/app/services/application-owner/application-owner.service.ts
- portal-frontend/src/app/services/application-parcel/application-parcel.dto.ts
- services/apps/portal/src/application/application-parcel/application-parcel.dto.ts
- services/apps/portal/src/application/application-parcel/application-parcel.entity.ts
- services/apps/portal/src/application/application-parcel/application-parcel.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1677866906022-add_crown_owner.ts
- services/apps/portal/src/providers/typeorm/migrations/1677867792844-add_crown_type_to_parcel.ts
* Add new owner type CRWN
* Filter / change the inputs based on whether its crown land or not
* Add new create/edit crown land owner dialog
> Update Parcel Entry Owners for Crown Land

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.component.scss
- portal-frontend/src/app/features/application-details/application-details.component.ts
- portal-frontend/src/app/features/application-details/nfu-details/nfu-details.component.ts
- portal-frontend/src/app/features/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
* Fix columns being wrong for land use
* Hide purchase date error if showErrors is false
* Remove mat-hint in favor of placeholder to solve layout issues
* Show errors when navigating from 8.6 to Step 6
> Bug fixes for Application Steps

- portal-frontend/src/app/features/application-details/application-details.component.html
* show local government warning on step 8
> fix local government warning on step 8

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/application-details/parcel/parcel.component.scss
- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
- services/apps/portal/src/application/application-owner/application-owner.dto.ts
- services/apps/portal/src/application/application-validator.service.spec.ts
- services/apps/portal/src/application/application-validator.service.ts
* also reset search by when switching from Crown Land -> Simple
> Make pin optional and update Step 8 for Crown Land

- portal-frontend/src/app/features/application-details/application-details.module.ts
- portal-frontend/src/app/features/application-details/parcel/parcel.component.html
* Show error if pid is not correct length
* Add ngxMask for formatting
> Show validation error and format PID

- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.ts
* Add dynamic placeholder for searchBy field
* Disable adding more owners for government parcels after the first one is added
> Crown Fixes

- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- services/apps/alcs/src/application-grpc/alcs-application.controller.spec.ts
- services/apps/alcs/src/application-grpc/alcs-application.controller.ts
- services/apps/alcs/src/application-grpc/application-grpc.module.ts
- services/apps/portal/src/application-review/application-review.controller.spec.ts
- services/apps/portal/src/application-review/application-review.controller.ts
- services/apps/portal/src/application/application.service.spec.ts
- services/apps/portal/src/application/application.service.ts
* If app is not authorized disable menu items and show tooltip
> Submit Refused to Forward Application to ALCS

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.module.ts
- portal-frontend/src/app/features/application-details/tur-details/tur-details.component.html
- portal-frontend/src/app/features/application-details/tur-details/tur-details.component.spec.ts
- portal-frontend/src/app/features/application-details/tur-details/tur-details.component.ts
- portal-frontend/src/app/features/edit-application/edit-application.component.html
- portal-frontend/src/app/features/edit-application/edit-application.component.ts
- portal-frontend/src/app/features/edit-application/edit-application.module.ts
- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.ts
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.html
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.scss
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.spec.ts
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.ts
- portal-frontend/src/app/features/view-application/view-application.component.ts
- portal-frontend/src/app/services/application-document/application-document.dto.ts
- portal-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/shared/custom-stepper/custom-stepper.component.spec.ts
- services/apps/alcs/src/application/application-document/application-document.entity.ts
- services/apps/portal/src/application/application-document/application-document.entity.ts
- services/apps/portal/src/application/application-validator.service.spec.ts
- services/apps/portal/src/application/application-validator.service.ts
- services/apps/portal/src/application/application.dto.ts
- services/apps/portal/src/application/application.entity.ts
- services/apps/portal/src/application/application.service.ts
- services/apps/portal/src/providers/typeorm/migrations/1678404866307-add_tur_fields.ts
* Control components based on app type
* Update validation, proposal step, and view Step
> Add TUR Fields and Logic to Portal

- portal-frontend/src/app/services/authentication/authentication.service.ts
* Get fresh tokens upon loading from storage and validating to ensure they will remain valid for the next refresh 4 minutes after
> Refresh tokens after successfully loading from storage

- services/apps/alcs/src/common/authorization/authorization.service.ts
- services/apps/alcs/src/document/document.service.ts
- services/apps/alcs/src/logout/logout.controller.ts
- services/apps/alcs/src/providers/keycloak/keycloak-config.service.ts
- services/apps/portal/src/common/authorization/authorization.controller.ts
- services/apps/portal/src/common/authorization/authorization.service.ts
- services/apps/portal/src/logout/logout.controller.ts
- services/apps/portal/src/providers/keycloak/keycloak-config.service.ts
- services/config/default.json
* Change portal to ask for bceid by default
> Update Apps to use Single Keycloak

- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.html
- portal-frontend/src/app/features/home/home.component.html
- portal-frontend/src/app/features/home/home.component.scss
* open links in a new tab
* align create button text
> fix links and create button

- alcs-frontend/src/app/services/authentication/authentication.service.ts
- portal-frontend/src/app/services/authentication/authentication.service.ts
- services/apps/alcs/src/common/authorization/authorization.controller.ts
- services/apps/alcs/src/common/authorization/authorization.filter.ts
- services/apps/alcs/src/logout/logout.controller.ts
* Store session id with source and redirect to correct system lon login
* Add param to logout to specify target system
> Update login / logout to differentiate systems

- portal-frontend/src/app/features/edit-application/edit-application.component.html
- portal-frontend/src/app/features/edit-application/other-attachments/other-attachments.component.ts
- portal-frontend/src/app/features/edit-application/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.ts
- services/apps/alcs/src/common/automapper/application-owner.automapper.profile.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts
Fix file uploading / reloading on several pages
> Portal Fixes

- portal-frontend/src/app/features/edit-application/change-application-type-dialog/change-application-type-dialog.component.scss
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
> Fix update to return mapped app

- services/apps/alcs/src/alcs/application/application-document/application-document.service.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel-document/application-parcel-document.controller.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel-document/application-parcel-document.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel-document/application-parcel-document.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Add deletion of AppParcelDocument, similar to how AppDocuments are deleted
* Rename some Applications -> ApplicationSubmission
> Delete Parcel Documents

- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/providers/typeorm/orm.config.ts
Fix status changing to re-load the entity to prevent lots of things from being saved
> Renames + Bug Fix

- alcs-frontend/src/app/shared/application-document/application-document.component.ts
* Use onChanges which will run once when all inputs change
> Fix loading of documents before document type is set

- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/intake/intake.component.scss
- alcs-frontend/src/app/features/application/intake/intake.component.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/shared/inline-boolean/inline-boolean.component.html
- alcs-frontend/src/app/shared/inline-boolean/inline-boolean.component.scss
- alcs-frontend/src/app/shared/inline-boolean/inline-boolean.component.spec.ts
- alcs-frontend/src/app/shared/inline-boolean/inline-boolean.component.ts
- alcs-frontend/src/app/shared/inline-number/inline-number.component.html
- alcs-frontend/src/app/shared/inline-number/inline-number.component.scss
- alcs-frontend/src/app/shared/inline-number/inline-number.component.spec.ts
- alcs-frontend/src/app/shared/inline-number/inline-number.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- services/apps/alcs/src/alcs/application/application.controller.ts
- services/apps/alcs/src/alcs/application/application.dto.ts
- services/apps/alcs/src/alcs/application/application.entity.ts
- services/apps/alcs/src/alcs/import/import.service.ts
- services/apps/alcs/src/common/automapper/application.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1679950423581-add_app_payments.ts
* Add inline boolean and number inputs
* Add new fields to app entity for new data
> Add new intake page fields

- alcs-frontend/src/app/services/application/application-document/application-document.service.ts
- portal-frontend/src/app/features/review-application/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/services/application-document/application-document.dto.ts
- portal-frontend/src/app/services/application-document/application-document.service.ts
- portal-frontend/src/app/services/application-owner/application-owner.service.ts
- portal-frontend/src/app/services/application-parcel/application-parcel.service.ts
- portal-frontend/src/app/services/document/document.service.ts
- services/apps/alcs/src/document/document.dto.ts
- services/apps/alcs/src/document/document.service.spec.ts
- services/apps/alcs/src/providers/typeorm/migrations/1680280060590-rename_lg_source.ts
* Also use enums in moreplaces
> Re-name Local Government to L/FNG

- alcs-frontend/src/app/features/application/review/review.component.html
- alcs-frontend/src/app/features/commissioner/commissioner.component.html
- alcs-frontend/src/app/services/application/application-document/application-document.service.spec.ts
- alcs-frontend/src/app/services/application/application-document/application-document.service.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.entity.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.spec.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.ts
Evidentiary record now shows records with C visibility flag
> Update Evidentiary Record to use VIsibility Flags

- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/features/admin/ceo-criterion/ceo-criterion-dialog/ceo-criterion-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-dialog/decision-dialog.component.html
- portal-frontend/src/app/features/edit-application/edit-application.module.ts
- portal-frontend/src/app/features/edit-application/nfu/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/edit-application/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-application/tur/tur-proposal/tur-proposal.component.html
Set number inputs to use ngxMask for better compatability with Safari
> Change from number to using mask

- portal-frontend/src/app/features/application-details/application-details.component.ts
- portal-frontend/src/app/features/edit-application/primary-contact/primary-contact.component.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
* Update logic to only NOT require the letter if theres a single owner and they are individual
> Require authorization letter if only owner is organization

- alcs-frontend/src/app/features/application/documents/documents.component.ts
- alcs-frontend/src/app/services/application/application-document/application-document.service.ts
- portal-frontend/src/app/services/application-document/application-document.dto.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.ts
- services/apps/alcs/src/document/document.dto.ts
- services/apps/alcs/src/document/document.entity.ts
- services/apps/alcs/src/document/document.service.spec.ts
- services/apps/alcs/src/document/document.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1680551989646-rename_alcs_source.ts
* Remove document type restriction
* Re-load documents on upload
* Rename ALCS -> ALC
> Document Bug Fixes

- alcs-frontend/src/app/features/application/application-meeting/application-meeting.component.html
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/info-requests/info-requests.component.html
- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.html
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.scss
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.ts
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/application/review/review.component.html
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.html
- alcs-frontend/src/app/shared/inline-datepicker/inline-datepicker.component.ts
- services/apps/alcs/src/alcs/application/application.controller.ts
- services/apps/alcs/src/alcs/application/application.dto.ts
- services/apps/alcs/src/alcs/application/application.entity.ts
- services/apps/alcs/src/common/automapper/application.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1680560734288-add_proposal_nfu_fields.ts
* Change inline-datepicker to use value same as other inline pickers
> Add NFU Proposal Fields

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.module.ts
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.html
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.scss
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.spec.ts
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.ts
- portal-frontend/src/app/features/edit-application/proposal/subd-proposal/subd-proposal.component.ts
* Add new subd details component
* Add to view application component
> Add Subdivision View

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.module.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/subd-details/subd-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/subd-details/subd-details.component.scss
- alcs-frontend/src/app/features/application/applicant-info/application-details/subd-details/subd-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/subd-details/subd-details.component.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/documents/documents.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.ts
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/application/proposal/subd/sub.dcomponent.scss
- alcs-frontend/src/app/features/application/proposal/subd/subd.component.html
- alcs-frontend/src/app/features/application/proposal/subd/subd.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/subd/subd.component.ts
- alcs-frontend/src/app/features/application/staff-journal/staff-journal-note-input/staff-journal-note-input.component.spec.ts
- alcs-frontend/src/app/features/application/staff-journal/staff-journal.component.spec.ts
- alcs-frontend/src/app/services/application/application-submission/application-submission.service.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.html
- services/apps/alcs/src/alcs/application/application.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
* Add to applicant info page
* Add to app prep page
> More Subdivision Features

- bin/migrate-files/README.md
- bin/migrate-oats-data/README.md
- bin/migrate-oats-data/applications.py
* update/tidy readme
* fixes to migrations
> ETL readme tidy, scripts tweaking

- alcs-frontend/src/app/features/application/review/review.component.html
- alcs-frontend/src/app/features/commissioner/commissioner.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
- bcgovpubcode.yml
Title was rendering as both input and HTML attribute
> Rename title to tableTitle

- alcs-frontend/src/app/app-routing.module.ts
Fixes issues when navigating to lazy loaded routes that may not exist yet, may have performance impacts
> Enable PreLoad Modules Flag

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.component.ts
- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/edit-submission/other-attachments/other-attachments.component.ts
- portal-frontend/src/app/features/edit-submission/parcel-details/application-owners-dialog/application-owners-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.html
- portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Change setPrimary contact to use UUID instead of File Number
* Fix links on review page to stay in ALCS edit mode
* Hide submit button for drafts
> Fixes for Edit Submissions

- portal-frontend/package-lock.json
- portal-frontend/package.json
- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.component.html
- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.component.spec.ts
- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.component.ts
- portal-frontend/src/app/features/application-details/nfu-details/nfu-details.component.html
- portal-frontend/src/app/features/application-details/nfu-details/nfu-details.component.ts
- portal-frontend/src/app/features/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.html
- portal-frontend/src/app/features/application-details/subd-details/subd-details.component.ts
- portal-frontend/src/app/features/application-details/tur-details/tur-details.component.html
- portal-frontend/src/app/features/application-details/tur-details/tur-details.component.ts
- portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.html
- portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.ts
- portal-frontend/src/app/shared/shared.module.ts
- portal-frontend/src/app/shared/updated-banner/updated-banner.component.html
- portal-frontend/src/app/shared/updated-banner/updated-banner.component.scss
- portal-frontend/src/app/shared/updated-banner/updated-banner.component.spec.ts
- portal-frontend/src/app/shared/updated-banner/updated-banner.component.ts
* Diff Old and new Submission and store diffs into array
* Look into Array to see if form fields have changed and render accordingly
* Update Parcels to have similar logic
> Add Updated Banner

- portal-frontend/src/app/features/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/view-submission/view-submission.component.html
- portal-frontend/src/app/features/view-submission/view-submission.component.ts
* Only show Download PDF if there is a review
> Clear Review when loading next Submission

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.scss
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.ts
- Fix modal width
- Fix modal height to app type modal
- Did not fix modal height in submission type modal because modal has less fluctuation compared to app type modal, and the increased gap felt more confusing instead
- Route successful application creation to form directly
- Apply responsive styling to modal (tested with 400% zoom and mobile)
- Use angular material `mat-dialog-action` attribute to fix action button to the bottom of the modal
> Update create new app modal UX and UI

- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.html
- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/features/application/documents/documents.component.html
- alcs-frontend/src/app/features/application/documents/documents.component.ts
- alcs-frontend/src/app/services/application/application-document/application-document.dto.ts
- alcs-frontend/src/app/services/application/application-document/application-document.service.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
- portal-frontend/src/app/features/application-details/application-details.component.html
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.dto.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.ts
- services/apps/alcs/src/alcs/decision/application-decision/application-decision.service.ts
- services/apps/alcs/src/common/automapper/application.automapper.profile.ts
- services/apps/alcs/src/document/document.dto.ts
- services/apps/alcs/src/document/document.entity.ts
- services/apps/alcs/src/document/document.service.spec.ts
- services/apps/alcs/src/document/document.service.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.spec.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/pdf-generation/generate-review-document.service.ts
- services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1682357986234-add_document_system.ts
* Track which "system" the documents were uploaded in
* Only allow removal / deletion of documents that are from ALCS
* Merge Visibility flags in front end
> Add system for Documents

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/nfu-details/nfu-details.component.html
- alcs-frontend/src/app/services/application/application.dto.ts
Now a full boolean since its no longer JSON
Also fix step numbers for edit buttons
> Change nfuWillImportFill to correct type

- portal-frontend/src/app/features/review-submission/review-submission.component.html
- portal-frontend/src/app/features/review-submission/review-submission.component.scss
- portal-frontend/src/app/features/review-submission/review-submission.component.spec.ts
- portal-frontend/src/app/features/review-submission/review-submission.component.ts
- portal-frontend/src/app/features/review-submission/review-submit-fng/review-submit-fng.component.html
- portal-frontend/src/app/features/review-submission/review-submit-fng/review-submit-fng.component.spec.ts
- portal-frontend/src/app/features/review-submission/review-submit-fng/review-submit-fng.component.ts
- portal-frontend/src/app/features/review-submission/review-submit/review-submit.component.html
- portal-frontend/src/app/features/review-submission/review-submit/review-submit.component.spec.ts
- portal-frontend/src/app/features/review-submission/review-submit/review-submit.component.ts
- services/apps/alcs/src/portal/pdf-generation/generate-review-document.service.ts
- services/libs/common/src/cdogs/cdogs.service.ts
* Add PDF download buttons to submit page for FNG and LG review
* Supply generated time so it shows properly in PDF
> Bug fixes for L/FNG Submission PDF

- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.module.ts
- portal-frontend/src/app/features/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.html
- portal-frontend/src/app/features/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.scss
- portal-frontend/src/app/features/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.spec.ts
- portal-frontend/src/app/features/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.html
* Change button text to Update Submission
> Add new publish confirmation dialog

- portal-frontend/src/app/features/view-submission/alc-review/alc-review.component.html
- portal-frontend/src/app/features/view-submission/alc-review/alc-review.component.scss
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.scss
- portal-frontend/src/app/features/view-submission/view-submission.component.html
* Remove action buttons from FNG/ALC tabs
* Remove Download PDF from ALC until its implemented
* Fix warning banners
> Fixes for View Submission Sections

- portal-frontend/src/styles/colors.scss
- portal-frontend/src/styles/form-controls.scss
- Bugfix on disabled dropdown placeholder text to match the rest of input fields
- Improve disabled fields to make them more disabled: cursor behaviour and background color
> Improve disabled fields UI

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.scss
- portal-frontend/src/app/features/application-details/application-details.component.scss
- portal-frontend/src/app/features/edit-submission/other-attachments/other-attachments.component.html
- portal-frontend/src/app/features/edit-submission/other-attachments/other-attachments.component.scss
- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-owners/parcel-owners.component.scss
- portal-frontend/src/app/shared/file-drag-drop/drag-drop.directive.ts
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.scss
- Update responsive styling for uploaded file to account for long file name
- Update upload area UI and interaction
- Add placeholder for optional document table if nothing is uploaded
- Use same styling across portal for no data table texts
> Portal document upload area and optional doc table

- services/apps/alcs/src/alcs/commissioner/commissioner.dto.ts
* This will hide active/inactive days in their header if its set
> Map decision date for Comissioners

- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.scss
> Add disabled styling for file upload

- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/other-parcels/other-parcels.component.html
- portal-frontend/src/app/features/edit-submission/other-parcels/other-parcels.component.ts
- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/review-submission/review-submission.component.ts
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.scss
- portal-frontend/src/app/shared/utils/scroll-helper.ts
- portal-frontend/src/styles/form-controls.scss
- portal-frontend/src/styles/toast.scss
- Fix toast overlay from blocking other elements
- Add scroll behaviour to Create New + Change App Type modals
- Changes to parcel owner dropdown if owner is added already
- Collapse panel if no other parcels in application
> Portal interaction and scroll fixes

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.scss
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.html
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.scss
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.scss
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
In addition to UI changes, this also includes an UX update which disables user from updating app type to the same one as the current submission's app type
> Update Change App Type modal to match Create New modal

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision.module.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- services/apps/alcs/src/alcs/decision/application-decision.entity.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision.dto.ts
- services/apps/alcs/src/providers/typeorm/migrations/1684534105899-add_was_released_to_decisions.ts
* Add DB flag to track if a decision was previously released
* Add new dialog for reverting to draft
* Change release dialog if a decision was previously released
> Add Revert to Draft and Re-release

- portal-frontend/src/app/features/view-submission/alc-review/decisions/decisions.component.html
* Should append Subject to Conditions not replace the label
> Fixup Portal Decision Outcome

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/services/application/decision/application-decision-v1/application-decision.dto.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.service.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- services/apps/alcs/src/alcs/decision/application-decision.entity.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision-v2.controller.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision-v2.service.spec.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision.dto.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/linked-resolution-outcome-type.entity.ts
- services/apps/alcs/src/alcs/decision/decision-v2/decision-v2.module.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1684450272364-decv2_tweaks.ts
- services/apps/alcs/src/providers/typeorm/migrations/1684450417394-seed_dec_outcomes.ts
* Add new linked resolution outcome field
* Use new field and decision outcome to conditionally render other fields
* Improve validation to require a component in certain situations
> Add Linked Resolution Outcome to Decisions

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- services/apps/alcs/src/providers/typeorm/migrations/1684862304558-add_rescinded_to_decisions.ts
* Only enable rescinded and rescinded comment if decision was rescinded
* Require these fields if decision is rescinded
> Add rescinded decision outcome and form logic

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-components.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-components.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- services/apps/alcs/src/alcs/decision/decision-condition/decision-condition.service.spec.ts
- services/apps/alcs/src/alcs/decision/decision-condition/decision-condition.service.ts
- services/apps/alcs/src/alcs/decision/decision-v2/application-decision/application-decision-v2.service.ts
* Update components to return validation to their parent which can be used to control the Release Decision button
* Fix an issue where new conditions linked to new components were not saving
> Add validation to conditions and components

- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.ts
- portal-frontend/src/app/features/view-submission/view-submission.component.html
- portal-frontend/src/app/features/view-submission/view-submission.component.ts
> added cancel application

- alcs-frontend/src/app/features/admin/admin.component.ts
- alcs-frontend/src/app/features/admin/admin.module.ts
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype-dialog/noi-subtype-dialog.component.html
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype-dialog/noi-subtype-dialog.component.scss
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype-dialog/noi-subtype-dialog.component.spec.ts
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype-dialog/noi-subtype-dialog.component.ts
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype.component.html
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype.component.scss
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype.component.spec.ts
- alcs-frontend/src/app/features/admin/noi-subtype/noi-subtype.component.ts
- alcs-frontend/src/app/services/noi-subtype/noi-subtype.service.spec.ts
- alcs-frontend/src/app/services/noi-subtype/noi-subtype.service.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/alcs/admin/admin.module.ts
- services/apps/alcs/src/alcs/admin/ceo-criterion/ceo-criterion.controller.spec.ts
- services/apps/alcs/src/alcs/admin/ceo-criterion/ceo-criterion.controller.ts
- services/apps/alcs/src/alcs/admin/noi-subtype/noi-subtype.controller.spec.ts
- services/apps/alcs/src/alcs/admin/noi-subtype/noi-subtype.controller.ts
- services/apps/alcs/src/alcs/admin/noi-subtype/noi-subtype.service.spec.ts
- services/apps/alcs/src/alcs/admin/noi-subtype/noi-subtype.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-subtype.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1685573138652-add_noi_subtype_active.ts
* Add active flag to enable/disable
* Add Admin controller and services to back
* Add page to admin
> Add NOI Subtypes to Admin

- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/preparation/preparation.component.html
- alcs-frontend/src/app/features/notice-of-intent/preparation/preparation.component.scss
- services/apps/alcs/src/alcs/board/board.controller.spec.ts
- services/apps/alcs/src/alcs/board/board.controller.ts
- services/apps/alcs/src/alcs/board/board.entity.ts
- services/apps/alcs/src/alcs/card/card-type/card-type.entity.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.service.spec.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1685747376721-fix_noi_board.ts
* Genericize how cards are loaded
* Change columns in NOI Board
> More Bug Fixes

- alcs-frontend/src/app/features/application/decision/decision-v1/decision-v1.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-dialog/decision-dialog.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-dialog/decision-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision.component.ts
- alcs-frontend/src/app/features/notice-of-intent/overview/overview.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/overview/overview.component.ts
- alcs-frontend/src/app/services/notice-of-intent/decision/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-outcome.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.service.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1686166177818-remove_noi_outcome_first_decision.ts
* Also remove isFirstDecision and Proceeded over 60 days outcome
> Linking of Decisions to Modifications

- services/apps/alcs/src/alcs/application/application-meeting/application-meeting.entity.ts
- services/apps/alcs/src/alcs/application/application-meeting/application-meeting.service.spec.ts
- services/apps/alcs/src/alcs/application/application-meeting/application-meeting.service.ts
* Setting to null was not actually deleting the pause entity
> Delete app pause directly when report start and end date are null

- alcs-frontend/src/app/features/provision/provision.component.html
- alcs-frontend/src/app/features/provision/provision.component.scss
- alcs-frontend/src/app/features/provision/provision.component.ts
- services/apps/alcs/src/logout/logout.controller.spec.ts
- services/apps/alcs/src/logout/logout.controller.ts
- services/config/default.json
- services/config/test.json
* Add Log Out button to Provision Page
> Log user out of Siteminder at same time as Keycloak

- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/decision/decision.module.ts
- alcs-frontend/src/app/features/application/post-decision/edit-modification-dialog/edit-modification-dialog.component.html
- alcs-frontend/src/app/features/application/post-decision/edit-modification-dialog/edit-modification-dialog.component.ts
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.html
- alcs-frontend/src/app/shared/header/notifications/notifications.component.html
- alcs-frontend/src/app/shared/header/notifications/notifications.component.scss
- services/apps/alcs/src/providers/typeorm/migrations/1686340435992-add_doc_type.ts
* New UI for notifications
* Add new doc type
* Change Soil Board column order
* Add outcome notification date to modifications dialog
> Various Improvements

- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/application/proposal/proposal.component.scss
- alcs-frontend/src/app/features/application/proposal/proposal.component.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- services/apps/alcs/src/alcs/application/application.controller.ts
- services/apps/alcs/src/alcs/application/application.dto.ts
- services/apps/alcs/src/alcs/application/application.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1686351221810-add_staff_observations.ts
* Add column to store, update dto, and exposed on front end
> Add Staff Observations

- services/apps/alcs/src/alcs/import/application-import.service.spec.ts
- services/apps/alcs/src/alcs/import/application-import.service.ts
- services/apps/alcs/src/alcs/import/import.module.ts
- services/apps/alcs/src/alcs/import/noi-import.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.module.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.module.ts
- services/apps/alcs/src/commands/import.ts
- services/apps/alcs/src/main.ts
> Add NOI Import Service

- alcs-frontend/src/app/features/board/board.component.ts
* Change vetting board to put NOIs first, Applications second, and the rest third
> Change Vetting Board Sorting

- portal-frontend/src/app/features/application-details/application-details.component.html
* added banner to Primary contact in draft mode
> add banner to primary contact

- portal-frontend/src/app/features/edit-submission/edit-submission-base.module.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/change-subtype-confirmation-dialog/change-subtype-confirmation-dialog.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/change-subtype-confirmation-dialog/change-subtype-confirmation-dialog.component.scss
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/change-subtype-confirmation-dialog/change-subtype-confirmation-dialog.component.spec.ts
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/change-subtype-confirmation-dialog/change-subtype-confirmation-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.scss
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.spec.ts
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.ts
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1686766958056-add_naru_subtype.ts
* Only single subtype selector for now
> Add Naru Proposal

- alcs-frontend/src/app/features/application/decision/decision-v1/decision-v1-dialog/decision-v1-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-dialog/decision-dialog.component.html
> rename 'new' -> 'create'

- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision.component.ts
- alcs-frontend/src/app/shared/application-type-pill/application-type-pill.component.scss
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.html
- alcs-frontend/src/app/shared/details-header/details-header.component.ts
- alcs-frontend/src/app/shared/time-tracker/time-tracker.component.html
- alcs-frontend/src/app/shared/time-tracker/time-tracker.component.scss
- alcs-frontend/src/app/shared/time-tracker/time-tracker.component.ts
* Update time tracker and NOI Cards with new time tracking requirements around showing Due Date and overdue cards
* Small styling changes for all cards
> NOI Time Tracking

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.module.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.scss
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.ts
- alcs-frontend/src/app/services/application/application-submission/application-submission.service.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/application-details/application-details.component.html
- services/apps/alcs/src/alcs/application/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.service.ts
- services/apps/alcs/src/alcs/application/application.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Small cleanup on submission service relations
> NARU Validation and Showing in ALCS

- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.html
* Also DRY up repeated questions a bit more
> NARU Residence Step 8 + ALCS

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/pfrs/pfrs.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/pofo/pofo.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/turp-input/turp-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-components.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- services/apps/alcs/src/alcs/application-decision/application-modification/application-modification.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-modification/application-modification.service.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.service.ts
- services/apps/alcs/src/alcs/application/application.service.spec.ts
- services/apps/alcs/src/alcs/application/application.service.ts
- services/apps/alcs/src/alcs/covenant/covenant.service.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-modification/notice-of-intent-modification.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-modification/notice-of-intent-modification.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.service.ts
* decision UI fixes
* home page performance fixes
> decision ui changes and performance fixes for home page

- portal-frontend/src/app/features/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.ts
* Change logic to show No Data Flags instead of hiding them
* willimportFill was actually undefined despite being set to null, so check for that
* Only save if form is dirty
> Bug Fixes for NARU

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- alcs-frontend/src/app/services/application/application-submission/application-submission.service.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.ts
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- services/apps/alcs/src/alcs/application/application.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1687371977194-add_naru_tourism_fields.ts
* Also bug fixes for existing versions
> Naru Tourism Step 8 + ALCS

- alcs-frontend/src/app/shared/time-tracker/time-tracker.component.html
- alcs-frontend/src/app/shared/time-tracker/time-tracker.component.ts
* Change time tracker calculation to match the card
* Hide due date when active days are not being tracked
> Noi Tracking Fixes

- alcs-frontend/src/app/features/application/decision/decision-v1/decision-v1-dialog/decision-v1-dialog.component.ts
- fix decision creation with reconsideration
> fix condition

- alcs-frontend/src/app/features/application/proposal/subd/sub.dcomponent.scss
- portal-frontend/src/app/features/edit-submission/proposal/subd-proposal/subd-proposal.component.html
* Portal Subdivision Proposal Homesite Severance - set required doc upload UI to match disabled flag
* ALCS app prep page remove mini scrollbar due to overflow css
> Subdivision portal proposal and ALCS app prep fix

- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.ts
- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.html
- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/services/application/application-document/application-document.dto.ts
- alcs-frontend/src/app/services/application/application-document/application-document.service.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/application-details/application-details.component.html
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.controller.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.ts
- services/apps/alcs/src/portal/application-submission-draft/application-submission-draft.service.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.dto.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts
- services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.spec.ts
* Clean up logic in controller
* Fix warning banner preventing edit submission submit
* Load naru subtype in edit submission to enable editing of NARU
> Add Owner Dropdown for Corporate Summary

- services/apps/alcs/src/providers/typeorm/migrations/1687557623816-local_gov_name_edits.ts
git has been fixed and hopefully the bug too
> bugfix to use uuid instead of name go brrr

- services/apps/alcs/src/alcs/application/application-document/application-document.controller.ts
> Maintain extension when adding superseded

- alcs-frontend/src/app/features/application/applicant-info/applicant-info.component.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.scss
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.ts
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/services/application/application-parcel/application-parcel.service.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- services/apps/alcs/src/alcs/application/application-parcel/application-parcel.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-parcel/application-parcel.controller.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.dto.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.entity.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1688078238188-add_parcel_alr_area.ts
* Add editable ALR Area
* Add new column for it
* Add new component with table for display
> Add Parcel Prep Table to App Prep

- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.ts
- Delete empty agents before creating new one
- Update backend unit test
- Fix step 3 authorization letter validation bug if user switches from 3rd party agent to owner post step 8.
> Fix empty agents creation/deletion and auth letter validation

- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
Also update form validation to show all error messages when navigated from step 8
> Show toggle button validation on parcel search

- alcs-frontend/src/app/features/application/decision/conditions/conditions.component.ts
fix decision component labels on conditions
> fix labels

- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.html
- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.scss
- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/turp-input/turp-input.component.spec.ts
- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.spec.ts
- alcs-frontend/src/app/features/application/proposal/proposal.component.spec.ts
- alcs-frontend/src/app/features/board/board.component.spec.ts
- alcs-frontend/src/app/services/admin-board-management/admin-board-management.service.spec.ts
- alcs-frontend/src/app/services/admin-board-management/admin-board-management.service.ts
- alcs-frontend/src/app/services/board/board.dto.ts
- alcs-frontend/src/app/shared/header/notifications/notifications.component.spec.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.spec.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- services/apps/alcs/src/alcs/board/board.dto.ts
- services/apps/alcs/src/alcs/board/board.entity.ts
- services/apps/alcs/src/alcs/board/board.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1689182264768-add_schedule_flag_to_boards.ts
- services/apps/alcs/src/providers/typeorm/migrations/1689182339001-seed_schedule_flags.ts
> Add ability to show/hide boards from the Schedule page

- services/apps/alcs/src/alcs/application/application-code/application-local-government/application-local-government.service.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.entity.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1689198488363-track_submission_review_created_by.ts
* Use new createdBy user to identify whether the review was done by a LG or FNG
> Store creating User on Submission Review

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/naru/naru.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/nfup/nfup.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/pfrs/pfrs.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/pofo/pofo.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/roso/roso.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/turp/turp.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/application/decision/decision.module.ts
- Move Ag Cap Map and Consultant fields to separate component
- Add to all app type components and style accordingly
> Update decision component field layouts

- alcs-frontend/src/app/features/board/dialogs/notice-of-intent/create/create-notice-of-intent-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/planning-review/create/create-planning-review-dialog.component.ts
- alcs-frontend/src/app/services/planning-review/planning-review.dto.ts
- alcs-frontend/src/app/services/planning-review/planning-review.service.spec.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.controller.spec.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.controller.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.dto.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.service.spec.ts
- services/apps/alcs/test/pgtap/test_calculate_paused_time.sql
* Can now create on any board instead of defaulting to Executive Committee
> Add boardCode to create planning review

- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.ts
* Change logic to not require ocp / zoning for FNG reviews and show completed fields
> Show fields for completed FNG reviews

- alcs-frontend/src/app/features/application/overview/overview.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v1/application-decision/application-decision.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision.entity.ts
- services/apps/alcs/src/alcs/application/application.service.spec.ts
- services/apps/alcs/src/alcs/application/application.service.ts
- services/apps/alcs/src/common/automapper/application-decision-v1.automapper.profile.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1689359038811-make_dec_date_nullable.ts
- services/apps/alcs/test/mocks/mockEntities.ts
* Don't show draft decisions in timeline
* Make it so draft decisions do not set the decision date on the app
> Make date optional on decision

- services/apps/alcs/src/logout/logout.controller.ts
* Change to new post_logout_redirect_uri instead of logout_redirect_uri
> Update Keycloak logout params

- alcs-frontend/src/app/services/application/application-submission-status/application-submission-status.dto.ts
- alcs-frontend/src/app/services/application/application-submission-status/application-submission-status.service.spec.ts
- alcs-frontend/src/app/services/application/application-submission-status/application-submission-status.service.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.html
- services/apps/alcs/src/alcs/alcs.module.ts
- services/apps/alcs/src/application-submission-status/application-submission-status.controller.spec.ts
- services/apps/alcs/src/application-submission-status/application-submission-status.controller.ts
- services/apps/alcs/src/application-submission-status/application-submission-status.module.ts
- services/apps/alcs/src/application-submission-status/submission-status.dto.ts
- services/apps/alcs/src/common/automapper/application-submission.automapper.profile.ts
> Feature/alcs 909 - part 1 

- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/features/application/overview/uncancel-application-dialog/uncancel-application-dialog.component.html
- alcs-frontend/src/app/features/application/overview/uncancel-application-dialog/uncancel-application-dialog.component.scss
- alcs-frontend/src/app/features/application/overview/uncancel-application-dialog/uncancel-application-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/overview/uncancel-application-dialog/uncancel-application-dialog.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.scss
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- alcs-frontend/src/app/shared/warning-banner/warning-banner.component.html
- alcs-frontend/src/app/shared/warning-banner/warning-banner.component.scss
- alcs-frontend/src/app/shared/warning-banner/warning-banner.component.spec.ts
- alcs-frontend/src/app/shared/warning-banner/warning-banner.component.ts
* Add pill to revert to draft decision dialog
> Add Cancel/Uncancel Application

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
* Only need to update validity, not the actual conditions
> Don't re-populate conditions on component changes

- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.ts
- alcs-frontend/src/app/features/application/overview/overview.component.ts
- alcs-frontend/src/app/features/application/overview/uncancel-application-dialog/uncancel-application-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/overview/overview.component.ts
- alcs-frontend/src/app/services/application/application-code.dto.ts
- alcs-frontend/src/app/services/application/application-reconsideration/application-reconsideration.dto.ts
- alcs-frontend/src/app/services/application/application-submission-status/application-submission-status.dto.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/application/application.service.ts
- alcs-frontend/src/app/shared/timeline/timeline.component.html
- alcs-frontend/src/app/shared/timeline/timeline.component.ts
- services/apps/alcs/src/common/automapper/application-decision-v1.automapper.profile.ts
* Update mapping of statuses and new HTML labels
> Update Overview timeline with new statuses

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/edit-submission/edit-submission.component.spec.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.ts
- portal-frontend/src/app/features/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.html
- portal-frontend/src/app/features/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Immediately redirect to start review URL when submitting to your own LG
* When creating a review if the primary contact is Government, copy over the contact details
> Start FNLG review when submitting to yourself

- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.scss
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.scss
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.ts
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- Use `submissionStatuses` from alcs-frontend to retrieve submitted to ALC status
- Add icon to LFNG banner and match ALC styling
> Fix portal LFNG review tab and update banner

- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.html
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.ts
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- portal-frontend/src/app/services/application-submission/application-submission.service.ts
- portal-frontend/src/app/services/authentication/authentication.dto.ts
- portal-frontend/src/app/shared/presribed-body/presribed-body.component.html
- portal-frontend/src/app/shared/presribed-body/presribed-body.component.scss
- portal-frontend/src/app/shared/presribed-body/presribed-body.component.spec.ts
- portal-frontend/src/app/shared/presribed-body/presribed-body.component.ts
- portal-frontend/src/app/shared/shared.module.ts
- portal-frontend/src/styles/typography.scss
- services/apps/alcs/src/user/user.controller.spec.ts
- services/apps/alcs/src/user/user.controller.ts
- services/apps/alcs/src/user/user.dto.ts
- services/apps/alcs/src/user/user.service.ts
* Add new step to both create and change application dialogs
* Hardcode government options
* Send to frontend whether use isFirstNation or isLocalGovernment
> Add Prescribed Body step to Create & Change Dialogs

- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/services/application-document/application-document.service.ts
- portal-frontend/src/app/services/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Only redirect to LFNG review is submitting as same government
* Make department mandatory on Step 3
* Always show authorization letter errors
> Bug Fixes for L/FNG as Applicant

- portal-frontend/src/app/features/edit-submission/edit-submission-base.module.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.spec.ts
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.ts
- services/apps/alcs/src/providers/typeorm/migrations/1690225882322-change_inclusion_legislative_reference.ts
> Add Inclusion form fields to portal and update description

- portal-frontend/src/app/features/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/land-use/land-use.component.ts
- portal-frontend/src/app/features/edit-submission/other-parcels/other-parcels.component.ts
- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/excl-proposal/excl-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/nfu-proposal/nfu-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/pofo-proposal/pofo-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/roso-proposal/roso-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/subd-proposal/subd-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/tur-proposal/tur-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/select-government/select-government.component.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Only save/load the application when components are dirty
* Remove logic to auto-save on every step navigation
* Add logging to help debug stepper issues
> Reduce Network Calls / Loads for Edit Submission

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.module.ts
- portal-frontend/src/app/features/application-details/excl-details/excl-details.component.html
- portal-frontend/src/app/features/application-details/excl-details/excl-details.component.spec.ts
- portal-frontend/src/app/features/application-details/excl-details/excl-details.component.ts
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/edit-submission/proposal/excl-proposal/excl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/excl-proposal/excl-proposal.component.scss
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- Add exclusion proposal review section in step 8 with validations and update banner
- Fix backend bug that prevented empty proposal from being saved
> Add Exclusion Step 8 Review & View section

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/pfrs/pfrs.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/pofo/pofo.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/roso/roso.component.html
- hide units from table if there is no data
> no data for tables with units

- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
* Check if submission is to own users government to control copying
* Add error to step 8 when missing Department
* Fix logic in primary contact to show errors at the right time
> LFNG As applicant bug fixes

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.spec.ts
- alcs-frontend/src/app/services/application/application-submission/application-submission.service.spec.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.scss
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.spec.ts
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.ts
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1690414066995-add_government_incl_fields_to_submission.ts
* Add question to indicate parcel ownership and store in DB
* Add more file uploads if the answer is no
> Add inclusion fields when user is LFNG

- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.html
- alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.scss
- alcs-frontend/src/app/shared/inline-editors/inline-ng-select/inline-ng-select.component.html
- alcs-frontend/src/app/shared/inline-editors/inline-ng-select/inline-ng-select.component.scss
- alcs-frontend/src/app/shared/inline-editors/inline-ng-select/inline-ng-select.component.spec.ts
- alcs-frontend/src/app/shared/inline-editors/inline-ng-select/inline-ng-select.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- inline editor using ng-select in App Prep page for nfu subtype
> nfu subtype with inline ng select

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/shared/lots-table/lots-table-form.component.scss
- alcs-frontend/src/app/shared/lots-table/lots-table-form.component.ts
- portal-frontend/src/app/shared/header/header.component.html
- portal-frontend/src/app/shared/header/header.component.ts
* Bug fix for header change after checked
> Fix Styling for SUBD, Fix Decisions with no components or conditions

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
* Setting just the code will not trump the actual value so saving a changed code doe not work
> Load the full type and set it instead of just code

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.module.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/incl-details/incl-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/incl-details/incl-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/incl-details/incl-details.component.ts
- portal-frontend/src/app/features/application-details/application-details.component.html
- portal-frontend/src/app/features/application-details/application-details.module.ts
- portal-frontend/src/app/features/application-details/incl-details/incl-details.component.html
- portal-frontend/src/app/features/application-details/incl-details/incl-details.component.spec.ts
- portal-frontend/src/app/features/application-details/incl-details/incl-details.component.ts
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.html
- portal-frontend/src/app/features/create-application-dialog/create-application-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
* Add Incl/Excl to Submission Validator
* Add Incl to Portal and ALCS App Details
* Update Incl form with interface to remove ts-ignore
* Change it so Incl does not have the prescribed body select *
> Incl/Excl Features

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/incl-excl/incl-excl.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/incl-excl/incl-excl.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/incl-excl/incl-excl.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/incl-excl-input/incl-excl-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/incl-excl-input/incl-excl-input.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/incl-excl-input/incl-excl-input.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-components.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision.module.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/component/application-decision-component.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/component/application-decision-component.entity.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/component/application-decision-component.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1690580462566-add_incl_excl_component_types.ts
- services/apps/alcs/src/providers/typeorm/migrations/1690580680063-add_dec_comp_applicant_type.ts
* Add Inclusion and Exclusion Decision Components with Copy Feature
* Add new decision component column to store applicant type
> Add Incl/Excl Decision Components

- portal-frontend/src/app/features/application-details/incl-details/incl-details.component.html
- portal-frontend/src/app/features/application-details/incl-details/incl-details.component.ts
- portal-frontend/src/app/features/edit-submission/change-application-type-dialog/change-application-type-dialog.component.ts
- portal-frontend/src/app/features/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/excl-proposal/excl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.ts
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* load creating government to check rather than users as the logged in user may change
* add FIXME to Exclusion Link
* Fix back button going to prescribed body for non-exclusion apps
* Fix INCL going to Prescribed body and not just EXCL
> Various Fixes

- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.html
- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.ts
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/view-submission/lfng-review/lfng-review.component.ts
- Add no data placeholders
- Remove duplicated section after refactor
- Update fields render logic to match form
> Fix LFNG Info resolution and document sections

- portal-frontend/src/app/services/application-owner/application-owner.service.ts
- services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.spec.ts
- services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.ts
- services/apps/alcs/src/portal/pdf-generation/pdf-generation.controller.ts
* Update toasts for some reason
* Stop red toast / error returning from Submit when the PDF generation fails.
> Bug Fixes for Edit Submission

- portal-frontend/src/app/features/edit-submission/land-use/land-use.component.html
- portal-frontend/src/app/features/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/edit-submission/proposal/excl-proposal/excl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/incl-proposal/incl-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/subd-proposal/subd-proposal.component.html
- portal-frontend/src/app/features/edit-submission/proposal/tur-proposal/tur-proposal.component.html
* Update order for all proposal / input component steps.
> Re-organize Error Fields, Hints, and Character Limits

- alcs-frontend/src/app/features/admin/card-status/card-status-dialog/card-status-dialog.component.html
- alcs-frontend/src/app/features/admin/card-status/card-status-dialog/card-status-dialog.component.ts
- services/apps/alcs/src/alcs/admin/card-status/card-status.controller.spec.ts
- services/apps/alcs/src/alcs/admin/card-status/card-status.controller.ts
- services/apps/alcs/src/alcs/card/card-status/card-status.service.ts
- services/apps/alcs/src/common/automapper/board.automapper.profile.ts
* Sort columns while mapping them
* Hook up delete button and add to controller
> Sort columns and implement column delete

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/incl-excl/incl-excl.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
* Use correct field for null checks on conditions page for no data
> Adjust field alignment for  incl/excl decision components

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/styles/typography.scss
* Add subtext to all form fields so they line up
* Change some fields back to non-full width
* Remove a font size in typography so it can be changed
> Add more subtext

- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission-base.module.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/files-step.partial.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/land-use/land-use.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/land-use/land-use.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/land-use/land-use.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/land-use/land-use.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/other-attachments/other-attachments.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/other-attachments/other-attachments.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/other-attachments/other-attachments.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/other-attachments/other-attachments.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/select-government/select-government.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/select-government/select-government.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/select-government/select-government.component.ts
- portal-frontend/src/app/services/notice-of-intent-submission/notice-of-intent-submission.dto.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
* Update stepper with correct number of steps and labels
* Copy over components and setup for NOIs
> Add Steps 2,3,4,7

- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.html
- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.scss
- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.module.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1692030508798-add_noi_intake_fields.ts
* Add more payment fields
* Set statuses when setting certain fields in update
* Add tooltips
> Add new payment fields and hook up statuses

- bin/migrate-oats-data/applications/app_prep.py
- bin/migrate-oats-data/applications/sql/application-prep/application_prep.sql
- bin/migrate-oats-data/applications/sql/application-prep/application_prep_basic_validation.sql
Doing the more elegant and logical way this time
> 1011- Insert fee amounts

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
* Add new requireComponents flag to make components optional for rescinded decisions
> Hide rescinded decision fields instead of disabling

- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/delete-parcel/delete-parcel-dialog.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/delete-parcel/delete-parcel-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry-confirmation-dialog/parcel-entry-confirmation-dialog.component.ts
* Was accidentally still using Application Parcel Service
> Change NOI Parcel Dialog to use NOI Parcel Service

- alcs-frontend/src/app/features/application/decision/decision-v2/revert-to-draft-dialog/revert-to-draft-dialog.component.ts
- alcs-frontend/src/app/services/application/application-code.dto.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/application/application.service.ts
- services/apps/alcs/src/alcs/application/application-submission-status/submission-status.dto.ts
* Sort statuses by weight, not date, to find correct revert status
* Update missed DTO to new codes value to fix release dialog
> Bug fixes for Decision Dialogs

- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission-base.module.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/review-and-submit.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/review-and-submit.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/review-and-submit.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.scss
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.module.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.scss
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.scss
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.ts
- portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html
Add Step 8 for NOIs and ROSO Proposal, not including Step 6
> Add Step 8 for NOI + Roso

- bin/migrate-oats-data/documents/alcs_documents_to_noi_documents.py
- bin/migrate-oats-data/sql/documents_app/alcs_documents_to_app_documents.sql
- bin/migrate-oats-data/sql/documents_app/alcs_documents_to_app_documents_total_count.sql
quick fix to old table application_document_code to document_code
> fixed reference to old table

- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.html
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission-validator.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission-validator.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.module.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
* Add noi validator service
* Update confirmation dialog to new UX
> Add submission and validation for ROSO NOIs

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/nfu-details/nfu-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/nfu-details/nfu-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/nfu-details/nfu-details.component.ts
- portal-frontend/src/app/features/applications/application-details/application-details.component.html
- portal-frontend/src/app/features/applications/application-details/naru-details/naru-details.component.spec.ts
- portal-frontend/src/app/features/applications/application-details/nfu-details/nfu-details.component.html
- portal-frontend/src/app/features/applications/application-details/nfu-details/nfu-details.component.spec.ts
- portal-frontend/src/app/features/applications/application-details/nfu-details/nfu-details.component.ts
- portal-frontend/src/app/features/applications/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.spec.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
* Add to Step 6 and Step 8
* Add to ALCS
> Add Proposal map to NFU Submissions

- bin/migrate-oats-data/applications/sql/insert-batch-application.sql
- bin/migrate-oats-data/noi/sql/insert_noi.sql
- services/apps/alcs/test/pgtap/test_calculate_paused_time.sql
rename application_local_government table to local_government in etl and pgtap
> rename local government table

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/change-noi-type-dialog/change-noi-type-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/change-noi-type-dialog/change-noi-type-dialog.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/change-noi-type-dialog/change-noi-type-dialog.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/change-noi-type-dialog/change-noi-type-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission-base.module.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts
* Add and hook up NOI change type dialog
* Update buttons on change application dialog to be more sensible
> Add NOI Change Type DIalog

- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/services/notice-of-intent-submission/notice-of-intent-submission.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-parcel/notice-of-intent-parcel.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission-validator.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
* Change all to two main functions and remove the extra layers
* Update unit tests
* Only allow editing of In Progress Applications
* Change to just getByFileNumber and getByUuid
> Clean up NOI User Access

- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/alc-review.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/alc-review.component.scss
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/alc-review.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/alc-review.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.scss
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.module.ts
* Add ALC Tab Content and Documents for NOIs
> Add ALC Tab Contents for NOIs

- portal-frontend/src/app/app-routing.module.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.scss
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.module.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.scss
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/confirm-publish-dialog/confirm-publish-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/remove-file-confirmation-dialog/remove-file-confirmation-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/remove-file-confirmation-dialog/remove-file-confirmation-dialog.component.scss
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/remove-file-confirmation-dialog/remove-file-confirmation-dialog.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/remove-file-confirmation-dialog/remove-file-confirmation-dialog.component.ts
- portal-frontend/src/app/services/notice-of-intent-submission/notice-of-intent-submission-draft.service.spec.ts
- portal-frontend/src/app/services/notice-of-intent-submission/notice-of-intent-submission-draft.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.module.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.module.ts
- services/apps/alcs/src/portal/portal.module.ts
> Add NOI Edit Submission

- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/pfrs-details/pfrs-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.html
> Add app update banners to new NOI soil components

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
* This prevents them from validating immediately
> Add required validators asynchronously

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-components.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-components.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.scss
* Error state had no border so was not showing red
* Add confirmation dialogs for removing conditions / components.
> Add confirmation dialogs, fix error state

- bin/migrate-oats-data/migrate.py
- bin/migrate-oats-data/submissions/__init__.py
- bin/migrate-oats-data/submissions/app_submissions.py
- bin/migrate-oats-data/submissions/sql/app_submission.sql
- bin/migrate-oats-data/submissions/sql/app_submission_count.sql
A copy & paste of feature/ALCS-1013 that has a clean commit history and has not strayed from the known path of git
> Submission Base Field Import

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.scss
* Update styling for POFO/PFRS/ROSO Input Components to match new designs
* Update document table to have upload button on the right like other sections
> Decision Fixes

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/incl-excl-input/incl-excl-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.scss
* Rename Ag fields to full names
* Change padding on scroller to line buttons up with edges
* Fix ordering of INCL/EXCL components
> Decision Bug Fixes

- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/alc-review.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/decisions/decisions.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/decisions/decisions.component.scss
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/decisions/decisions.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/decisions/decisions.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.module.ts
- portal-frontend/src/app/services/notice-of-intent-decision/notice-of-intent-decision.dto.ts
- portal-frontend/src/app/services/notice-of-intent-decision/notice-of-intent-decision.service.spec.ts
- portal-frontend/src/app/services/notice-of-intent-decision/notice-of-intent-decision.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.module.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
- services/apps/alcs/src/portal/application-decision/application-decision.dto.ts
- services/apps/alcs/src/portal/notice-of-intent-decision/notice-of-intent-decision.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-decision/notice-of-intent-decision.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-decision/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/portal/notice-of-intent-decision/notice-of-intent-decision.module.ts
- services/apps/alcs/src/portal/portal.module.ts
- services/apps/alcs/src/providers/typeorm/migrations/1692902429290-update_dec_number_generation_for_nois.ts
* Add modules/controllers/ui
* Fix small typos
* Rename existing DTO to include Application
> Show NOI Decisions in Portal

- alcs-frontend/src/app/features/application/overview/overview.component.ts
- portal-frontend/src/app/features/applications/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/applications/edit-submission/select-government/select-government.component.ts
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.ts
* Add special exception to local government uuid
* Pass original submission UUID to app-details so it can be used by parcels
> Fix Edit Submission Updated banners

- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
* Filter to only application parcels on app prep page
* Save POFO and ROSO components if child components are dirty
* Allow updating submissions in draft mode regardless of their status
> Bug Fixes Pt1

- portal-frontend/src/app/features/applications/review-submission/review-contact-information/review-contact-information.component.html
- portal-frontend/src/app/features/applications/review-submission/review-contact-information/review-contact-information.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-ocp/review-ocp.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-resolution/review-resolution.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-submission.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-zoning/review-zoning.component.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/providers/typeorm/datasource.cli.orm.config.ts
* Also don't reload application / documents / etc when changing steps
> Change L/FNG Review to only call save when components are dirty

- alcs-frontend/src/app/features/application/overview/uncancel-application-dialog/uncancel-application-dialog.component.ts
* Should be sorted by weight to get correct result
> Sort statuses by weight not date for Uncancel

- bin/migrate-oats-data/noi/noi.py
- bin/migrate-oats-data/noi/sql/insert_noi.sql
error out on NULL constraint fixed
> Fixed type code issue for NOI ETL

- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.module.ts
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.html
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.scss
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.html
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.scss
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.ts
- portal-frontend/src/app/services/notification-transferee/notification-transferee.dto.ts
- portal-frontend/src/app/services/notification-transferee/notification-transferee.service.spec.ts
- portal-frontend/src/app/services/notification-transferee/notification-transferee.service.ts
- portal-frontend/src/styles.scss
- services/apps/alcs/src/portal/notification-submission/notification-transferee/notification-transferee.controller.ts
> Add Transferees UI

- alcs-frontend/src/app/features/search/application-search-table/application-search-table.component.html
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- alcs-frontend/src/app/features/search/non-application-search-table/non-application-search-table.component.html
- alcs-frontend/src/app/features/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html
- alcs-frontend/src/app/features/search/search.component.html
- alcs-frontend/src/app/features/search/search.component.scss
- alcs-frontend/src/app/features/search/search.component.ts
- alcs-frontend/src/styles.scss
- alcs-frontend/src/styles/autocomplete.scss
- services/apps/alcs/src/alcs/search/search.controller.ts
- services/apps/alcs/src/utils/string-helper.spec.ts
- services/apps/alcs/src/utils/string-helper.ts
- do not search for non-applications if no criteria are provided
- adjust file type dropdown height
- minor ui adjustments
> Advanced search part 4: search adjustments

- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.module.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/delete-parcel/delete-parcel-dialog.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/delete-parcel/delete-parcel-dialog.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/notifications/edit-submission/primary-contact/primary-contact.component.scss
- portal-frontend/src/app/features/notifications/edit-submission/primary-contact/primary-contact.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/select-government/select-government.component.html
- portal-frontend/src/app/features/notifications/edit-submission/select-government/select-government.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/select-government/select-government.component.ts
- portal-frontend/src/app/services/notification-submission/notification-submission.dto.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.controller.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.controller.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.service.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.service.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.dto.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.entity.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1694024021090-add_notification_contact_fields.ts
* Also fix small bug with Parcels using the wrong service
> Add Primary Contact and L/FNG Selection for Notifications

- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.module.ts
- portal-frontend/src/app/features/notifications/edit-submission/files-step.partial.ts
- portal-frontend/src/app/features/notifications/edit-submission/other-attachments/other-attachments.component.html
- portal-frontend/src/app/features/notifications/edit-submission/other-attachments/other-attachments.component.scss
- portal-frontend/src/app/features/notifications/edit-submission/other-attachments/other-attachments.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/other-attachments/other-attachments.component.ts
- portal-frontend/src/app/services/notification-document/notification-document.dto.ts
- portal-frontend/src/app/services/notification-document/notification-document.service.spec.ts
- portal-frontend/src/app/services/notification-document/notification-document.service.ts
- services/apps/alcs/src/alcs/alcs.module.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.controller.spec.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.controller.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.dto.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.entity.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.service.spec.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.service.ts
- services/apps/alcs/src/alcs/notification/notification.entity.ts
- services/apps/alcs/src/alcs/notification/notification.module.ts
- services/apps/alcs/src/common/automapper/notification.automapper.profile.ts
- services/apps/alcs/src/portal/notification-document/notification-document.controller.spec.ts
- services/apps/alcs/src/portal/notification-document/notification-document.controller.ts
- services/apps/alcs/src/portal/notification-document/notification-document.dto.ts
- services/apps/alcs/src/portal/notification-document/notification-document.module.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.controller.spec.ts
- services/apps/alcs/src/portal/portal.module.ts
- services/apps/alcs/src/providers/typeorm/migrations/1694037493007-add_notification_documents.ts
* Add Notification Documents and Other Attachments Page
> Add Notification Documents

- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/release-dialog/release-dialog.component.html
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.ts
- services/apps/alcs/src/alcs/application/application-timeline/application-timeline.service.spec.ts
- services/apps/alcs/src/alcs/application/application-timeline/application-timeline.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-timeline/notice-of-intent-timeline.service.ts
- services/apps/alcs/src/providers/email/email.service.ts
- services/templates/emails/decision-released/application.template.ts
- services/templates/emails/decision-released/notice-of-intent.template.ts
- update timeline for applications and notifications
- remove decision date from templates for noi and applications
> update timeline and decision emails

- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html
- error outline on noi decision for Decision Maker field
> error outline on noi decision for Decision Maker field

- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/document-upload-dialog/document-upload-dialog.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-document/notice-of-intent-document.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-document/notice-of-intent-document.controller.ts
* Add loading of owners / parcels
* Mark previous documents as superseded
> Add special handling for Corporate Summary / Certificate of Title

- portal-frontend/src/app/features/notice-of-intents/edit-submission/review-and-submit/review-and-submit.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.html
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/edit-submission.module.ts
- portal-frontend/src/app/features/notifications/edit-submission/proposal/proposal.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/review-and-submit.component.html
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/review-and-submit.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/review-and-submit.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.html
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.scss
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.ts
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.scss
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.spec.ts
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.ts
- portal-frontend/src/app/features/notifications/notification-details/notification-details.module.ts
- portal-frontend/src/app/features/notifications/notification-details/parcel/parcel.component.html
- portal-frontend/src/app/features/notifications/notification-details/parcel/parcel.component.scss
- portal-frontend/src/app/features/notifications/notification-details/parcel/parcel.component.spec.ts
- portal-frontend/src/app/features/notifications/notification-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.html
- portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.scss
- portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.spec.ts
- portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.controller.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.controller.ts
- services/apps/alcs/src/portal/notification-submission/notification-parcel/notification-parcel.service.ts
* Setup Step 7 for Review
* Fixes for other steps
* Add confirmation dialog to Proposal Step.
> Review & Submit for Notifications

- portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.html
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.html
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
- portal-frontend/src/app/features/notifications/view-submission/alc-review/alc-review.component.html
- portal-frontend/src/app/features/notifications/view-submission/alc-review/alc-review.component.scss
- portal-frontend/src/app/features/notifications/view-submission/alc-review/alc-review.component.spec.ts
- portal-frontend/src/app/features/notifications/view-submission/alc-review/alc-review.component.ts
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.scss
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.html
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.module.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission-validator.service.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission-validator.service.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.controller.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.controller.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.module.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.service.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts
- services/apps/alcs/src/portal/notification-submission/notification-transferee/notification-transferee.controller.ts
- services/apps/alcs/src/portal/notification-submission/notification-transferee/notification-transferee.service.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-transferee/notification-transferee.service.ts
* Add ALC Tab content and documents
> Add Validation to Notification Submission

- alcs-frontend/src/app/services/search/file-type/file-type-data-source.service.spec.ts
- alcs-frontend/src/app/services/search/file-type/file-type-data-source.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v1/application-decision-meeting/application-decision-meeting.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v1/application-decision-meeting/application-decision-meeting.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.ts
- services/apps/alcs/src/alcs/application/application-submission-status/application-submission-status.service.spec.ts
- services/apps/alcs/src/alcs/application/application-submission-status/application-submission-status.service.ts
- services/apps/alcs/src/alcs/application/application-submission-status/submission-status.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-status.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.ts
- services/apps/alcs/src/main.module.ts
- services/apps/alcs/src/providers/email/email.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1694195607654-email_sent_in_status_table.ts
- services/apps/alcs/src/providers/typeorm/migrations/1694214288431-email_sent_in_noi_submission_status_table.ts
- services/apps/alcs/src/queues/scheduler/application/application-expiry/application-expiry.consumer.spec.ts
- services/apps/alcs/src/queues/scheduler/application/application-expiry/application-expiry.consumer.ts
- services/apps/alcs/src/queues/scheduler/application/status-emails/status-emails.consumer.spec.ts
- services/apps/alcs/src/queues/scheduler/application/status-emails/status-emails.consumer.ts
- services/apps/alcs/src/queues/scheduler/notice-of-intent/status-emails.consumer.spec.ts
- services/apps/alcs/src/queues/scheduler/notice-of-intent/status-emails.consumer.ts
- services/apps/alcs/src/queues/scheduler/scheduler.module.ts
- services/apps/alcs/src/queues/scheduler/scheduler.service.spec.ts
- services/apps/alcs/src/queues/scheduler/scheduler.service.ts
- delayed status email sending REVA ALCD for application and NOI
- enable bull mq
- minor fixes
> delayed status email sending ALCD and REVA for Application and NOI

- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.html
- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.ts
- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/board.component.spec.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/board/dialogs/notification/notification-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/notification/notification-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/notification/notification-dialog.component.ts
- alcs-frontend/src/app/services/board/board.dto.ts
- alcs-frontend/src/app/services/notification/notification.dto.ts
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferees.component.ts
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
- services/apps/alcs/src/alcs/admin/board-management/board-management.controller.ts
- services/apps/alcs/src/alcs/board/board.controller.spec.ts
- services/apps/alcs/src/alcs/board/board.controller.ts
- services/apps/alcs/src/alcs/board/board.module.ts
- services/apps/alcs/src/alcs/notification/notification.service.spec.ts
- services/apps/alcs/src/alcs/notification/notification.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1694803254582-add_srw_board.ts
* Add notification card dialog
* Add new board, with new statuses
* Prevent allowing create for NOTIs on any board
* Auto-create GIS Subtask and move card to NOTI board on Submission
> Add SRW Cards and SRW Board

- services/apps/alcs/src/alcs/application/application-submission-status/application-submission-status.service.spec.ts
- services/apps/alcs/src/alcs/application/application-submission-status/application-submission-status.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.ts
- services/apps/alcs/src/queues/scheduler/application/status-emails/status-emails.consumer.ts
- services/apps/alcs/src/queues/scheduler/notice-of-intent/status-emails.consumer.ts
- adjust date filter for email consumer
> adjust date to retrieve submission statuses for email consumers

- services/apps/alcs/src/main.controller.ts
- services/apps/alcs/src/queues/scheduler/application/status-emails/status-emails.consumer.ts
I need some additional log messages to verify logger and if consumers are starting on dev env
> additional log messages

- services/apps/alcs/src/portal/pdf-generation/generate-srw-document.service.ts
* Fix visibility flags to not include public.
> Change Public -> LG on Notification Documents

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/nfu-details/nfu-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/subd-details/subd-details.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/notice-of-intent-details.component.html
- portal-frontend/src/app/features/applications/application-details/application-details.component.html
- portal-frontend/src/app/features/applications/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/applications/application-details/nfu-details/nfu-details.component.html
- portal-frontend/src/app/features/applications/application-details/subd-details/subd-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/land-use/land-use.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/excl-proposal/excl-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/incl-proposal/incl-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/subd-proposal/subd-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/tur-proposal/tur-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/land-use/land-use.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pofo/pofo-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.html
- portal-frontend/test/tests/submissions/NFU_submission_creation.spec.ts
- portal-frontend/test/tests/submissions/TUR_submission_creation.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1695408288984-update_column_text.ts
* Update questions, sublabels, etc for NOIs and Applications
> Text Updates

- bin/migrate-oats-data/noi/notice_of_intent_init.py
- bin/migrate-oats-data/noi/notice_of_intent_migration.py
- bin/migrate-oats-data/noi/oats_to_alcs_notice_of_intent_table_etl/notice_of_intent_decision_date.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_base/notice_of_intent_decision_date/notice_of_intent_decision_date.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_base/notice_of_intent_decision_date/notice_of_intent_decision_date_validation.sql
import NOI decision_date from OATS to ALCS
> NOI decision_date etl

- portal-frontend/src/app/features/home/application-list/application-list.component.html
- portal-frontend/src/app/features/home/home.component.scss
- portal-frontend/src/app/features/home/noi-list/noi-list.component.html
- portal-frontend/src/app/features/home/notification-list/notification-list.component.html
- services/apps/alcs/src/portal/notification-submission/notification-submission.service.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts
- services/apps/alcs/src/providers/email/email.service.ts
- services/apps/alcs/src/providers/email/status-email.service.spec.ts
- services/apps/alcs/src/queues/scheduler/application/application-expiry/application-expiry.consumer.spec.ts
- services/apps/alcs/src/user/user.service.spec.ts
* Add tests for it
* Update email service to return true/false
* Minor UI fix to Inbox
> Only set ALC Response Sent status if Noti Email Sends

- bin/migrate-oats-data/applications/application_submission_status_email/submission_status_email.py
- bin/migrate-oats-data/applications/base_applications.py
- bin/migrate-oats-data/applications/submissions/app_submissions.py
- bin/migrate-oats-data/db.py
- bin/migrate-oats-data/documents/alcs_documents_to_app_documents.py
- bin/migrate-oats-data/documents/alcs_documents_to_noi_documents.py
- bin/migrate-oats-data/documents/oats_documents_to_alcs_documents_app.py
- bin/migrate-oats-data/menu/commands/clean_all.py
- bin/migrate-oats-data/noi/noi_submission_status_email/submission_status_email.py
- bin/migrate-oats-data/noi/notice_of_intent_init.py
- bin/migrate-oats-data/noi/notice_of_intent_migration.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/__init__.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/notice_of_intent_submission_init.py
- bin/migrate-oats-data/noi/oats_to_alcs_notice_of_intent_table_etl/oats_to_alcs_notice_of_intent_table_etl.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/notice_of_intent_submission_init.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/notice_of_intent_submission_init_count.sql
- notice of intent submission base import
- connection.commit fix for clean functions
- fix for exhausted connection pool
> Feature/alcs 1130 Notice of intent submission base etl

- portal-frontend/src/app/app-routing.module.ts
- portal-frontend/src/app/features/login/login.component.html
- portal-frontend/src/app/features/login/login.component.scss
- portal-frontend/src/app/features/login/login.component.spec.ts
- portal-frontend/src/app/features/login/login.component.ts
- portal-frontend/src/app/features/public/public.component.html
- portal-frontend/src/app/features/public/public.component.spec.ts
- portal-frontend/src/app/features/public/public.component.ts
- portal-frontend/src/app/features/public/public.module.ts
- portal-frontend/src/app/shared/header/header.component.html
- portal-frontend/src/app/shared/header/header.component.scss
- portal-frontend/src/app/shared/header/header.component.spec.ts
- portal-frontend/src/app/shared/header/header.component.ts
- portal-frontend/src/styles.scss
* Add new bar to header
* Change landing page to match new design
* Create Public Module and placeholder page
> Update Main Page and Header

- alcs-frontend/src/app/features/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts
- alcs-frontend/src/app/features/search/notification-search-table/notification-search-table.component.ts
- services/apps/alcs/src/alcs/search/search.controller.ts
- fix civic address search
- fix sorting on noi and notifications
> fix notification and noi table sorting

- services/apps/alcs/src/queues/scheduler/scheduler.service.ts
run till 11 pm instead of midnight
> run till 11pm instead of midnight

- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.html
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.scss
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.ts
- Use ViewChildren and QueryList to access ngif search input field
- Focus input field on search icon toggle
- Select input field if no result is found
- Copy File ID to advanced search page if search text was entered to input field
> Improve searchbar interaction and copy file ID to advanced search

- portal-frontend/src/app/shared/pipes/emailValid.pipe.ts
- services/apps/alcs/src/utils/email.helper.ts
* Update email regex to accept capital letters
> Accept emails with capital letters

- bin/migrate-oats-data/noi/notice_of_intent_submissions/notice_of_intent_soil_fields.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/soil_fields/notice_of_intent_soil_fields.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/soil_fields/validation.sql
- add project duration and duration unit in scope of soil fields
- validation script
> add project duration and duration unit in scope of soil fields

- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.ts
- portal-frontend/src/app/features/public/search/public-search.component.html
- portal-frontend/src/app/features/public/search/public-search.component.ts
* When a user searches store what they searched on and re-load if they come back
> Remember Search Fields

- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.ts
- portal-frontend/src/app/shared/soil-table/soil-table.component.html
- Save NARU soil and fill table data on change
- Remove default value set in soil table
- Select input on focus to prevent user error from ngx-mask validation
> Portal table entry bug fixes

- portal-frontend/src/app/features/home/home.component.html
- portal-frontend/src/app/features/home/home.component.spec.ts
- portal-frontend/src/app/features/home/home.component.ts
- portal-frontend/src/app/shared/header/header.component.html
* Show government name over business name
> Add business name to inbox

- portal-frontend/src/app/features/public/application/alc-review/alc-review.component.html
- portal-frontend/src/app/features/public/application/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/public/notice-of-intent/alc-review/alc-review.component.html
- portal-frontend/src/app/features/public/notice-of-intent/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.module.ts
- portal-frontend/src/app/features/public/notification/alc-review/alc-review.component.html
- portal-frontend/src/app/features/public/notification/alc-review/alc-review.component.ts
- portal-frontend/src/app/features/public/notification/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/public/notification/public-notification.component.html
- portal-frontend/src/app/services/public/public.service.spec.ts
- portal-frontend/src/app/services/public/public.service.ts
- services/apps/alcs/src/portal/public/public.controller.ts
* Fix file downloads for all public documents
> Fix File Downloads

- portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.html
- portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.ts
- portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html
- portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts
- portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.html
- portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.ts
- portal-frontend/src/app/services/application-decision/application-decision.service.ts
- portal-frontend/src/app/services/notice-of-intent-decision/notice-of-intent-decision.service.ts
- services/apps/alcs/src/portal/public/application/application-decision.controller.spec.ts
- services/apps/alcs/src/portal/public/application/application-decision.controller.ts
- services/apps/alcs/src/portal/public/notice-of-intent/notice-of-intent-decision.controller.spec.ts
- services/apps/alcs/src/portal/public/notice-of-intent/notice-of-intent-decision.controller.ts
- services/apps/alcs/src/portal/public/search/notification/public-notification-search.service.ts
* Fix Sorting for Notifications on the backend
* Set default sorting to all tables
* Fix routing for decisions for signed in users
> Public Fixes

- services/apps/alcs/src/document/document-code.entity.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.spec.ts
- services/apps/alcs/src/portal/application-document/application-document.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.ts
- services/apps/alcs/src/portal/notification-document/notification-document.controller.spec.ts
- services/apps/alcs/src/portal/notification-document/notification-document.controller.ts
* If document is certain type add public visibility
> Add default visibility flags to portal documents

- services/apps/alcs/src/alcs/application/application-submission-status/application-submission-status.service.spec.ts
- services/apps/alcs/src/alcs/application/application-submission-status/application-submission-status.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.ts
- services/apps/alcs/src/alcs/search/application/application-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.entity.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1697048162692-fix_search_function_status_weights.ts
* Fix function to prefer weight over date
* Only look at statuses for non-draft submissions
> Search Fixes

- bin/migrate-oats-data/noi/notice_of_intent_submissions/statuses/notice_of_intent_status_in_progress.py
- bin/migrate-oats-data/noi/oats_to_alcs_notice_of_intent_table_etl/notice_of_intent_decision_date.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/statuses/in_progress/notice_of_intent_status_in_progress.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/statuses/in_progress/notice_of_intent_status_in_progress_count.sql
- use min date for in-progress status in NOI
> use min date for in progress status in noi

- bin/migrate-oats-data/applications/base_applications.py
- bin/migrate-oats-data/common/__init__.py
- bin/migrate-oats-data/common/oats_temp_tables.py
- bin/migrate-oats-data/noi/notice_of_intent_init.py
allows noi import to run without applications being imported first
> Fix standalone noi-import 

- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notification/applicant-info/notification-details/notification-details.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.scss
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/pfrs-details/pfrs-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.html
- portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.html
- portal-frontend/src/app/features/public/application/submission/parcel/parcel.component.html
- portal-frontend/src/app/features/public/application/submission/parcel/parcel.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/submission/parcel/parcel.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/parcel/parcel.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/submission/pfrs-details/pfrs-details.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/submission/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/pofo-details/pofo-details.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/submission/roso-details/roso-details.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/submission-details.component.scss
- portal-frontend/src/app/features/public/notification/submission/proposal-details/proposal-details.component.html
* Fix spacing of soil table
* Remove "Parcel Information" heading
* Remove Parcel SCSS so it spaces the same as other tables
> Public View Fixes

- portal-frontend/src/app/features/public/notice-of-intent/submission/parcel/parcel.component.scss
- portal-frontend/src/app/features/public/notification/submission/parcel/parcel.component.scss
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
* Already applied to applications but missed here
> Only join non draft decisions for NOIs

- portal-frontend/src/app/services/document/document.service.ts
- portal-frontend/src/app/shared/overlay-spinner/file-overlay-spinner/file-overlay-spinner.component.html
- portal-frontend/src/app/shared/overlay-spinner/file-overlay-spinner/file-overlay-spinner.component.scss
- portal-frontend/src/app/shared/overlay-spinner/file-overlay-spinner/file-overlay-spinner.component.spec.ts
- portal-frontend/src/app/shared/overlay-spinner/file-overlay-spinner/file-overlay-spinner.component.ts
- portal-frontend/src/app/shared/overlay-spinner/overlay-spinner.service.ts
- portal-frontend/src/app/shared/shared.module.ts
* Add new custom overlay spinner for use specifically during file uploads
> Add File Overlay Spinner

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/application/documents/documents.component.html
- alcs-frontend/src/app/features/application/documents/documents.component.spec.ts
- alcs-frontend/src/app/features/application/documents/documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.html
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.ts
* Were always visible before
* Dynamically calculate
> Implement visibility flags

- bin/migrate-oats-data/applications/submissions/data_insert/data_prep.py
- bin/migrate-oats-data/applications/submissions/data_insert/insert_query.py
- bin/migrate-oats-data/applications/submissions/data_insert/submap/soil_elements.py
- bin/migrate-oats-data/applications/submissions/sql/app_submission.sql
- bin/migrate-oats-data/applications/submissions/sql/app_submission_validation.sql
plus some extra fields that were missed before.
> incl_excl fields for app_sub

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-attachments/review-attachments.component.spec.ts
- portal-frontend/src/app/features/applications/review-submission/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
* Add more toast messages for virus failed uploads
> Add missing toast messages

- alcs-frontend/src/app/features/search/application-search-table/application-search-table.component.html
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.scss
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.ts
- alcs-frontend/src/app/features/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html
- alcs-frontend/src/app/features/search/notification-search-table/notification-search-table.component.html
- alcs-frontend/src/app/features/search/search.component.html
- alcs-frontend/src/app/features/search/search.component.scss
- alcs-frontend/src/app/features/search/search.component.ts
- alcs-frontend/src/app/services/search/search.dto.ts
- alcs-frontend/src/app/services/search/search.service.spec.ts
- alcs-frontend/src/styles/autocomplete.scss
- portal-frontend/src/app/services/inbox/inbox.service.spec.ts
- portal-frontend/src/app/services/search/search.service.spec.ts
- services/apps/alcs/src/alcs/search/application/application-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/application/application-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/non-applications/non-applications.service.spec.ts
- services/apps/alcs/src/alcs/search/non-applications/non-applications.service.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/search.controller.spec.ts
- services/apps/alcs/src/alcs/search/search.controller.ts
- services/apps/alcs/src/alcs/search/search.dto.ts
* Remove other parcels
* Use ng-select for all dropdowns
* Add X to file type selector and prevent input
* Add toast message and scrolling
* Sort nulls differently
> Advanced Search Improvements

- bin/migrate-oats-data/documents/alcs_documents_to_app_documents.py
- bin/migrate-oats-data/documents/alcs_documents_to_noi_documents.py
- bin/migrate-oats-data/documents/oats_documents_to_alcs_documents_app.py
- bin/migrate-oats-data/documents/oats_documents_to_alcs_documents_noi.py
- bin/migrate-oats-data/menu/commands/documents.py
- bin/migrate-oats-data/menu/commands/import_all.py
imported correct functions, added comments & updated console log
> Fix oats -> alcs document processing

- portal-frontend/src/app/features/home/inbox/inbox-list/inbox-list.component.html
- portal-frontend/src/app/features/home/inbox/inbox-list/inbox-list.component.ts
- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.html
- portal-frontend/src/app/features/home/inbox/inbox.component.html
- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.scss
* Remove double spinner
* Adjust text
* Add missing dropdown arrow
> Inbox Fixes

- portal-frontend/src/app/features/login/login.component.ts
- portal-frontend/src/app/shared/header/header.component.html
- portal-frontend/src/app/shared/header/header.component.scss
- portal-frontend/src/app/shared/header/header.component.ts
* Redirect Login -> Home if user is already logged in
* Update header to not show profile and logout button when on any public page
* Remove Portal Inbox from header
> Update Header and Login Page

- alcs-frontend/src/app/features/application/decision/decision-v1/decision-v1-dialog/decision-v1-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/application/post-decision/edit-reconsideration-dialog/edit-reconsideration-dialog.component.html
- alcs-frontend/src/app/features/application/post-decision/edit-reconsideration-dialog/edit-reconsideration-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/post-decision/edit-reconsideration-dialog/edit-reconsideration-dialog.component.ts
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.html
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.ts
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.spec.ts
- alcs-frontend/src/app/services/application/application-reconsideration/application-reconsideration.dto.ts
- alcs-frontend/src/app/shared/inline-editors/inline-review-decision-outcome/inline-decision-outcome.component.html
- alcs-frontend/src/app/shared/inline-editors/inline-review-decision-outcome/inline-decision-outcome.component.scss
- alcs-frontend/src/app/shared/inline-editors/inline-review-decision-outcome/inline-decision-outcome.component.spec.ts
- alcs-frontend/src/app/shared/inline-editors/inline-review-decision-outcome/inline-decision-outcome.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.entity.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.service.ts
- services/apps/alcs/src/alcs/application-decision/application-reconsideration/reconsideration-decision-outcome-type/application-reconsideration-outcome-type.entity.ts
- services/apps/alcs/src/common/automapper/reconsideration.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1697745047619-add_recon_decision_outcome.ts
- services/apps/alcs/src/providers/typeorm/migrations/1697745131329-seed_recon_decision_outcome.ts
* Add new Decision Outcome with 3 options
* Re-order fields to match new figma
* Hide Outcome date unless it is Refused
> Updates to Reconsiderations

- portal-frontend/src/app/features/applications/application-details/application-details.component.scss
- portal-frontend/src/app/features/applications/application-details/pfrs-details/pfrs-details.component.scss
- portal-frontend/src/app/features/applications/application-details/subd-details/subd-details.component.scss
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.scss
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.scss
- portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.scss
- Subdivision table
- Survey plan table
- Optional attachment in App, NOI, and SRW (with error message in review page)
> Update submission tables responsive view with error message

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
* Set validators and remove validators was clearing the format validator as well as required
* Update code to use add/remove so the format validator remains on parcel / form changes
> Use add/remove Validators for PID

- portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html
- portal-frontend/src/app/features/public/search/public-search.component.html
- portal-frontend/src/app/features/public/search/search-list/search-list.component.html
- portal-frontend/src/app/features/public/search/search-list/search-list.component.ts
- services/apps/alcs/src/portal/code/code.controller.spec.ts
- services/apps/alcs/src/portal/code/code.controller.ts
* Add type to list component and then use to display not found message
* Update code controller to check if there is an authorization header before trying to decode it and failing.
> Search Bug Fixes

- portal-frontend/src/app/features/applications/application-details/subd-details/subd-details.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
* Add error class to parcel error so it gets scrolled to
* Update logic for toggling the file uploads for ROSO and PFRS to also update the other ones correctly
* Add backend validation for SUBD Proposals including lot size
> Portal Proposal Fixes

- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/notification/notification-dialog.component.spec.ts
- alcs-frontend/src/app/services/application/application-code.dto.ts
- alcs-frontend/src/app/services/application/application.service.spec.ts
- alcs-frontend/src/app/services/search/search.service.spec.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.ts
- portal-frontend/src/app/features/applications/application-details/application-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/applications/view-submission/lfng-review/lfng-review.component.ts
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- services/apps/alcs/src/alcs/application/application.service.ts
- services/apps/alcs/src/alcs/code/application-code/application-type/application-type.dto.ts
- services/apps/alcs/src/alcs/code/application-code/application-type/application-type.entity.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1698255209608-add_app_type_government_review_required.ts
* Use this flag in front end and back end wherever appropriate compared to checking for TURP
* Update Tests
> Add requiresGovernmentReview flag to App Type

- portal-frontend/src/app/features/create-submission-dialog/create-submission-dialog.component.ts
- portal-frontend/src/app/services/code/code.dto.ts
- services/apps/alcs/src/alcs/application/application.service.ts
- services/apps/alcs/src/alcs/code/application-code/application-type/application-type.dto.ts
- services/apps/alcs/src/alcs/code/application-code/application-type/application-type.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1698344015968-add_covenant_app_type.ts
- services/apps/alcs/src/providers/typeorm/migrations/1698345181441-add_portal_type_order.ts
* Add new covenant type with description
* Add portalOrder to set the sorting of the app types in the front end dialog
* Update HTML Description for Applications to include Covenants
> Add Portal Order and Covenants to App Types

- alcs-frontend/src/app/features/notice-of-intent/decision/decision-dialog/decision-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html
Linked Modification Request -> Linked Request
> Update Missed Text for NOI Decisions

- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.module.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/cove-details/cove-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/cove-details/cove-details.component.scss
- alcs-frontend/src/app/features/application/applicant-info/application-details/cove-details/cove-details.component.spec.ts
- alcs-frontend/src/app/features/application/applicant-info/application-details/cove-details/cove-details.component.ts
- alcs-frontend/src/app/services/application/application-submission/application-submission.service.spec.ts
- alcs-frontend/src/app/services/application/application-submission/application-submission.service.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/applications/application-details/cove-details/cove-details.component.ts
- portal-frontend/src/app/features/applications/edit-submission/select-government/select-government.component.html
- portal-frontend/src/app/features/applications/edit-submission/select-government/select-government.component.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.controller.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.service.ts
- services/apps/alcs/src/alcs/application/application.module.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/application-submission/covenant-transferee/covenant-transferee.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1698708663714-relabel_srw_terms.ts
* Added validation in backend + tests for Covenant Submissions
* Add covenant proposal step to ALCS
* Update SRW Terms Label
> Add Covenant Validation and ALCS View

- alcs-frontend/src/app/features/application/proposal/soil/soil.component.html
- alcs-frontend/src/app/features/notice-of-intent/proposal/soil/soil.component.html
- portal-frontend/src/app/features/notifications/edit-submission/proposal/proposal.component.html
Fill -> Soil
Make Input half Width
> Update Text and CSS

- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/notice-of-intent/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/services/search/file-type/file-type-data-source.service.ts
- services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1698773732187-fix_cove_color.ts
* Update labels on app prep / noi prep
* Add Covenant to App Types dropdown
* Fix Covenant color
* Remove Creating V1 covenants from all boards
> Cove Updates

- services/apps/alcs/src/portal/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/templates/emails/submitted-to-alc/cove-applicant.template.ts
- services/templates/emails/submitted-to-alc/index.ts
- services/templates/emails/submitted-to-alc/no-review-government.template.ts
* TURP and COVE use same government template so renamed to no-review template
> Add Email Template for Covenants

- portal-frontend/src/app/features/public/application/public-application.component.html
- portal-frontend/src/app/features/public/application/public-application.component.ts
- portal-frontend/src/app/features/public/application/public-application.module.ts
- portal-frontend/src/app/features/public/application/submission/cove-details/cove-details.component.html
- portal-frontend/src/app/features/public/application/submission/cove-details/cove-details.component.scss
- portal-frontend/src/app/features/public/application/submission/cove-details/cove-details.component.spec.ts
- portal-frontend/src/app/features/public/application/submission/cove-details/cove-details.component.ts
- portal-frontend/src/app/features/public/application/submission/submission-details.component.html
- portal-frontend/src/app/features/public/application/submission/submission-details.component.ts
- portal-frontend/src/app/services/public/public-application.dto.ts
- portal-frontend/src/app/services/search/file-type/file-type-data-source.service.ts
- services/apps/alcs/src/common/automapper/public.automapper.profile.ts
- services/apps/alcs/src/portal/application-submission/application-submission.dto.ts
- services/apps/alcs/src/portal/application-submission/application-submission.module.ts
- services/apps/alcs/src/portal/public/application/public-application.dto.ts
- services/apps/alcs/src/portal/public/application/public-application.service.spec.ts
- services/apps/alcs/src/portal/public/application/public-application.service.ts
* Add Public Covenant Proposal
* Send Transferees in the main request for Covenants
> Covenant Public View

- alcs-frontend/src/app/features/application/applicant-info/application-details/cove-details/cove-details.component.scss
- portal-frontend/src/app/features/applications/application-details/cove-details/cove-details.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/cove-proposal/cove-proposal.component.ts
* Mark form fields as dirty
* Allow overflow to work
> Covenant Fixes

- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html
- portal-frontend/src/app/features/applications/alcs-edit-submission/alcs-edit-submission.component.html
- portal-frontend/src/app/features/applications/alcs-edit-submission/alcs-edit-submission.component.ts
- services/apps/alcs/src/portal/application-submission-draft/application-submission-draft.service.spec.ts
- services/apps/alcs/src/portal/application-submission-draft/application-submission-draft.service.ts
- services/apps/alcs/src/portal/application-submission/covenant-transferee/covenant-transferee.controller.ts
- services/apps/alcs/src/portal/application-submission/covenant-transferee/covenant-transferee.service.spec.ts
- services/apps/alcs/src/portal/application-submission/covenant-transferee/covenant-transferee.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.spec.ts
* Copy over covenants when creating draft
* Delete when publishing
> Update ALCS Edit Submission for Covenants

- services/apps/alcs/src/alcs/application-decision/application-component-lot/application-decision-component-lot.entity.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/component/application-decision-component.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.entity.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.entity.ts
- services/apps/alcs/src/portal/application-submission/application-submission.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.entity.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1699380056668-increase_precision.ts
* Mistake yesterday, need to increase both scale and precision to store more digits
> Increase Precision to allow for the extra decimals

- services/Dockerfile
- services/migrate.sh
* Remove env so we don't print all our secrets
* Update services docker file to load secrets
> DevOps Updates

- alcs-frontend/src/app/features/application/applicant-info/application-details/cove-details/cove-details.component.scss
- portal-frontend/src/app/features/applications/application-details/cove-details/cove-details.component.scss
- portal-frontend/src/app/features/public/application/submission/cove-details/cove-details.component.scss
- services/apps/alcs/src/portal/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
* Allow ALCS users to delete files from portal
* Hide vertical scrollbar
> Covenant Bug Fixes

- alcs-frontend/src/app/features/application/applicant-info/applicant-info.component.html
- alcs-frontend/src/app/features/application/applicant-info/applicant-info.component.scss
- alcs-frontend/src/app/features/application/applicant-info/applicant-info.component.ts
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.html
- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.scss
- alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.ts
- alcs-frontend/src/app/services/application/application.dto.ts
- portal-frontend/src/app/features/applications/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/applications/view-submission/lfng-review/lfng-review.component.scss
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.html
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.scss
- portal-frontend/src/app/services/application-submission/application-submission.dto.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.dto.ts
- services/templates/emails/return-to-lfng/application.template.ts
- services/templates/emails/return-to-lfng/index.ts
Show returned comments in ALCS/Portal
> Show returned comments

- services/apps/alcs/src/alcs/application/application.controller.spec.ts
- services/apps/alcs/src/alcs/application/application.controller.ts
- services/apps/alcs/src/alcs/commissioner/commissioner.controller.spec.ts
- services/apps/alcs/src/alcs/commissioner/commissioner.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.ts
- services/apps/alcs/src/alcs/notification/notification.controller.spec.ts
- services/apps/alcs/src/alcs/notification/notification.controller.ts
- services/apps/alcs/src/common/tracking/file-viewed.entity.ts
- services/apps/alcs/src/common/tracking/tracking.module.ts
- services/apps/alcs/src/common/tracking/tracking.service.ts
- services/apps/alcs/src/main.module.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.controller.spec.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.controller.ts
- services/apps/alcs/src/providers/typeorm/migrations/1700180573212-add_file_tracking.ts
* Add new view track entity to track views
* Store User ID and FIle ID
* Add to calls for loading the detailed objects by file ID for al ALCS
* Add to Portal only if user is L/FNG
> Add View Tracking for Sensitive Data

- portal-frontend/src/app/features/applications/view-submission/alc-review/alc-review.component.html
- portal-frontend/src/app/features/applications/view-submission/alc-review/alc-review.component.ts
- portal-frontend/src/app/services/inbox/inbox.dto.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.spec.ts
- services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Clear submission date when returning to applicant
* Clean up logic for banners and show ALC banner when return to LFNG
* Remove old applicant field and mark owner optional
> LFNG Return Fixes

- services/apps/alcs/src/common/tracking/file-viewed.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1700508807032-convert_user_uuid_to_uuid_tracking.ts
> Change filed viewed user to correct uuid

- bin/migrate-oats-data/applications/app_rx_items.py
- bin/migrate-oats-data/applications/base_applications.py
- bin/migrate-oats-data/applications/migrate_application.py
- bin/migrate-oats-data/applications/sql/application-prep/app_rx_all_items.sql
- bin/migrate-oats-data/applications/sql/application-prep/app_rx_all_items_count.sql
- bin/migrate-oats-data/noi/notice_of_intent_migration.py
- bin/migrate-oats-data/noi/oats_to_alcs_notice_of_intent_table_etl/__init__.py
- bin/migrate-oats-data/noi/oats_to_alcs_notice_of_intent_table_etl/notice_of_intent_rx_all_items.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_base/notice_of_intent_rx_all_items.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_base/notice_of_intent_rx_all_items_count.sql
Note this will not work with obfuscated data, to test either remove the line for 'AND proxy' or use a different who_created value in the DB
> Date received all items for application and NOI

- portal-frontend/src/app/features/home/inbox/inbox.component.scss
- services/apps/alcs/src/portal/inbox/application/inbox-application.service.ts
* Allow  L/FNG to see INCG even when Submitted Date is not set.
* Add !important to beat material
> Add INCG to L/FNG inbox statuses

- bin/migrate-oats-data/applications/submissions/data_insert/insert_query.py
- bin/migrate-oats-data/applications/submissions/sql/app_submission.sql
- bin/migrate-oats-data/noi/notice_of_intent_submissions/notice_of_intent_proposal_fields.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/proposal_fields/notice_of_intent_proposal_fields.sql
Do not merge to develop until users is updated
> created by uuid to submissions + missing fields

- portal-frontend/src/app/features/applications/application-details/application-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/land-use/land-use.component.html
- portal-frontend/src/app/features/applications/edit-submission/select-government/select-government.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/land-use/land-use.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/select-government/select-government.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.html
- portal-frontend/src/app/features/notifications/edit-submission/select-government/select-government.component.html
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
> Update not setup government message

- portal-frontend/src/app/features/applications/edit-submission/change-application-type-dialog/change-application-type-dialog.component.html
- portal-frontend/src/app/features/applications/edit-submission/change-application-type-dialog/change-application-type-dialog.component.ts
- portal-frontend/src/app/features/create-submission-dialog/create-submission-dialog.component.html
- portal-frontend/src/app/features/create-submission-dialog/create-submission-dialog.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/change-noi-type-dialog/change-noi-type-dialog.component.html
- services/apps/alcs/src/providers/typeorm/migrations/1701473272368-update_portal_descriptions.ts
* Update App Change Type sorting to match create
* Add cursor effect when hovering labels (can be clicked)
* Update HTML descriptions for main types
> Create / Change Dialog Improvements

- portal-frontend/src/app/app.component.scss
- portal-frontend/src/app/features/applications/review-submission/review-attachments/review-attachments.component.html
- portal-frontend/src/app/features/applications/review-submission/review-attachments/review-attachments.component.spec.ts
- portal-frontend/src/app/features/applications/review-submission/review-attachments/review-attachments.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-contact-information/review-contact-information.component.html
- portal-frontend/src/app/features/applications/review-submission/review-contact-information/review-contact-information.component.spec.ts
- portal-frontend/src/app/features/applications/review-submission/review-contact-information/review-contact-information.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-ocp/review-ocp.component.html
- portal-frontend/src/app/features/applications/review-submission/review-ocp/review-ocp.component.spec.ts
- portal-frontend/src/app/features/applications/review-submission/review-ocp/review-ocp.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-resolution/review-resolution.component.html
- portal-frontend/src/app/features/applications/review-submission/review-resolution/review-resolution.component.spec.ts
- portal-frontend/src/app/features/applications/review-submission/review-resolution/review-resolution.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-submission.component.html
- portal-frontend/src/app/features/applications/review-submission/review-submission.component.scss
- portal-frontend/src/app/features/applications/review-submission/review-submission.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-submit-fng/review-submit-fng.component.html
- portal-frontend/src/app/features/applications/review-submission/review-submit/review-submit.component.html
- portal-frontend/src/app/features/applications/review-submission/review-zoning/review-zoning.component.html
- portal-frontend/src/app/features/applications/review-submission/review-zoning/review-zoning.component.ts
* Make new menu template and use for all steps except last
* Small UI tweaks and updates
> Update LFNG Review

- portal-frontend/src/app/features/applications/application-details/application-details.component.spec.ts
- portal-frontend/src/app/features/applications/application-details/application-details.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.spec.ts
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.ts
* Hide authorization letter section if its not required and nothing is uploaded
* Only consider owners who are linked to a parcel
> Primary Contact Updates

- portal-frontend/src/app/features/home/inbox/inbox.component.html
- portal-frontend/src/app/features/home/inbox/inbox.component.ts
- portal-frontend/src/app/shared/header/header.component.html
- portal-frontend/src/app/shared/header/header.component.scss
* Use hamburger in tablet size now
* Fix inbox to remove set timeouts and use a variable in the component
> Update Hamburger menu to new designs

- bin/migrate-oats-data/applications/base_applications.py
- bin/migrate-oats-data/applications/sql/insert-batch-application.sql
- bin/migrate-oats-data/applications/submissions/parcels/application_parcel_insert.py
- bin/migrate-oats-data/applications/submissions/parcels/owners/application_owners.py
- bin/migrate-oats-data/applications/submissions/sql/parcels/application_parcels_insert.sql
- bin/migrate-oats-data/applications/submissions/sql/parcels/owners/application_owner.sql
- bin/migrate-oats-data/applications/submissions/sql/parcels/owners/application_parcel_owner_linking.sql
- bin/migrate-oats-data/applications/submissions/sql/parcels/owners/application_parcel_owner_linking_count.sql
- bin/migrate-oats-data/noi/notice_of_intent_submissions/parcels/notice_of_intent_parcel_insert.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/parcels/owners/notice_of_intent_owners.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/parcels/notice_of_intent_parcels_insert.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/parcels/owners/notice_of_intent_owner.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/parcels/owners/notice_of_intent_parcel_owner_linking.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/parcels/owners/notice_of_intent_parcel_owner_linking_count.sql
- services/apps/alcs/src/alcs/application-decision/application-decision-v1/application-decision-meeting/application-decision-meeting.entity.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.entity.ts
- services/apps/alcs/src/alcs/application/application-meeting/application-meeting.entity.ts
- services/apps/alcs/src/alcs/application/application-paused.entity.ts
- services/apps/alcs/src/alcs/application/application.entity.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.entity.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1701992253115-add_oats_property_id_to_parcel.ts
- services/apps/alcs/src/providers/typeorm/migrations/1701993162234-add_oats_property_interes_id_to_application_owner.ts
- services/apps/alcs/src/providers/typeorm/migrations/1702317710836-application_indexes.ts
- services/apps/alcs/src/providers/typeorm/migrations/1702320761790-add_oats_columns_to_noi_parcel_owners.ts
- added indexes to speed up etl insert and delete for applications
- added SOURCE set to APPLICANT for applications imported with ETL
- relinked application owners to parcels
- relinked noi owners to parcels
> properly link owners to parcels

- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
- services/apps/alcs/src/common/authorization/authorization.controller.spec.ts
- services/apps/alcs/src/portal/public/application/application-decision.controller.spec.ts
- services/apps/alcs/src/portal/public/application/application-decision.controller.ts
- services/apps/alcs/src/portal/public/notice-of-intent/notice-of-intent-decision.controller.spec.ts
- services/apps/alcs/src/portal/public/notice-of-intent/notice-of-intent-decision.controller.ts
- services/apps/alcs/src/providers/email/email.module.ts
- services/apps/alcs/src/providers/email/status-email.service.spec.ts
- services/apps/alcs/src/providers/email/status-email.service.ts
- services/apps/alcs/src/queues/scheduler/application/status-emails/status-emails.consumer.spec.ts
- services/apps/alcs/src/queues/scheduler/application/status-emails/status-emails.consumer.ts
- services/apps/alcs/src/queues/scheduler/notice-of-intent/status-emails.consumer.spec.ts
- services/apps/alcs/src/queues/scheduler/notice-of-intent/status-emails.consumer.ts
- services/templates/emails/decision-released/application.template.ts
- services/templates/emails/decision-released/notice-of-intent.template.ts
- Add new public endpoints to download decision document from email
- Update template with new copies and decision document links
- Add new service methods to get and map decision documents for Application and NOI
- Add FIXME comment to bug for future investigation
> Attach document links to decision released emails

- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.html
- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.scss
- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.ts
* Only add hover class to rows with a link
* Clean up link code to not log undefined and not use .click
> Inbox Table Fixes

- alcs-frontend/src/app/features/application/applicant-info/application-details/tur-details/tur-details.component.html
- portal-frontend/src/app/features/applications/application-details/tur-details/tur-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/tur-proposal/tur-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/tur-proposal/tur-proposal.component.scss
- portal-frontend/src/app/features/public/application/submission/tur-details/tur-details.component.html
- Add link to proof of serving notice template
- Change/add label/sublabel for proposal map field
- Added to TUR proposal, review, view, ALCS, and public
> Add applications proof of serving notice template link and updated proposal map label/sublabel (ALCS-1336)

- services/apps/alcs/src/alcs/application-decision/application-reconsideration/reconsideration-decision-outcome-type/application-reconsideration-outcome-type.entity.ts
- services/apps/alcs/src/common/automapper/reconsideration.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1704327423575-remove_dead_entity.ts
* Was added at some point but never used
> Remove Dead Entity

- bin/migrate-oats-data/applications/migrate_application.py
- bin/migrate-oats-data/applications/submissions/__init__.py
- bin/migrate-oats-data/applications/submissions/review/__init__.py
- bin/migrate-oats-data/applications/submissions/review/lg_submission_review.py
- bin/migrate-oats-data/applications/submissions/sql/review/app_submission_review.sql
- bin/migrate-oats-data/applications/submissions/sql/review/app_submission_review_count.sql
Populated known parts of application_submission_review from the Application_Local_Government sheet
- Missing created_by_uuid and is_authorized
> init LG app submission review

- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact-confirmation-dialog/primary-contact-confirmation-dialog.component.html
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact-confirmation-dialog/primary-contact-confirmation-dialog.component.spec.ts
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact-confirmation-dialog/primary-contact-confirmation-dialog.component.ts
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.scss
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact-confirmation-dialog/primary-contact-confirmation-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact-confirmation-dialog/primary-contact-confirmation-dialog.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact-confirmation-dialog/primary-contact-confirmation-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.controller.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.ts
- Clean up small UI discrepancies 
- Major refactor to fix rendering and control flow issues
- Fixed list not being updated after owner delete
- Save toggle state
- Select 'yes' as default
- Updated owner services to allow unsetting of primary contact
**Outstanding issues**
- Radio not showing red on error
- Radio errors showing even when selected
> QA fixes for primary contact (ALCS-555, partial)

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
* Accidentally remove when adding in other new disabled state
> Add back isDraft calculation

- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/applications/application-details/subd-details/subd-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/incl-proposal/incl-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/subd-proposal/subd-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notifications/notification-details/parcel/parcel.component.html
* Disable all fields on step 1 until they select Fee Simple or Crown
* Remove disabled logic from parcel entry as its not used
* Hide file upload on Step 8 for SUBD if not required
* Disable soil and fill questions on NFU and NARU unless they answer Yes
> Change logic of disabling / showing hiding fields for App & NOI

- bin/migrate-oats-data/applications/submissions/review/lg_submission_review.py
- bin/migrate-oats-data/applications/submissions/sql/review/app_submission_review.sql
- bin/migrate-oats-data/applications/submissions/sql/review/app_submission_review_count.sql
- etl is_authorized flag for application_submission_review
- tiny clean up
> populate is_authorized flag

- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.ts
- services/apps/alcs/src/providers/typeorm/migrations/1704920088781-disable_v1_create_cards.ts
* Remove App and NOI creation from all boards
* Hide in Admin UI for Create
> Prevent creating v1 cards

- portal-frontend/src/app/features/applications/edit-submission/proposal/cove-proposal/cove-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/cove-proposal/cove-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/excl-proposal/excl-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/excl-proposal/excl-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/incl-proposal/incl-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/incl-proposal/incl-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/subd-proposal/subd-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/subd-proposal/subd-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/tur-proposal/tur-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/tur-proposal/tur-proposal.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pofo/pofo-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pofo/pofo-proposal.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.scss
* Remove Fixme and put the real link in
* Standardize wording of all sections
* Remove consideration message
* Update Step 6 of NOIs as well for the same message
> Update Links on all Proposal Components

- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.html
Added a conditional container to that whole section, except the no owner warning (NOI and app).
> Fix radio list error still showing when no owners (ALCS-555)

- bin/migrate-files/README.md
- bin/migrate-oats-data/applications/submissions/data_insert/data_prep.py
- duration field mapping updates for:
- naru
- nfu
- pfrs
> duration field mapping update for naru, nfu

- portal-frontend/src/app/features/applications/application-details/cove-details/cove-details.component.html
- portal-frontend/src/app/features/applications/application-details/incl-details/incl-details.component.html
- portal-frontend/src/app/features/applications/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.spec.ts
- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.html
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
* Update some Step 8s for conditional rendering
* Disable owner search dropdown entirely
* Disable PMBC search
* Apply disable/enable to SRWs
> QA Fixes for Show / Hide

- bin/migrate-files/application_docs/application_docs_import.py
- bin/migrate-files/common/log_file_helper.py
- document import on windows
- record the last imported file on every file upload rather than at the end of batch
> document import on windows

- portal-frontend/src/app/features/applications/alcs-edit-submission/alcs-edit-submission.component.ts
- Added NARU proposal component to ALCS edit submission
- Added check for NARU proposal component on proposal save
> Fix NAUR proposal not being saved in ALCS front-end (ALCS-1395)

- bin/migrate-files/README.md
- bare bones instructions on running docs import in windows
> updated readme for windows

- bin/migrate-oats-data/applications/migrate_application.py
- bin/migrate-oats-data/applications/submissions/__init__.py
- bin/migrate-oats-data/applications/submissions/app_submissions.py
- bin/migrate-oats-data/applications/submissions/data_insert/__init__.py
- bin/migrate-oats-data/applications/submissions/data_insert/covenant_update.py
- update COVE fields in application_submission
- set draft covenant to false
> update application_submissions for covenants

- services/apps/alcs/src/portal/inbox/application/inbox-application.service.spec.ts
- services/apps/alcs/src/portal/inbox/application/inbox-application.service.ts
- services/apps/alcs/src/portal/inbox/notice-of-intent/inbox-notice-of-intent.service.spec.ts
- services/apps/alcs/src/portal/inbox/notice-of-intent/inbox-notice-of-intent.service.ts
- services/apps/alcs/src/portal/inbox/notification/inbox-notification.service.spec.ts
- services/apps/alcs/src/portal/inbox/notification/inbox-notification.service.ts
- Apply same fix from #1316 to inbox search
- Includes a couple auto-format changes
> Apply 1328 fix to inbox search as well (ALCS-1459)

- bin/migrate-oats-data/applications/submissions/review/lg_submission_review.py
- is ocp True if Y OR N
- is zoning True if Y or N
> Update Zoning and OCP Designation for Gov Review

- bin/migrate-oats-data/applications/__init__.py
- bin/migrate-oats-data/applications/application_decision_date.py
- bin/migrate-oats-data/applications/migrate_application.py
- bin/migrate-oats-data/applications/sql/application_decision_date/application_decision_date.sql
- bin/migrate-oats-data/applications/sql/application_decision_date/application_decision_date_count.sql
- bin/migrate-oats-data/applications/sql/application_decision_date/application_decision_date_validation.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_base/notice_of_intent_decision_date/notice_of_intent_decision_date_count.sql
- application.decision_date ETL
- fixes for NOI decision_date count
- tidy
> etl application.decision_date

- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.html
- portal-frontend/src/app/services/authentication/token-refresh.service.ts
* Add debug messages to token refresh
> Hook up error messages to correct fields

- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/nfu-proposal/nfu-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pofo/pofo-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.html
- portal-frontend/src/app/shared/soil-table/soil-table.component.ts
* Set flag in all proposal steps using the soil table
> Add touch all flag to soil table to display errors

- portal-frontend/src/app/features/applications/application-details/application-details.component.html
- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/applications/review-submission/review-submit-fng/review-submit-fng.component.html
- portal-frontend/src/app/features/applications/review-submission/review-submit/review-submit.component.html
- portal-frontend/src/app/features/applications/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.html
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
* Format phone numbers to nice formats
> Add missing phone masks

- alcs-frontend/src/app/features/application/decision/decision.component.html
- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/notice-of-intent/proposal/proposal.component.html
* Previously we only had ALCS and Applicant, now we have OATS
* We want to show all V2 features for OATS applications
> Update Logic for OATS type Apps

- bin/migrate-oats-data/applications/decisions/application_decisions_init.py
- bin/migrate-oats-data/noi/noi_decisions/notice_of_intent_decisions_init.py
- update UPSERT values for application and noi decisions
- update chair review required field mapping
> ETL application/noi decission fields mapping updates

- bin/migrate-oats-data/applications/submissions/parcels/primary_contact/application_primary_contact.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/parcels/primary_contacts/notice_of_intent_primary_contact.py
- update owners so primary contact does not show "None" for first name if primary contact is an organization
> Update Primary contact First Name

- portal-frontend/src/app/features/applications/application-details/nfu-details/nfu-details.component.html
- portal-frontend/src/app/features/applications/application-details/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.html
- portal-frontend/src/app/features/public/application/submission/nfu-details/nfu-details.component.html
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Add missing required messages for EMLI and Placer mining fields
* Add No Data and required error for NFU Hectares
* Re-order POFO Step 8 questions to Match Step 6
* Update backend so nfuHectares, nfuOutslideLands and nfuAgricultureSupport fields can be cleared
> Bug Fixes for Portal

- alcs-frontend/Dockerfile
- alcs-frontend/README.md
- alcs-frontend/src/app/services/authentication/authentication.service.ts
- portal-frontend/src/app/app.component.scss
- portal-frontend/src/app/app.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.scss
- portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.scss
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.scss
- portal-frontend/src/app/features/public/application/public-application.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.component.scss
- portal-frontend/src/app/features/public/notification/public-notification.component.scss
- services/apps/alcs/src/alcs/application/application-submission-status/submission-status.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-document/notice-of-intent-document.service.spec.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
- services/apps/alcs/src/clamav/clamav.service.ts
- services/apps/alcs/src/queues/scheduler/application/application-expiry/application-expiry.consumer.ts
* Fix the ones I can
* Remove the ones that don't matter
> Clean up TODO and FIXMEs

- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.ts
- services/templates/emails/partials/portal-button.template.ts
* Update Portal Button to use URL from Config
* Add sending of cancellation email for NOIs
> Email Fixes

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/shared/owner-dialogs/crown-owner-dialog/crown-owner-dialog.component.html
- portal-frontend/src/app/shared/owner-dialogs/crown-owner-dialog/crown-owner-dialog.component.ts
- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.html
- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts
* Add loading to owner dialogs to prevent duplicate clicks
* Save parcels when adding a new owner to ensure the parcel type is saved.
> Owner Fixes

- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.ts
- alcs-frontend/src/app/features/notice-of-intent/proposal/proposal.component.html
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
* Remove unneeded ?s from LINTing
* Fix NOI Parcel DTO
* Add logic to hide corporate summary for Crown Parcels
> Fix Parcel Layout for NOI Crown Parcels

- bin/migrate-oats-data/applications/submissions/data_insert/data_prep.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/notice_of_intent_proposal_fields.py
Proposal background description mapping for POFO, ROSO, PFRS, INCL, EXCL
> proposal background description mapping for POFO, ROSO, PFRS, INCL, EXCL

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/incl-excl-input/incl-excl-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/incl-excl-input/incl-excl-input.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/notice-of-intent/proposal/proposal.component.html
* Add error outline for Applicant Type
* Change Area from ha to m2
> Fixes for Decisions Components

- bin/migrate-oats-data/applications/migrate_application.py
- bin/migrate-oats-data/applications/submissions/__init__.py
- bin/migrate-oats-data/applications/submissions/application_applicant_on_submissions.py
- bin/migrate-oats-data/applications/submissions/parcels/application_parcel_insert.py
- bin/migrate-oats-data/applications/submissions/parcels/owners/application_owners.py
- bin/migrate-oats-data/applications/submissions/sql/applicant/application_applicant.sql
- bin/migrate-oats-data/applications/submissions/sql/applicant/application_applicant_count.sql
- bin/migrate-oats-data/common/date_time_helper.py
- bin/migrate-oats-data/noi/notice_of_intent_migration.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/__init__.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/notice_of_intent_applicant_on_submissions.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/parcels/notice_of_intent_parcel_insert.py
- bin/migrate-oats-data/noi/notice_of_intent_submissions/parcels/owners/notice_of_intent_owners.py
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/applicant/notice_of_intent_applicant.sql
- bin/migrate-oats-data/noi/sql/notice_of_intent_submission/applicant/notice_of_intent_applicant_count.sql
- update audit_created_at on parcel and owner for application and noi so the dates will different from each other and allow sorting
- update applicant on application_submission
- update applicant on noi_submission
> Update applicant on NOI and Application

- bin/migrate-oats-data/applications/decisions/app_components/application_decision_components_init.py
- bin/migrate-oats-data/noi/noi_decisions/noi_components/notice_of_intent_decision_components_init.py
- set expiry, end_date or both
- use logic in ticket
> adjust expiry/end_date for components

- bin/migrate-oats-data/noi/notice_of_intent_submissions/parcels/primary_contacts/notice_of_intent_primary_contact.py
> Remove None from NOI as well

- bin/migrate-oats-data/common/__init__.py
- bin/migrate-oats-data/common/oats_to_alcs_document_source_code.py
- bin/migrate-oats-data/documents/document_source_update.py
-added enum to covert oats doc source to ALCS
> Use ALCS document Source mapping

- alcs-frontend/src/app/features/application/applicant-info/applicant-info.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.ts
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.ts
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/applicant-info.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/notice-of-intent-details.component.ts
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/notice-of-intent-details.module.ts
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.ts
- alcs-frontend/src/app/features/notice-of-intent/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/features/notice-of-intent/proposal/parcel-prep/parcel-prep.component.ts
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-details.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.html
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.html
- portal-frontend/src/app/features/public/application/public-application.component.html
- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.component.html
- portal-frontend/src/app/features/public/notification/public-notification.component.html
Spinners added to:
* Applicant Info (NOI+APP)
* App Prep Parcels (NOI+APP)
* View App in Portal (NOI+APP)
* Public View App in Portal (NOI+APP+SRW)
> Add Lots of Loading Spinners

- portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.html
- portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.ts
- portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html
- portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts
- portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.html
- portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.ts
- portal-frontend/src/app/features/public/search/public-search.component.html
- portal-frontend/src/app/features/public/search/public-search.component.ts
* Bind all values so that when component is hidden then rendered it doesn't lose settings
* use on sort change instead of subscribing to the component
> Add Loading Spinners to Public Search

- alcs-frontend/src/app/features/search/application-search-table/application-search-table.component.html
- alcs-frontend/src/app/features/search/application-search-table/application-search-table.component.ts
- alcs-frontend/src/app/features/search/non-application-search-table/non-application-search-table.component.html
- alcs-frontend/src/app/features/search/non-application-search-table/non-application-search-table.component.ts
- alcs-frontend/src/app/features/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html
- alcs-frontend/src/app/features/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts
- alcs-frontend/src/app/features/search/notification-search-table/notification-search-table.component.html
- alcs-frontend/src/app/features/search/notification-search-table/notification-search-table.component.ts
- alcs-frontend/src/app/features/search/search.component.ts
- alcs-frontend/src/app/features/search/search.interface.ts
* Add search spinners on changing page or changing page size
> Add Search Spinners to ALCS

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
* Don't clear form on search to prevent fields from going red
* Add dynamic mask and length that changes based on PID or PIN
> Parcel Entry Fixes

- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.html
- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.ts
- portal-frontend/src/app/features/home/inbox/inbox.component.ts
* Move pagination loading to inside the component to prevent it losing state
* Clean up the inbox table as I did the search tables
* Reset items per page on clear
> Cleanup Inbox Table

- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
* Was being set as required when crown instead of fee simple
> Switch pid validators

- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/roso-details/roso-details.component.html
- portal-frontend/src/app/features/applications/application-details/pfrs-details/pfrs-details.component.html
- portal-frontend/src/app/features/applications/application-details/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/applications/application-details/roso-details/roso-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/roso-details/roso-details.component.html
* Had cross sections instead of reclamation plans in several places
> Show Correct Documents

- bin/migrate-oats-data/applications/migrate_application.py
- bin/migrate-oats-data/noi/notice_of_intent_migration.py
- remove ETL unknown applicant update
> ETL unknown applicant 

- services/apps/alcs/src/portal/public/search/application/public-application-search.service.ts
- services/apps/alcs/src/portal/public/search/notice-of-intent/public-notice-of-intent-search.service.ts
> Do not include Draft Decisions in Decisions Filters

- services/apps/alcs/src/providers/typeorm/migrations/1707410497801-add_leading_zero_to_pid.ts
add leading zero to PID on application, notice_of_intent, notification
> add leading zero to PID

- portal-frontend/src/app/features/notice-of-intents/edit-submission/select-government/select-government.component.ts
- services/apps/alcs/src/portal/application-submission-draft/application-submission-draft.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.ts
- Disable gov field in NOI edit submission
- Add missing crown type values in draft mappers
> Fixes for ALCS edit submission

- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/services/notice-of-intent-document/notice-of-intent-document.service.spec.ts
- portal-frontend/src/app/services/notice-of-intent-document/notice-of-intent-document.service.ts
- services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.ts
> Add download file to ALC Review Tab for NOI

- alcs-frontend/src/app/features/application/applicant-info/application-details/subd-details/subd-details.component.html
> Hide homesite severance

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry-confirmation-dialog/parcel-entry-confirmation-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry-confirmation-dialog/parcel-entry-confirmation-dialog.component.html
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry-confirmation-dialog/parcel-entry-confirmation-dialog.component.html
Changes made to application, NOI, and SRW
> Update parcel confirmation dialog text

- services/apps/alcs/src/alcs/application/application.controller.spec.ts
- services/apps/alcs/src/alcs/application/application.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.ts
- services/apps/alcs/src/common/authorization/authorization.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.controller.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.controller.ts
* Add checks in ALCS for both
* You can only cancel NOI in Portal when its in progress currently, so delete that email code
* Add check in Portal for Apps
* Add tests
> Don't send email for In Progress Apps / NOIs

- services/apps/alcs/src/providers/typeorm/migrations/1707760803513-set_applicant_on_noi_submission.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707760810880-set_applicant_on_noi.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707760907222-set_applicant_on_application_submission.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707760911787-set_applicant_on_application.ts
Using the last name of the first owner on the first parcel update:
- applicant field on application submission and applications
- applicant field on notice of intent submission and notice of intent
> migration script for application and notice of intent applicants

- services/templates/emails/cancelled/application.template.ts
- services/templates/emails/cancelled/notice-of-intent.template.ts
- services/templates/emails/decision-released/application.template.ts
- services/templates/emails/decision-released/notice-of-intent.template.ts
- services/templates/emails/notifications/srw-notice.template.ts
- services/templates/emails/partials/footer.template.ts
- services/templates/emails/refused-to-forward.template.ts
- services/templates/emails/return-to-lfng/application.template.ts
- services/templates/emails/returned-as-incomplete.template.ts
- services/templates/emails/submitted-to-alc/application.template.ts
- services/templates/emails/submitted-to-alc/cove-applicant.template.ts
- services/templates/emails/submitted-to-alc/no-review-government.template.ts
- services/templates/emails/submitted-to-alc/noi-applicant.template.ts
- services/templates/emails/submitted-to-alc/noi-government.template.ts
- services/templates/emails/submitted-to-alc/tur-applicant.template.ts
- services/templates/emails/submitted-to-lfng/applicant.template.ts
- services/templates/emails/submitted-to-lfng/government.template.ts
- services/templates/emails/under-review-by-alc.template.ts
- services/templates/emails/under-review-by-lfng.template.ts
- services/templates/emails/wrong-lfng.template.ts
* Prevents email from getting clipped
> Add a display none uuid at the end of the footer

- services/apps/alcs/src/providers/typeorm/migrations/1707760803513-set_applicant_on_noi_submission.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707760810880-set_applicant_on_noi.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707760907222-set_applicant_on_application_submission.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707760911787-set_applicant_on_application.ts
- added extra space in applicant migration 
- exclude nulls from update statement for application and noi
> added extra space in applicant migration

- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.html
- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.scss
- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.spec.ts
- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.ts
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.html
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.scss
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.ts
- alcs-frontend/src/app/services/application/application-boundary-amendments/application-boundary-amendment.dto.ts
- alcs-frontend/src/app/services/application/application-boundary-amendments/application-boundary-amendment.service.spec.ts
- alcs-frontend/src/app/services/application/application-boundary-amendments/application-boundary-amendment.service.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.entity.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision-v2.module.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1707851049233-add_boundary_amendments.ts
* Only shows for inclusion exclusion
* Update the navigation to support conditional items based on appTypes
* Add new entity, service, controller
* Add new page to front end under app detail
* Unit tests
> Add Boundary Amendments

- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.html
- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.ts
- alcs-frontend/src/app/features/application/decision/decision.module.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-boundary-amendment/application-boundary-amendment.service.ts
* Add confirmation dialog for delete
* Add inline editors for year/period
+ Clean up decision module
> Boundary Amendments Pt2

- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.html
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.ts
- Removed view child
- Moved blurring to close/clear event
> Fix assignee select not blurring for all scenarios

- portal-frontend/src/app/features/login/login.component.spec.ts
- portal-frontend/src/app/features/login/login.component.ts
- portal-frontend/src/app/services/maintenance/maintenance.service.spec.ts
- portal-frontend/src/app/services/maintenance/maintenance.service.ts
- services/apps/alcs/src/main.controller.ts
* Add portal routed health check
* Call portal health check everytime we load the login page
* This will trigger the maintenance mode redirect if the portal is in maintenance mode
> Use Portal Healthcheck for Maintenance Mode

- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.ts
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.ts
- portal-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- portal-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.scss
- portal-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
- portal-frontend/src/app/shared/owner-dialogs/crown-owner-dialog/crown-owner-dialog.component.ts
- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts
- portal-frontend/src/app/shared/warning-banner/warning-banner.component.scss
- Update confirmation dialog UI to use warning banner in body message and require title
- Add title to all components that used common dialog service
- Show confirmation dialog if previous type selection has filled input
> Update portal confirmation dialog UI and add check to structure type change

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.ts
* Don't count the current decision in the date rules
* Don't set a min date if its the first decision
> Decision Date Fixes

- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.html
- alcs-frontend/src/app/features/application/boundary-amendment/boundary-amendment.component.ts
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.html
* Add inline editor to area
* Add ha suffix to input field
> Update Boundary Amendments

- services/apps/alcs/src/alcs/import/application-import.service.spec.ts
- services/apps/alcs/src/alcs/import/application-import.service.ts
- services/apps/alcs/src/alcs/import/import.module.ts
- services/apps/alcs/src/commands/import.ts
- services/apps/alcs/src/main.ts
* Re-purpose existing import to populate some data on ETLd records
> Update Import for new Logic

- portal-frontend/src/app/features/create-submission-dialog/create-submission-dialog.component.html
- portal-frontend/src/app/shared/prescribed-body/prescribed-body.component.ts
* Move Read more into the warning banner to be consistent with other pages
* Add scrolling for warning banners on prescribed body
> Create Submission UI Fixes

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
* Change units from ha -> m2 for mislabeled area fields
* Change placeholder to match field name
* Clean up bad HTML
> Soil Labeling Fixes

- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.html
- portal-frontend/src/app/features/public/application/submission/parcel/parcel.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/parcel/parcel.component.html
- portal-frontend/src/app/services/public/public.dto.ts
- services/apps/alcs/src/portal/public/public.dto.ts
- Crown type capitalized in step 1 apps and nois
- crown type view standardized across public search and alcs view
> crown type modifications

- bin/migrate-oats-data/documents/__init__.py
- bin/migrate-oats-data/documents/post_launch/__init__.py
- bin/migrate-oats-data/documents/post_launch/alcs_documents_to_notification_documents.py
- bin/migrate-oats-data/documents/post_launch/migrate_documents.py
- bin/migrate-oats-data/documents/post_launch/oats_documents_to_alcs_documents_srw.py
- bin/migrate-oats-data/documents/post_launch/sql/alcs_documents_to_notification_documents.sql
- bin/migrate-oats-data/documents/post_launch/sql/alcs_documents_to_notification_documents_count.sql
- bin/migrate-oats-data/documents/post_launch/sql/oats_documents_to_alcs_documents.sql
- bin/migrate-oats-data/documents/post_launch/sql/oats_documents_to_alcs_documents_count.sql
- bin/migrate-oats-data/menu/post_launch_commands/__init__.py
- bin/migrate-oats-data/menu/post_launch_commands/clean_all.py
- bin/migrate-oats-data/menu/post_launch_commands/documents.py
- bin/migrate-oats-data/menu/post_launch_commands/import_all.py
- bin/migrate-oats-data/migrate.py
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1709614448912-add_oats_doc_app_id_to_notification_docs.ts
- services/apps/alcs/src/providers/typeorm/migrations/1709615421151-add_notification_unique_exclusion.ts
- Import oats notification docs to alcs
- link alcs docs to notifications
> Notification Documents

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html
* TEMPORARY FIX ONLY FOR PRODUCTION WILL DO REAL FIX WITH MORE TIME
> Only render removed button for last row of additional structures

- bin/migrate-oats-data/srw/submission/parcel/srw_parcel_init.py
- bin/migrate-oats-data/srw/submission/primary_contact/srw_process_primary_contact.py
- bin/migrate-oats-data/srw/submission/transferee/srw_init_transferee.py
- add leading zero to pid, 
- tweak mapping for first_name
> Small tweaks to SRW mapping

- alcs-frontend/src/app/features/board/dialogs/planning-review/create/create-planning-review-dialog.component.html
- alcs-frontend/src/app/features/planning-review/header/header.component.ts
- alcs-frontend/src/app/features/planning-review/overview/overview.component.html
- alcs-frontend/src/app/features/planning-review/overview/overview.component.ts
- alcs-frontend/src/app/shared/inline-editors/inline-button-toggle/inline-button-toggle.component.html
- alcs-frontend/src/app/shared/inline-editors/inline-button-toggle/inline-button-toggle.component.scss
- alcs-frontend/src/app/shared/inline-editors/inline-button-toggle/inline-button-toggle.component.spec.ts
- alcs-frontend/src/app/shared/inline-editors/inline-button-toggle/inline-button-toggle.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.dto.ts
* Use to toggle Open/Closed for PRs
> Add Inline Toggle Component

- bin/migrate-oats-data/srw/post_launch/srw_migration.py
- bin/migrate-oats-data/srw/sql/submission/statuses/init_srw_status.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/init_srw_status_count.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_cancelled.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_cancelled_count.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_in_progress.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_in_progress_count.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_response_sent.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_response_sent_count.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_submitted_alc.sql
- bin/migrate-oats-data/srw/sql/submission/statuses/srw_submitted_alc_count.sql
- bin/migrate-oats-data/srw/submission/__init__.py
- bin/migrate-oats-data/srw/submission/statuses/__init__.py
- bin/migrate-oats-data/srw/submission/statuses/srw_status_base_insert.py
- bin/migrate-oats-data/srw/submission/statuses/srw_status_cancelled.py
- bin/migrate-oats-data/srw/submission/statuses/srw_status_in_progress.py
- bin/migrate-oats-data/srw/submission/statuses/srw_status_response_sent.py
- bin/migrate-oats-data/srw/submission/statuses/srw_status_submitted_alc.py
-init statuses
-populate submission statuses
> ETL SRW Statuses

- .github/workflows/e2e-test.yml
> Fix expression string not wrapped in quotes

- bin/migrate-oats-data/common/constants.py
- bin/migrate-oats-data/srw/srw_staff_journal.py
- bin/migrate-oats-data/srw/submission/srw_proposal_fields.py
- bin/migrate-oats-data/staff_journal_users/populate_staff_journal_users.py
- add default user to SRW submission
- move default user to constants
> added default etl user uuid to srw

- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/additional-information/additional-information.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.scss
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/pfrs-details/pfrs-details.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/pofo-details/pofo-details.component.html
- Display correct org text for individual owners
- Show area-wide fill question in ALCS detail
- Align proposal field order with portal order
- Add m^2 to ALCS applicant structures table
> Four bug fixes for ALCS applicant info

- alcs-frontend/src/app/features/planning-review/decision/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/planning-review/decision/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/planning-review/planning-review.component.ts
- alcs-frontend/src/app/features/planning-review/referrals/referral.component.scss
- alcs-frontend/src/app/features/planning-review/referrals/referral.component.ts
* Change menu order
* Keep columns evenly sized
* Add missing confirmation dialog
* Update Decision Document visibility
> Fixes for PRs

- bin/migrate-oats-data/menu/post_launch_commands/documents.py
- bin/migrate-oats-data/menu/post_launch_commands/import_all.py
- bin/migrate-oats-data/srw/post_launch/srw_migration.py
- bin/migrate-oats-data/srw/sql/submission/proposal_fields/srw_survey_plan_update.sql
- bin/migrate-oats-data/srw/sql/submission/proposal_fields/srw_survey_plan_update_count.sql
- bin/migrate-oats-data/srw/submission/__init__.py
- bin/migrate-oats-data/srw/submission/srw_survey_update.py
if SRWP or SURV file present set survey plan indicator to true
> SET survey plan

- bin/migrate-oats-data/srw/sql/submission/parcel/srw_parcels_insert.sql
- bin/migrate-oats-data/srw/submission/parcel/srw_parcel_init.py
- use mapping from applications/nois
- if property_owner_type is missing ise logic based of PIN and PID
> Update Parcel ownership mapping

- bin/migrate-oats-data/documents/post_launch/alcs_documents_to_notification_documents.py
- bin/migrate-oats-data/documents/post_launch/sql/alcs_documents_to_notification_documents.sql
-propagate document description from oats documents
> Add SRW document description

- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.ts
- alcs-frontend/src/app/shared/application-type-pill/application-type-pill.constants.ts
- alcs-frontend/src/app/shared/card/card.component.scss
- services/apps/alcs/src/alcs/planning-review/planning-referral/planning-referral.service.ts
* Load assignee so it shows the avatar circle
* Only add due date padding when its not the only child
* Use actual PR type instead of fixed type
> More PR Card Fixes

- alcs-frontend/src/app/features/search/planning-review-search-table/planning-review-search-table.component.ts
- alcs-frontend/src/app/features/search/search.component.html
- alcs-frontend/src/app/features/search/search.component.ts
- services/apps/alcs/src/alcs/search/planning-review/planning-review-advanced-search.service.ts
* Update field description
* Fix search by document name
> PR search fixes

- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.scss
- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- Add missing 'No Data' for app fields
- Add missing 'No Data' for NOI preview
- Certificate of title was missing completely
- Fix useless scrollbar showing up
- Some auto-format changes
> Fix 'No Data' text missing and unneeded scrollbar in ALCS detail

- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.scss
- alcs-frontend/src/app/features/admin/board-management/board-management.component.ts
- alcs-frontend/src/app/features/board/board.component.spec.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/inquiry/inquiry-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/inquiry/inquiry-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/inquiry/inquiry-dialog.component.ts
- alcs-frontend/src/app/services/board/board.dto.ts
- alcs-frontend/src/app/services/inquiry/inquiry-parcel/inquiry-parcel.dto.ts
- alcs-frontend/src/app/services/inquiry/inquiry.dto.ts
- alcs-frontend/src/app/services/inquiry/inquiry.service.spec.ts
- alcs-frontend/src/app/services/inquiry/inquiry.service.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- services/apps/alcs/src/alcs/board/board.controller.spec.ts
- services/apps/alcs/src/alcs/board/board.controller.ts
- services/apps/alcs/src/alcs/board/board.dto.ts
- services/apps/alcs/src/alcs/board/board.module.ts
- services/apps/alcs/src/alcs/card/card-type/card-type.entity.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.controller.spec.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.controller.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.dto.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.entity.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.module.ts
* Add front end dialogs for creating and viewing inquiries
> Creation of Inquiries

- alcs-frontend/src/app/features/application/documents/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/features/notification/documents/document-upload-dialog/document-upload-dialog.component.ts
* Previously would not send the new file and only change the name
> Attach pending files to update document requests

- alcs-frontend/src/app/features/home/assigned/assigned.component.html
- alcs-frontend/src/app/features/home/assigned/assigned.component.spec.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/features/home/subtask/subtask.component.html
- alcs-frontend/src/app/features/home/subtask/subtask.component.ts
- alcs-frontend/src/app/services/home/home.service.ts
- services/apps/alcs/src/alcs/card/card-subtask/card-subtask.dto.ts
- services/apps/alcs/src/alcs/home/home.controller.spec.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/home/home.module.ts
> Add Inquiries to Home page

- bin/migrate-oats-data/planning_review/migrate_planning_review.py
- bin/migrate-oats-data/planning_review/planning_review_staff_journal.py
- bin/migrate-oats-data/planning_review/referrals/__init__.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_card_init.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_card_update.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_referrals_init.py
- bin/migrate-oats-data/planning_review/sql/planning_review_base_update.sql
- bin/migrate-oats-data/planning_review/sql/planning_review_staff_journal.sql
- bin/migrate-oats-data/planning_review/sql/planning_review_staff_journal_count.sql
- bin/migrate-oats-data/planning_review/sql/referrals/init_planning_review_cards.sql
- bin/migrate-oats-data/planning_review/sql/referrals/init_planning_review_cards_count.sql
- bin/migrate-oats-data/planning_review/sql/referrals/insert_planning_review_referrals.sql
- bin/migrate-oats-data/planning_review/sql/referrals/insert_planning_review_referrals_count.sql
- bin/migrate-oats-data/planning_review/sql/referrals/update_planning_review_cards.sql
- bin/migrate-oats-data/planning_review/sql/referrals/update_planning_review_cards_count.sql
- create and update cards
- pr staff journal import
- planning referrals
> Planning Review Referral

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.ts
- Refactor to use boolean value directly
- Add error class when touched and invalid
> Add correct error class to 'Approval Dependent' field when invalid

- alcs-frontend/src/app/features/admin/admin.component.scss
- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.scss
- alcs-frontend/src/app/features/application/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/features/inquiry/inquiry.component.scss
- alcs-frontend/src/app/features/notice-of-intent/notice-of-intent.component.scss
- alcs-frontend/src/app/features/notice-of-intent/proposal/parcel-prep/parcel-prep.component.html
- alcs-frontend/src/app/features/notification/intake/intake.component.ts
- alcs-frontend/src/app/features/notification/notification.component.scss
- alcs-frontend/src/app/features/planning-review/planning-review.component.scss
- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.html
- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
* Change detailed page layout for all types to scroll the child content not the window
* Add index column to evidentiary records
* Add scrollable to document sorting to it scrolls
* Add mask to PID on Proposal
> UI Changes

- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.html
- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.scss
- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.scss
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
* Add a Move to Top / Bottom menu when right clicking on either Application or PR evidentiary records
> Add Right Click Sorting Menu

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/styles.scss
- Improve app/NOI gen res number button visibility
- Improve app/NOI decision long text field UX
- Remove redundant mixin def
- Preserve new lines app/NOI decision text fields
> Improve app/NOI gen res button visibility, multiline text editing/viewing

- bin/migrate-oats-data/planning_review/planning_review_base_update.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_card_init.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_card_update.py
update changes, from gdoc comments
> Planning review ETL updates

- alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.scss
- alcs-frontend/src/app/features/inquiry/detail/details.component.html
- alcs-frontend/src/app/features/inquiry/detail/details.component.ts
- alcs-frontend/src/app/features/inquiry/header/header.component.ts
- alcs-frontend/src/app/features/inquiry/inquiry.component.ts
- alcs-frontend/src/app/features/inquiry/parcel/parcels.component.html
- alcs-frontend/src/app/services/inquiry/inquiry.dto.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.dto.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.module.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.service.spec.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.service.ts
* Set title on inquiry page
* Add code for updating inquiry region and local government
* Add error message to create dialog
* Add spacing to create parcel table
> Inquiry Fixes

- bin/migrate-oats-data/documents/post_launch/alcs_documents_to_planning_review_documents.py
- bin/migrate-oats-data/documents/post_launch/migrate_documents.py
- bin/migrate-oats-data/documents/post_launch/oats_documents_to_alcs_documents_planning_review.py
- bin/migrate-oats-data/documents/post_launch/sql/planning_review/alcs_documents_to_planning_review_documents.sql
- bin/migrate-oats-data/documents/post_launch/sql/planning_review/alcs_documents_to_planning_review_documents_count.sql
- bin/migrate-oats-data/documents/post_launch/sql/planning_review/oats_documents_to_alcs_documents.sql
- bin/migrate-oats-data/documents/post_launch/sql/planning_review/oats_documents_to_alcs_documents_count.sql
- bin/migrate-oats-data/menu/command_parser/document_command_parser.py
- bin/migrate-oats-data/menu/menu.py
- bin/migrate-oats-data/menu/post_launch_commands/clean_all.py
- bin/migrate-oats-data/menu/post_launch_commands/documents.py
- bin/migrate-oats-data/menu/post_launch_commands/import_all.py
- bin/migrate-oats-data/migrate.py
- services/apps/alcs/src/alcs/planning-review/planning-review-document/planning-review-document.entity.ts
- services/apps/alcs/src/document/document.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1711670649388-add_planning_review_id_to_documents.ts
- services/apps/alcs/src/providers/typeorm/migrations/1712088761489-add_pr_audit_created_by.ts
- services/apps/alcs/src/providers/typeorm/migrations/1712090189047-add_contraint_to_pr_docs.ts
- Handles db side document import and linking for planning reviews
> Planning review Docs

- services/apps/alcs/test/pgtap/test_calculate_paused_time.sql
> fix pgtap test

- services/apps/alcs/src/providers/typeorm/migrations/1712159113804-create-cards-for-applications.ts
- services/apps/alcs/src/providers/typeorm/migrations/1712164553675-create-cards-for-nois.ts
- create cards for provided applications
- create cards for provided NOIs
- backup tables for applications and NOIs that got card created and linked
> migrations to create cards for applications and nois

- services/apps/alcs/src/alcs/notification/notification.controller.ts
> Pass req instead of user entity to get function

- .codeclimate.yml
- services/package.json
* Exclude DTOs, Modules, and Entities
* Exclude Command and Import Folder (Ansley said to keep not delete)
> Update coverage rules

- bin/migrate-oats-data/common/alcs_planning_review_enum.py
- bin/migrate-oats-data/common/oats_to_alcs_planning_review_type.py
- bin/migrate-oats-data/planning_review/decisions/__init__.py
- bin/migrate-oats-data/planning_review/decisions/init_planning_review_decisions.py
- bin/migrate-oats-data/planning_review/migrate_planning_review.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_card_init.py
- bin/migrate-oats-data/planning_review/referrals/planning_review_card_update.py
- bin/migrate-oats-data/planning_review/sql/decisions/planning_review_decisions_insert.sql
- bin/migrate-oats-data/planning_review/sql/decisions/planning_review_decisions_insert_count.sql
- bin/migrate-oats-data/planning_review/sql/referrals/update_planning_review_cards.sql
- populate planning review decisions
- bugfix to alcs.cards concerning planning reviews
> Planning review decisions ETL

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.spec.ts
- services/apps/alcs/src/alcs/local-government/local-government.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.spec.ts
- services/apps/alcs/src/common/tracking/tracking.service.spec.ts
- services/apps/alcs/src/portal/public/public.controller.spec.ts
- services/apps/alcs/src/portal/public/status/public-status.controller.spec.ts
> Add backend tests

- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.html
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.ts
- alcs-frontend/src/app/shared/application-type-pill/application-type-pill.constants.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.service.ts
- services/apps/alcs/src/alcs/notification/notification.service.ts
* Remove hardcoded notification type
> Populate Notification and Inquiry AppType for Home Page

- bin/migrate-oats-data/documents/post_launch/migrate_documents.py
- bin/migrate-oats-data/documents/post_launch/oats_documents_to_alcs_documents_srw.py
- bin/migrate-oats-data/inquiry/inquiry_migration.py
- bin/migrate-oats-data/inquiry/inquiry_staff_journal.py
- bin/migrate-oats-data/inquiry/sql/inquiry_staff_journal_insert.sql
- bin/migrate-oats-data/inquiry/sql/inquiry_staff_journal_insert_count.sql
- bin/migrate-oats-data/menu/post_launch_commands/__init__.py
- bin/migrate-oats-data/menu/post_launch_commands/clean_all.py
- bin/migrate-oats-data/menu/post_launch_commands/documents.py
- bin/migrate-oats-data/menu/post_launch_commands/import_all.py
- bin/migrate-oats-data/migrate.py
- import issue notes into alcs staff journals
- fix issue with import all and clean all still touching srws and previous code
- import and clean commands now only though pr and inquires
> inquiry staff journal import + etl bugfix

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.spec.ts
- portal-frontend/src/app/features/public/search/public-search.component.spec.ts
- portal-frontend/src/app/features/public/search/public-search.component.ts
* Add component tests to some of the larger portal components
> Add Portal Unit Tests

- bin/migrate-oats-data/documents/post_launch/alcs_documents_to_inquiry_documents.py
- bin/migrate-oats-data/documents/post_launch/alcs_documents_to_notification_documents.py
- bin/migrate-oats-data/documents/post_launch/alcs_documents_to_planning_review_documents.py
- bin/migrate-oats-data/documents/post_launch/migrate_documents.py
- bin/migrate-oats-data/documents/post_launch/oats_documents_to_alcs_documents_inquiry.py
- bin/migrate-oats-data/documents/post_launch/oats_documents_to_alcs_documents_planning_review.py
- bin/migrate-oats-data/documents/post_launch/oats_documents_to_alcs_documents_srw.py
- bin/migrate-oats-data/documents/post_launch/sql/inquiry/alcs_documents_to_inquiry_documents.sql
- bin/migrate-oats-data/documents/post_launch/sql/inquiry/alcs_documents_to_inquiry_documents_count.sql
- bin/migrate-oats-data/documents/post_launch/sql/inquiry/oats_documents_to_alcs_documents.sql
- bin/migrate-oats-data/documents/post_launch/sql/inquiry/oats_documents_to_alcs_documents_count.sql
- services/apps/alcs/src/alcs/inquiry/inquiry-document/inquiry-document.entity.ts
- services/apps/alcs/src/document/document.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1712618156742-add_cols_and_contraint_to_inq_docs.ts
- services/apps/alcs/src/providers/typeorm/migrations/1712619551207-add_auditor.ts
- import inquiry docs to alcs
- link alcs docs to inquiry
- fix bug with planning review mime type
- did not touch document import (ECS)
> init inquiry documents

- alcs-frontend/src/app/services/application/application-staff-journal/staff-journal.service.spec.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.service.spec.ts
- alcs-frontend/src/app/services/inquiry/inquiry.service.spec.ts
- alcs-frontend/src/app/services/inquiry/inquiry.service.ts
- alcs-frontend/src/app/services/message/message.service.spec.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent-parcel/notice-of-intent-parcel.service.spec.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.service.spec.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.service.ts
- alcs-frontend/src/app/services/notification/notification-detail.service.spec.ts
- alcs-frontend/src/app/services/notification/notification.service.spec.ts
- alcs-frontend/src/app/services/toast/toast.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.dto.ts
* Also delete dead create code
> More tests!

- bin/migrate-oats-data/inquiry/inquiry_migration.py
- bin/migrate-oats-data/inquiry/parcels/inquiry_parcel_insert.py
- bin/migrate-oats-data/inquiry/sql/parcels/inquiry_parcel_insert.sql
- bin/migrate-oats-data/inquiry/sql/parcels/inquiry_parcel_insert_count.sql
- services/apps/alcs/src/alcs/inquiry/inquiry.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1712701842929-add_prop_ids_to_inq_parcels.ts
- init inquiry parcels
- add property_id and subject_property_id to inquiry_parcels for ETL preservation
- PID padded with zeros to 9 digits
- Only adds parcels with alr_application_land_ind = 'Y'
> Init inquiry parcels

- services/apps/alcs/src/common/authorization/authorization.controller.spec.ts
- services/apps/alcs/src/common/authorization/roles-guard.service.spec.ts
- services/apps/alcs/src/common/authorization/roles-guard.service.ts
- services/apps/alcs/src/user/user.service.spec.ts
- services/apps/alcs/src/user/user.service.ts
- services/apps/alcs/test/mocks/mockTypes.ts
* Cache users in redis for loading them for each request
> Caches users in Redis

- services/apps/alcs/src/document/document.service.ts
- services/apps/alcs/src/portal/guards/maintenance.guard.ts
- maintenance mode guard update
> refactor maintenance guard

- services/apps/alcs/src/alcs/search/planning-review/planning-review-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/planning-review/planning-review-advanced-search.service.ts
- add sorting by status to planning review
> sort by status in planning review

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pfrs-input/pfrs-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/pofo-input/pofo-input.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/roso-input/roso-input.component.html
added missing field labels on textarea in decision component for application and noi
> add field labels on textarea fields in decision

- portal-frontend/package-lock.json
- portal-frontend/package.json
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
* Re-enable remove from any position
* Switch everything from index to ID
* Update tests
> Change Additional Structures form to use ID instead of Index

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-file-upload-dialog/decision-document-upload-dialog.component.ts
fix the decision document upload function to include the mime type of uploaded file
> added missing mime type to decision documents upload

- services/apps/alcs/src/alcs/inquiry/inquiry-document/inquiry-document.entity.ts
- services/apps/alcs/src/alcs/inquiry/inquiry-parcel/inquiry-parcel.entity.ts
- services/apps/alcs/src/alcs/inquiry/inquiry.entity.ts
- services/apps/alcs/src/alcs/planning-review/planning-review-document/planning-review-document.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1713311722985-add_oats_property_ids_to_inquiry_parcels.ts
- Added Unique to entity
- Inquiry and inquiry-parcel entities were swapped
- fix inquiry_document typo to inquiry_parcel and create new migration
> fix migration & entity issues with documents, inquiries & planning review

- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notification/applicant-info/notification-details/parcel/parcel.component.html
- alcs-frontend/src/app/services/application/application.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-details.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/public/application/submission/parcel/parcel.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/parcel/parcel.component.html
- portal-frontend/src/app/services/application-parcel/application-parcel.dto.ts
- portal-frontend/src/app/services/notice-of-intent-parcel/notice-of-intent-parcel.dto.ts
- portal-frontend/src/app/services/public/public.dto.ts
- services/apps/alcs/src/portal/application-submission/application-owner/application-owner.dto.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.dto.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.entity.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.dto.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.ts
- services/apps/alcs/src/portal/public/public.dto.ts
- services/apps/alcs/src/providers/typeorm/migrations/1713299422987-remove_parcel_ownershiptype.ts
> Remove crownLandOwnerType from Parcels

- services/apps/alcs/src/portal/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
* For ALCS users add a bypass that any user with ALCS roles is allowed to view the application to allow them to see documents attached to drafts that were copied over
> When checking document access only check NON draft submissions

- portal-frontend/src/styles.scss
- portal-frontend/src/styles/buttons.scss
* Change portal buttons to bold / uppercase
* Add code to set checkbox checks to white
> Update styling for Buttons/Checkboxes

- alcs-frontend/src/app/features/application/applicant-info/applicant-info.component.ts
- show all steps from application for L/FNG Refused to Forward
> fix for wasSubmittedToLfng

- services/apps/alcs/src/portal/pdf-generation/generate-noi-submission-document.service.ts
- services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.ts
Add pdf to end of submission updated pdf
> Add missing file extensions

- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/services/authentication/auth.interceptor.spec.ts
- alcs-frontend/src/app/services/authentication/auth.interceptor.ts
- alcs-frontend/src/app/services/authentication/unauthorized.interceptor.spec.ts
- alcs-frontend/src/app/services/authentication/unauthorized.interceptor.ts
* Clean up existing interceptor to be more interceptor, less service
> Add interceptor to redirect to login on 401

- bin/migrate-oats-data/migrate.py
- bin/migrate-oats-data/prod_db_obfuscation/alcs/inquiry/__init__.py
- bin/migrate-oats-data/prod_db_obfuscation/alcs/inquiry/inquiry.py
- bin/migrate-oats-data/prod_db_obfuscation/alcs/obfuscate.py
- bin/migrate-oats-data/prod_db_obfuscation/alcs/planning_review/__init__.py
- bin/migrate-oats-data/prod_db_obfuscation/alcs/planning_review/planning_review.py
- Overwrite PII and other sensitive info
- add obfuscate back into migrate function
-  did not touch oats, appears not needed as it is being handled
> Obfuscate Planning Review & Inquiries

- services/apps/alcs/src/alcs/application-decision/application-decision.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.entity.ts
- services/apps/alcs/src/portal/public/search/application/public-application-search-view.entity.ts
- services/apps/alcs/src/portal/public/search/application/public-application-search.service.spec.ts
- services/apps/alcs/src/portal/public/search/application/public-application-search.service.ts
- services/apps/alcs/src/portal/public/search/notice-of-intent/public-notice-of-intent-search.service.ts
- services/apps/alcs/src/portal/public/search/notification/public-notification-search.service.ts
- services/apps/alcs/src/portal/public/search/public-search.controller.ts
- services/apps/alcs/src/providers/typeorm/migrations/1713894259298-update_public_search.ts
* Parallelize all searches to happen at the same time
* Remove unnecessary join for type (was already added in mapping layer)
* Add debug performance timing
> Search Performance Improvements

- bin/migrate-oats-data/inquiry/sql/parcels/inquiry_parcel_insert.sql
- bin/migrate-oats-data/inquiry/sql/parcels/inquiry_parcel_insert_count.sql
- take all parcels / ignore alr_application_land_ind
> remove clause to check for alr_application_land_ind in inquiries 

- alcs-frontend/src/app/features/application/intake/intake.component.html
- alcs-frontend/src/app/features/application/intake/intake.component.scss
- alcs-frontend/src/app/features/application/intake/intake.component.spec.ts
- alcs-frontend/src/app/features/application/intake/intake.component.ts
- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.html
- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.scss
- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/intake/intake.component.ts
- alcs-frontend/src/app/features/planning-review/overview/overview.component.html
- alcs-frontend/src/app/features/planning-review/overview/overview.component.scss
- alcs-frontend/src/app/features/planning-review/overview/overview.component.spec.ts
- alcs-frontend/src/app/features/planning-review/overview/overview.component.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent.dto.ts
- alcs-frontend/src/app/services/planning-review/planning-review.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.dto.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.module.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.service.spec.ts
- services/apps/alcs/src/alcs/planning-review/planning-review.service.ts
* Add Region to NOI + App
* Add L/FNG + Region to PRs
> Add Region / Local Government Dropdowns

- portal-frontend/src/app/features/notice-of-intents/edit-submission/select-government/select-government.component.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.module.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.ts
- update local government on NOI submission update
- send email if local government changed
> Feature/alcs 1815 - update local government on NOI

- services/apps/alcs/src/alcs/application/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/alcs/application/application-submission/application-submission.service.ts
- services/apps/alcs/src/alcs/application/application.module.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission/notice-of-intent-submission.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.module.ts
- split retrieval of submission and owner into 2 queries 
The step above led to performance improvement from 23 seconds to 0.23 seconds on submisisonService.get(...
> improve get submission for noi and application

- portal-frontend/src/app/features/applications/edit-submission/proposal/cove-proposal/transferee-dialog/transferee-dialog.component.scss
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.html
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.scss
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.scss
- portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.scss
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.html
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.scss
- portal-frontend/src/app/features/public/application/public-application.component.html
- portal-frontend/src/app/features/public/application/public-application.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.component.html
- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.component.scss
- portal-frontend/src/app/features/public/notification/public-notification.component.html
- portal-frontend/src/app/features/public/notification/public-notification.component.scss
- portal-frontend/src/app/shared/owner-dialogs/crown-owner-dialog/crown-owner-dialog.component.html
- portal-frontend/src/app/shared/owner-dialogs/crown-owner-dialog/crown-owner-dialog.component.scss
- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.scss
- Remove duplicated absolute positioned banner that hid page elements
- Add responsive styling to crown owner dialog actions to match owner dialog
> Fix portal submission detail banners and crown owner dialog buttons

- services/apps/alcs/src/portal/public/search/application/public-application-search.service.ts
- services/apps/alcs/src/portal/public/search/notice-of-intent/public-notice-of-intent-search.service.ts
- services/apps/alcs/src/portal/public/search/notification/public-notification-search.service.ts
> Fix File Type on Public Search

- alcs-frontend/nginx.conf
- alcs-frontend/src/app/app.component.ts
- alcs-frontend/src/app/app.module.ts
- alcs-frontend/src/app/services/analytics/analytics.service.ts
- portal-frontend/nginx.conf
- portal-frontend/src/app/app.component.ts
> Allow Snowplow via CSP

- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-submission-status/notice-of-intent-submission-status.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission-draft/notice-of-intent-submission-draft.service.ts
- fix sending email on LFNG change on NOI
> fix send email on LFNG change

- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/features/home/subtask/subtask.component.ts
* Was missing from some subtask views
> Add inquiry to assigned and subtask counts

- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-file-upload-dialog/decision-document-upload-dialog.component.ts
- alcs-frontend/src/app/features/planning-review/decision/decision-input/decision-file-upload-dialog/decision-document-upload-dialog.component.ts
* This retains the type so not everything it octet-stream
* Code was already in place for applications
> Retain file type when renaming file

- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.spec.ts
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.ts
- portal-frontend/src/app/features/public/notice-of-intent/submission/submission-details.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/submission-details.component.ts
* Hook up built component
* Fix CSS and Rename
> Add Additional Information to Public NOIs

- services/package-lock.json
- services/package.json
> Downgrade CLS Package

- services/apps/alcs/src/clamav/clamav.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1715274839125-fix-mime-types-for-files.ts
- update mime-types for pdf files
- bonus: fix clamav service to allow upload for local
> update file mime-type, update for clamAV

- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.scss
- portal-frontend/src/app/features/public/search/file-type-filter-drop-down/file-type-filter-drop-down.component.ts
- portal-frontend/src/app/features/public/search/public-search.component.html
- portal-frontend/src/app/features/public/search/public-search.component.scss
* Add close button to all controls
* Update type dropdown to reset typed values unless they are valid and clear filter when blurring
> UI Improvements on Public Search

- portal-frontend/src/app/app.module.ts
- portal-frontend/src/app/features/applications/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-details.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/applications/review-submission/review-submission.component.ts
- portal-frontend/src/app/features/home/home.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-details.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-details.component.ts
- portal-frontend/src/app/features/notifications/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.service.ts
- Also cleaned up everywhere `disableClose` is set for individual dialogs
> Disable close on click-outside globally for portal

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/shared/owner-dialogs/parcel-owners/parcel-owners.component.ts
- Parcel owner dialog now returns updated owner
- Parcel entry component now updates list from dialog return value
> Parcel owner dialog now returns updated owner

- services/apps/alcs/src/alcs/search/application/application-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/inquiry/inquiry-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/planning-review/planning-review-advanced-search.service.ts
* Fix name queries being terribly wrong, must not have tested this myself
* Change variable names for date_submitted so they do not conflict
> ALCS Search Fixes

- alcs-frontend/src/app/features/admin/admin.module.ts
- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.html
- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.scss
- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.ts
* Copy chips from CC emails feature
> Change Admin Government Emails to use Chips

- portal-frontend/src/app/features/public/search/public-search.component.html
- portal-frontend/src/app/features/public/search/public-search.component.ts
- Split datepicker
- Remove placeholder
- Limit dates
- Open picker by clicking anywhere on field
- Prevent direct editing of date text input
> Improve public search decision date picker

- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.scss
- alcs-frontend/src/app/features/search/search.component.html
- alcs-frontend/src/app/features/search/search.component.scss
- alcs-frontend/src/app/features/search/search.component.ts
* Re-organize components
* Remove View more section
* Change date picker to open on click and prevent typing
> ALCS Advanced Search UI Reorg

- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.spec.ts
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.ts
- alcs-frontend/src/app/features/search/search.component.html
- alcs-frontend/src/app/features/search/search.component.scss
- alcs-frontend/src/app/features/search/search.component.ts
- alcs-frontend/src/app/services/search/portal-status/portal-status-data-source.service.spec.ts
- alcs-frontend/src/app/services/search/portal-status/portal-status-data-source.service.ts
- alcs-frontend/src/app/services/search/search.dto.ts
- services/apps/alcs/src/alcs/search/application/application-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/application/application-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.ts
- services/apps/alcs/src/alcs/search/planning-review/planning-review-advanced-search.service.spec.ts
- services/apps/alcs/src/alcs/search/search.controller.ts
- services/apps/alcs/src/alcs/search/search.dto.ts
* Generalize the file type filter dropdown to take in more inputs to be re-usable
* Add a new data source for portal status types according to Ticket
* Switch existing component to use a combo of the above
> Change Portal Status to Multi Select

- alcs-frontend/src/app/features/search/search.component.scss
- portal-frontend/src/app/features/home/inbox/inbox.component.scss
- portal-frontend/src/app/features/public/search/public-search.component.html
- portal-frontend/src/app/features/public/search/public-search.component.scss
* Move close to be after date picker icon to be consistent with other fields
> Fix alignment of close icons

- alcs-frontend/src/app/features/application/applicant-info/application-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/parcel/parcel.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/pofo-details/pofo-details.component.html
- alcs-frontend/src/app/features/notice-of-intent/applicant-info/notice-of-intent-details/roso-details/roso-details.component.html
- alcs-frontend/src/app/features/notification/applicant-info/notification-details/notification-details.component.html
- alcs-frontend/src/app/features/notification/applicant-info/notification-details/parcel/parcel.component.html
* Unify parcel labels to be like the portal
* Add missing ha
* Show ha/m on already filled/already placed table as 0 is valid
> Update ALCS Labels

- alcs-frontend/src/app/features/planning-review/referrals/referral.component.html
- alcs-frontend/src/app/shared/inline-editors/inline-textarea/inline-textarea.component.html
- alcs-frontend/src/app/shared/inline-editors/inline-textarea/inline-textarea.component.scss
- alcs-frontend/src/app/shared/inline-editors/inline-textarea/inline-textarea.component.ts
* Update text area so it wraps text
* Move edit button to after the text instead of to the right of it
> Change referral to use text area for two fields

- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html
- alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.scss
* Add to ALCS file selector to match other dropdowns
> Add Dropdown Arrow to File Selector

- services/apps/alcs/src/providers/typeorm/migrations/1716326002959-add_missing_lfng_reviews.ts
* Add reviews to submissions that are currently in Under Review by L/FNG and do not have a review
> Add missing LFNG Reviews

- services/apps/alcs/src/alcs/card/card.service.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-parcel/application-parcel.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/application-submission/covenant-transferee/covenant-transferee.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-parcel/notice-of-intent-parcel.service.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts
* Sort owners by first name
* Sort transferees by first name
* Sort card subtasks by created date
> Add sorting to lots of queries

- portal-frontend/src/app/features/applications/edit-submission/proposal/cove-proposal/transferee-dialog/transferee-dialog.component.ts
- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts
* Update transferee to not clear org name
* Update owners to properly clear files when switching to indv
> Fixes for changing Indv/Org in Dialogs

- docs/jobs.md
* Uses copy instead of insert for better performance
> Add batching and PG_COPY setting

- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts
Fixed the corporate summary file issue when adding new owner in NOI/Apps step 1:
- Fixed the file missing issue when changing owner type from org -> individual -> org
- Fixed the corporate summary file getting attached to individual owner type
> Fix Corporate Summary file issue on Parcel Owners table in NOIs/Apps

- portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts
Fix corporate summary not being discarded after changing from organization to individual on edit dialog
> Fix corporate summary not being discarded after changing in edit

- alcs-frontend/src/app/features/board/board.component.scss
- alcs-frontend/src/app/shared/commenting/comments.component.html
- alcs-frontend/src/app/shared/drag-drop-board/drag-drop-board.component.scss
- alcs-frontend/src/app/shared/mention-textarea/mention-textarea.component.html
- alcs-frontend/src/app/shared/mention-textarea/mention-textarea.component.scss
- alcs-frontend/src/app/shared/staff-journal/staff-journal-note-input/staff-journal-note-input.component.html
- Remove underline from mention list items
- Change comment box display to outline
- Add space between input and buttons
- Fix sticky board header
- Change staff journal input to outline
> ALCS board, comment, staff journal UI tweaks

- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.html
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.scss
- alcs-frontend/src/styles/ngselect.scss
UI/UX Changes to the home page:
- Added a '-' placeholder of type when NOI is not retroactive.
- Resized active days columns to make more space for the type column. Changed column sizes from fixed 25%.
- Changed assignee dropdown appearance from outline to fill. Added padding to the dropdown items.
> Homepage UI/UX Fix 

- portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts
Also added some type annotations.
> Make sure `selectedThirdPartyAgent` syncs with toggle

- alcs-frontend/src/app/features/home/assigned/assigned-table/assigned-table.component.html
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.scss
- Added '-' placeholder to non-retroactive NOIs in the "Cards Assigned to Me" section
- Adjusted columns' size for the "type" column to have multiple pills. (Increase type and decreased workflow stage widths)
> Fix Homepage UI/UX Bugs

- alcs-frontend/src/app/features/application/info-requests/info-request-dialog/info-request-dialog.component.html
- alcs-frontend/src/app/features/application/info-requests/info-request-dialog/info-request-dialog.component.scss
- alcs-frontend/src/app/features/notice-of-intent/info-requests/info-request-dialog/info-request-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/info-requests/info-request-dialog/info-request-dialog.component.scss
Following changes have been made for applications and NOIs Information Request dialog:
- Aligned text input with other radio button
- Changed the appearance of "Reason" section from filled to outline
> Fix UI/UX Bugs for Application and NOI Info Request

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/expiry-date-input/expiry-date-input.component.html
- Set ALR area to accept max 5 decimal places
- Fix TUR, COV, SUB ALR area mask to show all decimals
> Set ALR area validation and TUR, COV, SUB area mask to accept 5 decimal places

- services/apps/alcs/src/providers/typeorm/migrations/1718645937227-remove_rffg_from_select_files.ts
- File numbers: 66716 and  11073
> Remove dates from RFFG for select file numbers

- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/component/application-decision-component.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/component/application-decision-component.service.ts
Fix Application Decision Components' fields not being updated if the new values are null.
> Fix Application Decision Component PATCH not working for null values

- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.scss
- portal-frontend/src/app/features/home/home.component.scss
- portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.scss
- portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.scss
- portal-frontend/src/app/features/public/application/public-application.component.scss
- portal-frontend/src/app/features/public/notice-of-intent/public-notice-of-intent.component.scss
- portal-frontend/src/app/features/public/notification/public-notification.component.scss
- portal-frontend/src/app/features/public/search/public-search.component.scss
- portal-frontend/src/styles/tabs.scss
- **Clean up redundant tab formatting**
- **Set correct sizes and weight for all tabs**
- **Add padding between view page return button and tabs**
- **Add padding between tabs and tab content**
- **Fix padding around public search results heading**
> Fix padding around tabs

- e2e/pages/alcs/applicant-info-page/parcels-section.ts
- e2e/pages/portal/parcels-page.ts
- e2e/playwright.config.ts
- Fixed the map area not being able to validate the text
- Fixed the calendar button falling out of viewport and failing to scroll
- Config changes: 
- retries for local environment 
- timeout and action timeout for stability
- number of workers to be 1 on local env
> Fix E2E Test for TUR Failing

- services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1719348665533-add_notification_trigger_statuses.ts
- **Set trigger status for notification email statuses**
- **Update existing data with SUBM trigger status**
> Fix notification trigger statuses

- alcs-frontend/package-lock.json
- portal-frontend/package-lock.json
- services/package-lock.json
Fixed the following packages:
- ALCS:
- braces -> HIGH Severity
- ws -> HIGH Severity
- ejs -> MODERATE 
- fill-range
- Portal:
- braces -> HIGH Severity
- ws -> HIGH Severity
- fill-range
- Services:
- braces -> HIGH Severity
-   @grpc/grpc-js
- @grpc/proto-loader
- fill-range
- s3-streamlogger
> Fix Package Vulnerabilities

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/application/documents/documents.component.html
- alcs-frontend/src/app/features/application/documents/documents.component.ts
- alcs-frontend/src/app/features/inquiry/documents/documents.component.html
- alcs-frontend/src/app/features/inquiry/documents/documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.html
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.ts
- alcs-frontend/src/app/features/notification/documents/documents.component.html
- alcs-frontend/src/app/features/notification/documents/documents.component.ts
- alcs-frontend/src/app/features/planning-review/decision/decision-documents/decision-documents.component.html
- alcs-frontend/src/app/features/planning-review/decision/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/planning-review/documents/documents.component.html
- alcs-frontend/src/app/features/planning-review/documents/documents.component.ts
- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.html
- alcs-frontend/src/app/features/planning-review/review/evidentiary-record/evidentiary-record.component.ts
- alcs-frontend/src/app/shared/application-document/application-document.component.html
- alcs-frontend/src/app/shared/application-document/application-document.component.ts
- alcs-frontend/src/app/shared/constants.ts
- alcs-frontend/src/app/shared/pipes/truncate.pipe.spec.ts
- alcs-frontend/src/app/shared/pipes/truncate.pipe.ts
- alcs-frontend/src/app/shared/shared.module.ts
- alcs-frontend/src/app/shared/utils/file.ts
- Fixed file extension issue for files that did not have file extensions
- Long File Names:
- Added truncate pipe to shorten long names
- Added truncate pipe to documents tables
> ALCS Documentation UI/UX Bugs

- alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.ts
- alcs-frontend/src/app/services/admin-local-government/admin-local-government.service.ts
- Fixed error on creating and updating L/FNG admin accounts
- Added toast on successful create/update of L/FNG accounts
> Fix Admin L/FNG Bugs

- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.html
- portal-frontend/src/app/features/applications/application-details/parcel/parcel.component.ts
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.scss
- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/parcel/parcel.component.ts
- portal-frontend/src/app/shared/mobile/parcel-owner-mobile-card/parcel-owner-mobile-card.component.html
- portal-frontend/src/app/shared/mobile/parcel-owner-mobile-card/parcel-owner-mobile-card.component.scss
- portal-frontend/src/app/shared/mobile/parcel-owner-mobile-card/parcel-owner-mobile-card.component.ts
- portal-frontend/src/app/shared/owner-dialogs/parcel-owners/parcel-owners.component.html
- portal-frontend/src/app/shared/owner-dialogs/parcel-owners/parcel-owners.component.scss
- portal-frontend/src/app/shared/owner-dialogs/parcel-owners/parcel-owners.component.ts
- portal-frontend/src/app/shared/shared.module.ts
- Added mobile card for fee simple and crown parcel types on "parcel details" (step 1) and "review and submit" (step 8) for applications and NOIs.
- Changed government contact from radio button to select menu
- Moved the government contact detail to match fee simple design
> Add Mobile Card for Parcel Details in Applications and NOIs

- alcs-frontend/package-lock.json
- e2e/package-lock.json
- portal-frontend/package-lock.json
- services/package-lock.json
Minor version update for the following projects:
- services
- alcs-frontend
- portal-frontend
- e2e
> Regular Dependencies Update

- alcs-frontend/src/app/services/decision-meeting/decision-meeting.service.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.html
- alcs-frontend/src/app/shared/details-header/details-header.component.spec.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.spec.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- **Add ability to highlight tile from query param**
- **Add go to card button**
- **Stop opening commissioner detail in new window**
- **Add option to get meetings by file number**
- **Only show go to card button when file has meetings in schedule**
> Add 'Go to card' button for Commissioners

- services/apps/alcs/src/providers/typeorm/migrations/1724368028724-missed_chase_inquiries_etl.ts
I foolishly left off a semicolon at the end of the queries within the conditional.
> Add missing semicolon

- services/apps/alcs/src/providers/typeorm/migrations/1724368028724-missed_chase_inquiries_etl.ts
Cherry-picked commit from #1832 to avoid deploying recent changes.
> Prevent `mime_type` from being null

- services/apps/alcs/src/providers/typeorm/migrations/1725902876425-fix_chase_document_upload_dates.ts
Was using ETL date instead of OATS upload date
> Fix document upload date

- alcs-frontend/src/app/features/application/lfng-info/return-application-dialog/return-application-dialog.component.scss
- portal-frontend/src/app/features/applications/review-submission/return-application-dialog/return-application-dialog.component.html
- portal-frontend/src/app/features/applications/review-submission/return-application-dialog/return-application-dialog.component.scss
- portal-frontend/src/app/features/applications/review-submission/return-application-dialog/return-application-dialog.component.ts
- **Make L/FNG return comment required**
- **Fix tiny font on comment inputs**
> Improve return app comment inputs

- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.ts
- Added Confirmation Dialog on deleting existing residences
- Added No Data text to existing residences mobile view
> Add Confirmation Dialog and UI Fixes to NARU Existing Residences

- alcs-frontend/src/app/features/application/application.module.ts
- alcs-frontend/src/app/features/application/proposal/proposal.component.html
- alcs-frontend/src/app/features/application/proposal/proposal.component.scss
- alcs-frontend/src/app/features/notice-of-intent/proposal/proposal.component.html
- alcs-frontend/src/app/features/notice-of-intent/proposal/proposal.component.scss
- Fix date picker value disappearing on selection in applications in ALC Intake tab
- Fix "Proposal ALR Area Impacted (ha)" field not showing "Add Amount" on empty values in Application/NOI prep tab
- Fix the space between "Staff Comments and Observations" header and text input field
> Field Bugs on ALC Intake and App/NOI Prep Pages

- alcs-frontend/src/app/shared/inline-editors/inline-textarea-edit/inline-textarea-edit.component.scss
Css changes to make components look the same, and aligned to the component below.
> ALCS-2138 Change component properties

- alcs-frontend/src/app/shared/inline-editors/inline-textarea-edit/inline-textarea-edit.component.scss
> ALCS-2138 Padding and font adjustment

- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- **Properly map true/false to yes/no**
- **Add no data text for missing fields**
> Fix ALCS NARU yes/no and no data text

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- **Rename structure types**
- **Relabel questions**
- **Add links to ALC policy**
> Improve wording of NOI additional info step

- alcs-frontend/src/app/shared/application-document/application-document.component.html
> ALC-2262 Remove truncate clause

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/add-structure-dialog/add-structure-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/add-structure-dialog/add-structure-dialog.component.scss
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/additional-information/additional-information.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.ts
This address some fixes found on ticket Q&A.
> Q & A Fixes

- alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/applications/application-details/naru-details/naru-details.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/public/application/submission/naru-details/naru-details.component.html
- portal-frontend/src/app/features/public/application/submission/naru-details/naru-details.component.scss
- portal-frontend/src/app/features/public/application/submission/naru-details/naru-details.component.ts
- 2316: Fix missing index numbers on residences on mobile and desktop view
- 2317: Add NARU residence mobile design to public view
> Add NARU Residence Mobile View in Public and Fix Missing Index Numbers

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.html
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.scss
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.ts
> ALCS-2224 Added warning to residential types

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/add-structure-dialog/add-structure-dialog.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/add-structure-dialog/add-structure-dialog.component.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.html
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.scss
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.ts
> ALCS-2229 validation fixes

- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.html
- portal-frontend/src/app/shared/mobile/structure-mobile-card/structure-mobile-card.component.scss
> ALCS-2229 Div tweak

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/additional-information/additional-information.component.ts
- portal-frontend/src/app/features/public/notice-of-intent/submission/additional-information/additional-information.component.ts
Added the host listener on:
- Additional Information
- Review
- Public view
> ALCS-2327 Added Host Listener detect mobile

- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.ts
- portal-frontend/src/app/features/public/application/submission/pfrs-details/pfrs-details.component.html
- portal-frontend/src/app/features/public/application/submission/pfrs-details/pfrs-details.component.ts
- portal-frontend/src/app/features/public/application/submission/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/public/application/submission/pofo-details/pofo-details.component.ts
- portal-frontend/src/app/features/public/application/submission/roso-details/roso-details.component.html
- portal-frontend/src/app/features/public/application/submission/roso-details/roso-details.component.ts
- **Fix various structures form state issues**
- **Show warning as soon as type changes**
- **Fix structures table padding**
- **Show residential warning for accessory structures**
- **Remove building plans from public view**
> 1156 QA fixes

- alcs-frontend/src/app/services/application/application-tag/application-tag.service.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.service.ts
- alcs-frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- alcs-frontend/src/app/shared/tags/tags-header/tags-header.component.html
- alcs-frontend/src/app/shared/tags/tags-header/tags-header.component.ts
- services/apps/alcs/src/alcs/application/application-tag/application-tag.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.service.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.service.ts
- Fix tags header border behaviour: The border should disappear once user has selected a tag and clicks on another component
- Make tag name bold on confirmation dialog when deleting a tag from application/NOI
- Hide inactive tags from user for selecting in applications and NOIs
> QA Fixes: 472-2213

- services/apps/alcs/src/alcs/application/application-tag/application-tag.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- **Add app tag check function**
- **Conditionally add tags based on NARU answers**
> Conditionally apply tags based on NARU answers

- alcs-frontend/.eslintrc.json
- alcs-frontend/src/app/features/search/search.component.html
> ALCS-1874 Review fixes

- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.entity.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
- Add tags to NOIs once submitted to ALC based on structure types and area-wide filling question
- Deprecated populateNoiSubtype function
> Add Tags to NOIs Once Submitted Instead of Subtypes

- alcs-frontend/src/app/features/search/search.component.ts
- services/apps/alcs/src/utils/search/application-search-filters.ts
- services/apps/alcs/src/utils/search/notice-of-intent-search-filters.ts
- Added AND logic for tag search (added relational division in SQL)
- Remove space while selecting tags (so search after pressing enter works)
> ALCS-1874 QA fixes

- alcs-frontend/src/app/features/admin/tag/tag-category/tag-category-dialog/tag-category-dialog.component.html
- alcs-frontend/src/app/features/admin/tag/tag-category/tag-category-dialog/tag-category-dialog.component.ts
- alcs-frontend/src/app/features/admin/tag/tag-dialog/tag-dialog.component.html
- alcs-frontend/src/app/features/admin/tag/tag-dialog/tag-dialog.component.ts
- alcs-frontend/src/app/services/tag/tag-category/tag-category.service.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.controller.spec.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.controller.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.entity.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.service.spec.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.service.ts
- services/apps/alcs/src/alcs/tag/tag.controller.spec.ts
- services/apps/alcs/src/alcs/tag/tag.controller.ts
- services/apps/alcs/src/alcs/tag/tag.dto.ts
- services/apps/alcs/src/alcs/tag/tag.entity.ts
- services/apps/alcs/src/alcs/tag/tag.service.spec.ts
- services/apps/alcs/src/alcs/tag/tag.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1730856145155-remove_unique_constraints.ts
- services/package.json
This handles the tickets:
- ALCS-2353 - Cannot Create a Tag with Same Name After Deletion & Form Issue
- ALCS-2352 - Exposing DB information on Client Side
- ALCS-2354 - Cannot Delete a Category That Had Tags Associated With
> ALCS-2353 Constraints end error handling

- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.ts
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.ts
- **Undo previous fix adding warning to accessory structures**
- **Fix type mobile switching not updating conditional fields properly**
- **Fix various field state issues**
- **Make structure type counts more reliable**
- **Fix issue with mobile structure type not reflecting on desktop**
> 1156 QA fixes 2

- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/pofo-proposal/pofo-proposal.component.scss
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.scss
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.scss
Remove <td> borders when there is a residential warning.
> ALCS-2350 Remove borders when there is a residential warning

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- **Clear structures array on NOI changes**
- **Clarify result**
> Fix weird building plans behaviour

- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
- **Set structure type form control value when updating type**
- **Patch form after structure questions visibility has been set**
- **Explicitly set return type of `addControl`**
> Fix NOI structure questions disappearing

- portal-frontend/src/app/features/public/application/submission/pofo-details/pofo-details.component.html
- portal-frontend/src/app/features/public/application/submission/roso-details/roso-details.component.html
- **Show 'what steps...' question on 'No' instead of 'Yes'**
- **Move "what alternative..." question inside structures check**
> Fix S&F app public search visibility issues

- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/residence-dialog/residence-dialog.component.html
- portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/residence-dialog/residence-dialog.component.scss
> ALCS-2379 Naru text changes

- portal-frontend/src/app/features/home/inbox/inbox-table/inbox-table.component.ts
The table type was comparing with wrong strings.
Fixed so all the pagination methods are correctly called.
> ALCS-2389 Fix table change method call

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts
- alcs-frontend/src/app/features/application/decision/conditions/conditions.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.entity.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1732149522844-remove_superseded_date.ts
Remove superseded field from conditions
> ALCS-2060 Remove superseded field from conditions

- alcs-frontend/src/app/features/admin/admin.component.ts
- alcs-frontend/src/app/features/admin/admin.module.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-container.component.html
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-container.component.scss
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-container.component.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.spec.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types.component.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-dialog-data.interface.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent-decision-condition-types/notice-of-intent-decision-condition-types.service.spec.ts
- alcs-frontend/src/app/services/notice-of-intent/notice-of-intent-decision-condition-types/notice-of-intent-decision-condition-types.service.ts
- services/apps/alcs/src/alcs/admin/admin.module.ts
- services/apps/alcs/src/alcs/admin/notice-of-intent-decision-condition-types/notice-of-intent-decision-condition-types.controller.spec.ts
- services/apps/alcs/src/alcs/admin/notice-of-intent-decision-condition-types/notice-of-intent-decision-condition-types.controller.ts
- services/apps/alcs/src/alcs/admin/notice-of-intent-decision-condition-types/notice-of-intent-decision-condition-types.service.ts
Implement  NOI Decision Condition type on admin.
> ALCS-2302 Implement NOI decision type into admin

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.html
> ALCS-2074 Approval Dependent UI removal

- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.html
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
- services/apps/alcs/src/alcs/admin/application-decision-condition-types/application-decision-condition-types.service.ts
- services/apps/alcs/src/alcs/admin/notice-of-intent-decision-condition-types/notice-of-intent-decision-condition-types.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.dto.ts
- Disable the code field on edit mode
- Remove zero value on conditions without admin fee
> QA Fix: Fix Application and NOIs Decision Condition Type Bugs

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/services/application/application-decision-condition-types/application-decision-condition-types.service.ts
- **Fix undefined app component name**
- **Apply same change to NOI's**
- **Add success toast when deleting condition types**
> 2322 QA Fixes

- services/apps/alcs/src/providers/typeorm/migrations/1733957637664-migrate_components_to_decisions.ts
> ALCS-2099 Delete Migration and create a new one

- services/apps/alcs/src/providers/typeorm/migrations/1734024626850-fix_condition_type_date_field.ts
Fix for the field is_single_date_checked to is_date_checked
> ALCS-2092 Fix the data field name

- portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html
- portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html
The filed is already saving the right amount of decimals on DB.
- Fixed the NOI input field
- Added user hints on NOI and Application
> ALCS-2332 Added 5 decimal places validation and user hint

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-date/application-decision-condition-date.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-date/notice-of-intent-decision-condition-date.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1734395224473-clean_up_orphaned_condition_dates.ts
- services/apps/alcs/src/providers/typeorm/migrations/1734395531473-make_condition_date_condition_uuid_not_nullable.ts
- **Delete newly orphaned condition dates**
- **Clean up orphaned condition dates**
- **Make condition UUID not nullable to prevent orphaned dates**
> Fix date saving issues

- alcs-frontend/src/app/features/application/decision/conditions/conditions.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.html
- services/apps/alcs/src/providers/typeorm/migrations/1734394698009-fix_condition_status_function.ts
- Ui Fixes
- Function logic changes
> ALCS1858 Ui Fixes and Function logic changes

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/nfu-input/nfu-input.component.html
Non Farm use component date removal and layout adjustments.
> Remove date from Non Farm Use

- services/apps/alcs/src/providers/typeorm/migrations/1734465908479-fix_expired_condition.ts
Change expiry comparison from <= to just <
Compare only date portions truncating the time.
> ALCS-1850 Change expiry comparision and compare only date portions

- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.html
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
Added validation to existing admin fees and security amounts.
> ALCS-2431 Validate Admin fee and security amount

- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.html
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
- Prevents validation flash using isLoading state while fetching
- Sets admin fee to null on submit if unchecked
> ALCS-2431 Prevents validation flash

- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.html
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
Set single date as default when the date is not checked and set.
> ALCS-2446 Set single date as default if date is not checked

- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.ts
Added next year on menu dropdown
> ALCS-2416 Include next year in dropdown list

- services/apps/alcs/src/alcs/search/search.controller.ts
Fixed the controller setting the status searches with the right role.
> ALCS-2422 Fix the controllers with the correct role

- services/apps/alcs/src/providers/typeorm/migrations/1734644882049-create_bond_conditions_where_missing.ts
- services/apps/alcs/src/providers/typeorm/migrations/1734645250139-nullify_security_amounts_for_non_bond_conditions.ts
- services/apps/alcs/src/providers/typeorm/migrations/1734646226612-disable_security_amount_for_all_non_bond_condition_types.ts
- services/apps/alcs/src/providers/typeorm/migrations/1734646507149-enable_required_secuity_amount_for_bond_condition_type.ts
- **Add missing bond conditions**
- **Clear all non-bond security amounts**
- **Disable security amount for non-bond condition types**
- **Enable required security amount for bond condition type**
> Move all security amounts to bond conditions

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.html
Added the missing field to the missing types:
- COMPONENT_TYPE.TURP
- COMPONENT_TYPE.COVE
- COMPONENT_TYPE.SUBD
> ALCS-2449 HOTFIX - Added ALR field to the 3 missing types

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.html
> ALCS-2449 Merge into develop

- alcs-frontend/src/app/features/commissioner/application/commissioner-application.component.html
- alcs-frontend/src/app/features/commissioner/application/commissioner-application.component.spec.ts
- alcs-frontend/src/app/features/commissioner/application/commissioner-application.component.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.html
- alcs-frontend/src/app/shared/shared.module.ts
- alcs-frontend/src/app/shared/tags/commissioner-tags-header/commissioner-tags-header.component.html
- alcs-frontend/src/app/shared/tags/commissioner-tags-header/commissioner-tags-header.component.scss
- alcs-frontend/src/app/shared/tags/commissioner-tags-header/commissioner-tags-header.component.spec.ts
- alcs-frontend/src/app/shared/tags/commissioner-tags-header/commissioner-tags-header.component.ts
- alcs-frontend/src/app/shared/tags/tag-chip/tag-chip.component.html
- alcs-frontend/src/app/shared/tags/tag-chip/tag-chip.component.scss
- alcs-frontend/src/app/shared/tags/tag-chip/tag-chip.component.ts
- alcs-frontend/src/app/shared/tags/tags-header/tags-header.component.ts
- services/apps/alcs/src/alcs/application/application-tag/application-tag.controller.ts
- services/apps/alcs/src/alcs/tag/tag-category/tag-category.controller.ts
- services/apps/alcs/src/alcs/tag/tag.controller.ts
- Add tags to the application header on commissioner's view
- Fix tag and tag category fetch error on commissioner advanced search
- Add application status pill to commissioner's view
> Add Tags and File Status to Commissioner View

- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.html
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types.component.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-dialog-data.interface.ts
- alcs-frontend/src/app/shared/validators/code-exists-validator.ts
> ALCS-2453 Handle unique descriptions on condition types

- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts
- alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types.component.ts
> ALCS-2451 Allow to remove check box if the value is zero

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts
- alcs-frontend/src/app/shared/utils/decision-methods.ts
> ALCS-2059 QA fixes

- alcs-frontend/src/app/features/search/application-search-table/application-search-table.component.ts
- alcs-frontend/src/app/features/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts
- alcs-frontend/src/app/shared/header/search-bar/search-bar.component.ts
Navigate to conditions tab according to status on advanced and quick search.
> ALCS-2426 Added navigation according to status on search

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
> ALCS-2059 Ui Fixes

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.ts
> ALCS-2474 Fix single date updates

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
> ALCS-2059 Alignment fix

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.html
> ALCS-2447 Change icon color

- alcs-frontend/src/app/services/search/file-type/file-type-data-source.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1737402613673-turp_label_fix.ts
- services/templates/emails/submitted-to-alc/tur-applicant.template.ts
Migration to change TURP component label and description.
Fixes on adv search structure labels.
> ALCS-2360 Migration and label fixes

- alcs-frontend/src/app/features/application/application.component.html
- alcs-frontend/src/app/features/application/application.component.spec.ts
- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.html
- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.scss
- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/toast/toast.service.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- Add "Go to Condition" to the card dropdown in the header
- Add 'GO TO BOARD' to toast service after creating a condition card
- Add status pills to the condition card in the "Application Condition Board"
- Fix Tooltip not showing on disabled conditions
- Add decision order to the condition card dialog
> Application Condition Card UI/UX features

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts
> ALCS-2478 Allow to add a new date on conditions component

- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- Fix application condition board cards drag and drop bug not working
- Show all conditions only when editing the card
- Show the error color on the table border and checkbox color when no condition is selected
- Disabled checkbox for conditions already in use by other cards
- Add 'No Data' text to conditions without End/Due date value
> QA Fixes #1: 1871

- services/apps/alcs/src/providers/typeorm/migrations/1737585042507-adding_date_to_noi_conditions.ts
Same script used for applications, but on NOIs now.
Applications were already tested and validated by Nowshin.
> ALCS-2478 Add dates to NOI conditions

- services/apps/alcs/src/providers/typeorm/migrations/1737585042507-adding_date_to_noi_conditions.ts
> ALCS-2478 Created Script

- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
A hard to find issue ...
But, when we were duplicating a condition the dates were kept with the exact same properties, including the UUID.
So when saving the new condition the dates were updated to the new condition, leaving the old condition without dates.
The fix itself was pretty easy:
```typescript
condition.dates = condition.dates?.map((d) => {
return new ApplicationDecisionConditionDate({
...d,
uuid: undefined,
});
});
```
For the copied dates, I just set the UUID to undefined, and this would make typeorm create a new date row, instead of update the old one.
The same fix was also applied to NOIs.
> ALCS-2478 Create new dates when duplicating conditions

- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
Forgot to apply last fix (#2083) to NOI's
> 2226 QA #2: Apply draft button fix to NOI's

- alcs-frontend/src/app/features/admin/unarchive/unarchive.component.ts
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.scss
- services/apps/alcs/src/alcs/admin/unarchive-card/unarchive-card.service.spec.ts
- services/apps/alcs/src/alcs/admin/unarchive-card/unarchive-card.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/board/board.service.ts
- services/apps/alcs/src/alcs/card/card.module.ts
- services/apps/alcs/src/alcs/card/card.service.spec.ts
- services/apps/alcs/src/alcs/card/card.service.ts
- Disassociate conditions when the relevant condition card is archived
- Update conditions table design when the card is unarchived
> Archive and Unarchive Application Decision Condition Cards

- portal-frontend/src/app/features/public/notice-of-intent/alc-review/submission-documents/submission-documents.component.ts
Just applying same change as #2092 to NOI's
> 2448: Apply public search sorting fix to NOI's

- services/apps/alcs/src/alcs/board/board.controller.spec.ts
- services/apps/alcs/src/alcs/board/board.controller.ts
- services/apps/alcs/src/alcs/board/board.service.ts
- services/apps/alcs/src/alcs/card/card-type/card-type.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.module.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-modification/notice-of-intent-modification.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-modification/notice-of-intent-modification.service.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1738277452499-create_noi_conditions_board_and_columns.ts
- services/apps/alcs/src/providers/typeorm/migrations/1738278602878-add_noi_condition_card_type.ts
- services/apps/alcs/src/providers/typeorm/migrations/1738278849708-add_noi_decision_condition_card.ts
NOI Condition Cards backend functionalities:
- NOI Condition Card entity, DTO, service, controller
- Add NOI condition card to relevant services, including card and board
- Migrations for creating new NOI conditions board, card type, and new NOI condition card entity
> NOI Condition Cards - Backend

- portal-frontend/src/app/services/application-submission-review/application-submission-review.service.ts
- portal-frontend/src/app/services/application-submission/application-submission.service.ts
- portal-frontend/src/app/services/notice-of-intent-submission/notice-of-intent-submission.service.ts
- portal-frontend/src/app/services/notification-submission/notification-submission.service.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.spec.ts
- services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts
- services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts
- services/apps/alcs/src/portal/notification-submission/notification-submission.controller.ts
- Applies to apps, NOI's SRW's
- Also update message with more detail
> Throw error if correct documents failed to generate and attach

- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/application/application-decision-meeting/application-decision-meeting.service.spec.ts
- services/apps/alcs/src/alcs/application/application-decision-meeting/application-decision-meeting.service.ts
- services/apps/alcs/src/alcs/application/application.module.ts
- services/apps/alcs/src/alcs/meetings/decision-meeting.controller.spec.ts
- services/apps/alcs/src/alcs/meetings/decision-meeting.controller.ts
- services/apps/alcs/src/providers/typeorm/migrations/1738089637628-turn_off_application_condition_board_show_on_schedule.ts
- services/apps/alcs/src/providers/typeorm/migrations/1738196945240-remove_application_card_type_from_condition_board.ts
- services/apps/alcs/test/mocks/mockEntities.ts
- Add application decision condition cards to the commissioner schedule's meetings
- Remove the application conditions board from commissioner's view
> QA Fixes #2: 2406

- alcs-frontend/src/app/features/board/board.component.spec.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/board.module.ts
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent-decision-condition-dialog/notice-of-intent-decision-condition-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent-decision-condition-dialog/notice-of-intent-decision-condition-dialog.component.scss
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent-decision-condition-dialog/notice-of-intent-decision-condition-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition-card-dialog/condition-card-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition-card-dialog/condition-card-dialog.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition-card-dialog/condition-card-dialog.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition-card-dialog/condition-card-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision.module.ts
- alcs-frontend/src/app/features/notice-of-intent/notice-of-intent.component.html
- alcs-frontend/src/app/features/notice-of-intent/notice-of-intent.component.spec.ts
- alcs-frontend/src/app/features/notice-of-intent/notice-of-intent.component.ts
- alcs-frontend/src/app/services/board/board.dto.ts
- alcs-frontend/src/app/services/board/board.service.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.spec.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision-v2.service.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts
- alcs-frontend/src/app/shared/card/card.component.html
- alcs-frontend/src/app/shared/card/card.component.scss
- alcs-frontend/src/app/shared/card/card.component.ts
- alcs-frontend/src/app/shared/details-header/details-header.component.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.dto.ts
- Add NOI Condition card frontend component, services, and DTOs.
- Add NOI condition card to the board
- Update tests
> NOI Condition Card Frontend Component

- portal-frontend/src/app/features/login/login.component.spec.ts
- portal-frontend/src/app/features/login/login.component.ts
- services/apps/alcs/src/common/authorization/authorization.controller.ts
This does not necessarily resolve 2509, but is an important step.
- **Always redirect to frontend after login**
- **Toast on login when query param present**
> 2509: Redirect on login failures

- alcs-frontend/src/app/features/admin/unarchive/unarchive.component.ts
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent-decision-condition-dialog/notice-of-intent-decision-condition-dialog.component.html
- services/apps/alcs/src/alcs/admin/unarchive-card/unarchive-card.service.spec.ts
- services/apps/alcs/src/alcs/admin/unarchive-card/unarchive-card.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/card/card.module.ts
- services/apps/alcs/src/alcs/card/card.service.spec.ts
- services/apps/alcs/src/alcs/card/card.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.module.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
- Add archive and unarchive feature to notice of intent condition cards
- Exclude application condition cards with deleted decision in archived cards list
> Archive/Unarchive for NOI Condition Cards

- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
Fix delete method with condition cards
> ALCS-2468 Fix delete with cards

- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
Clear array before saving the object.
> ALCS-2468 Clear conditions array

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-date/application-decision-condition-date.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-date/notice-of-intent-decision-condition-date.service.ts
- **Create single date if single date and missing
- On loading condition view, create a date if none exist
- Applies to apps, NOI's
- Backend service now allows for creating a single date 
- Added an error if trying to create a date on a condition that doesn't   allow it.**
- **Fix runtime errors from missing decision**
- **Fix condition card display issue when date missing**
> 2523: Fix view condition and condition card display issues

- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.interface.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.spec.ts
- services/apps/alcs/src/alcs/application/application-document/application-document.service.ts
- services/apps/alcs/src/alcs/inquiry/inquiry-document/inquiry-document.service.spec.ts
- services/apps/alcs/src/alcs/inquiry/inquiry-document/inquiry-document.service.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-document/notice-of-intent-document.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-document/notice-of-intent-document.service.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.service.spec.ts
- services/apps/alcs/src/alcs/notification/notification-document/notification-document.service.ts
- services/apps/alcs/src/alcs/planning-review/planning-review-document/planning-review-document.service.spec.ts
- services/apps/alcs/src/alcs/planning-review/planning-review-document/planning-review-document.service.ts
- **Fix documents duplicating on replace file**
- **Filter file documents missing document fields**
- Applies to apps, NOI's, notifications, PR's, and inquiries
> 2495, 2521: Fix duplicate docs being create and soft deleted docs crashing documents page

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/application/documents/documents.component.ts
- alcs-frontend/src/app/features/inquiry/documents/documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.ts
- alcs-frontend/src/app/features/notification/documents/documents.component.ts
- alcs-frontend/src/app/features/planning-review/decision/decision-documents/decision-documents.component.ts
- alcs-frontend/src/app/features/planning-review/documents/documents.component.ts
- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.ts
- **Make file edit configurable by doc type**
- **Fix inquiries' documents not editable**
- **Update doc type after editing documents**
> 2529: Fix several ALCS upload dialog-related bugs

- alcs-frontend/src/app/features/application/documents/documents.component.html
- alcs-frontend/src/app/features/application/documents/documents.component.scss
- alcs-frontend/src/app/features/application/documents/documents.component.ts
- alcs-frontend/src/app/features/inquiry/documents/documents.component.html
- alcs-frontend/src/app/features/inquiry/documents/documents.component.scss
- alcs-frontend/src/app/features/inquiry/documents/documents.component.ts
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.html
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.scss
- alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.ts
- alcs-frontend/src/app/features/notification/documents/documents.component.html
- alcs-frontend/src/app/features/notification/documents/documents.component.scss
- alcs-frontend/src/app/features/notification/documents/documents.component.ts
- alcs-frontend/src/app/features/planning-review/documents/documents.component.html
- alcs-frontend/src/app/features/planning-review/documents/documents.component.scss
- alcs-frontend/src/app/features/planning-review/documents/documents.component.ts
- Applies to apps, NOI's, notifications, PR's, inquiries
- Make action buttons smaller
- Make actions column smaller
- Remove truncation of file name
- Make source to first column
> 2440: Improve documents tables

- alcs-frontend/src/app/features/home/assigned/assigned.component.spec.ts
- alcs-frontend/src/app/features/home/assigned/assigned.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/home/home.service.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
- services/apps/alcs/src/alcs/home/home.controller.spec.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/home/home.module.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
Implementation on NOI home page cards.
And some small application cards fixes.
> ALCS-2504 Nois Home Page cards implementation

- alcs-frontend/src/app/features/home/subtask/subtask.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
- services/apps/alcs/src/alcs/home/home.controller.spec.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
Condition subtasks cards for Application and NOIs.
> ALCS-2081 Added condition subtasks cards

- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.html
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.scss
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.ts
- alcs-frontend/src/app/services/card/card-subtask/card-subtask.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
- services/apps/alcs/src/alcs/card/card-subtask/card-subtask.dto.ts
- services/apps/alcs/src/alcs/home/home.controller.spec.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
> ALCS-2081 Implemented subtasks pills

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
Remove active days for conditions and conditions subtasks, as defined on a breakout with Ansley and Nowshin.
> ALCS-2081 Remove active days for conditions and conditions subtasks

- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.html
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.scss
- alcs-frontend/src/app/features/application/boundary-amendment/edit-boundary-amendment-dialog/edit-boundary-amendment-dialog.component.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
Added UUID read only input and copy to clipboard functionality
(Did a minor cleanup of a previous PR ...)
> ALCS-2433 Copy amendment uuid

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.ts
Show modification and reconsideration pills on application and NOI condition cards when the file has modification or reconsideration request instead of the decision
> Hotfix: Fix modification and reconsideration pills on condition cards

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-card/notice-of-intent-decision-condition-card.service.ts
Show modification and reconsideration pills on application and NOI condition cards when the file has modification or reconsideration request instead of the decision
> Backport Hotfix: Fix modification and reconsideration pills on condition cards

- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
- services/apps/alcs/src/alcs/home/home.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
Get MODI and RECON pills based on app or noi file number for conditions and subtasks.
> ALCS-2560 Change the search to APP/NOI File number

- alcs-frontend/src/app/features/application/application.component.ts
- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.scss
- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-condition/application-decision-condition-financial-instrument/application-decision-condition-financial-instrument.dto.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-condition/application-decision-condition-financial-instrument/application-decision-condition-financial-instrument.service.spec.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-condition/application-decision-condition-financial-instrument/application-decision-condition-financial-instrument.service.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/common/decision-condition-financial-instrument/decision-condition-financial-instrument.dto.ts
- alcs-frontend/src/app/services/common/decision-condition-financial-instrument/decision-condition-financial-instrument.service.ts
- alcs-frontend/src/app/shared/constants.ts
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument-dialog/decision-condition-financial-instrument-dialog.component.html
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument-dialog/decision-condition-financial-instrument-dialog.component.scss
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument-dialog/decision-condition-financial-instrument-dialog.component.spec.ts
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument-dialog/decision-condition-financial-instrument-dialog.component.ts
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument.component.html
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument.component.scss
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument.component.spec.ts
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument.component.ts
- alcs-frontend/src/app/shared/shared.module.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-financial-instrument/application-decision-condition-financial-instrument.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-financial-instrument/application-decision-condition-financial-instrument.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.controller.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.controller.ts
- Frontend components for application financial instruments
- Instruments table
- Instrument Add/Edit dialog
- Change soft delete to hard delete on the backend
> 542-2535: Applications Financial Instruments Frontend Components

- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.ts
- alcs-frontend/src/app/shared/constants.ts
> ALCS-2550: Backport

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
> ALCS-2553 UI fixes

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-component/basic/basic.component.html
> ALCS-2470 Bold ALR Area Impacted

- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.ts
- alcs-frontend/src/app/features/notice-of-intent/notice-of-intent.component.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.service.spec.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.service.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts
- alcs-frontend/src/app/shared/decision-condition-financial-instrument/decision-condition-financial-instrument.component.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.service.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.controller.spec.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.controller.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.entity.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.module.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
- services/apps/alcs/src/providers/typeorm/migrations/1740529203706-add_notice_of_intent_condition_financial_instrument.ts
- services/apps/alcs/test/mocks/mockEntities.ts
- Add frontend and backend components for NOI decision condition financial instruments
- Fix financial instrument common table's status column rendering received date instead of status date
> ALCS-2078: NOI Decision Condition Financial Instrument

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition-order-dialog/decision-condition-order-dialog.component.spec.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition-order-dialog/decision-condition-order-dialog.component.ts
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts
QA changes:
- Add the new condition at the bottom of the array
- Work with a copy of the array on order dialog and only apply to original array, if the save button is clicked
> Feature/alcs 2029 sort conditions qa#1

- alcs-frontend/src/app/features/board/dialogs/app-modification/app-modification-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/noi-modification/noi-modification-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/reconsiderations/reconsideration-dialog.component.html
Redirect to the decision tab by clicking on the "VIEW DETAIL" button for:
- Application modification and reconsideration cards
- NOI modification cards
> ALCS-2548: Redirect to decision tab for modification and reconsideration cards

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition-order-dialog/decision-condition-order-dialog.component.ts
Improve the sort logic from move items, and send to bottom just like Send to top was improved.
No more switching between rows, just rearranging after drop.
> ALCS-2029 Improve sort logic

- alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.ts
The change applies for applications and NOIs
> Add confirmation dialog for deleting dates in multiple date conditions

- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.html
- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.ts
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html
- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts
Implemented the alpha index on the conditions card
- If there's no order recorded, suppress the index
Fix was made while adding a new condition to record the current order.
> ALCS-2576 Implement alpha index on condition card

- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.html
- alcs-frontend/src/app/features/application/decision/conditions/condition-card-dialog/condition-card-dialog.component.ts
Remove index column and concatenate with the Condition name
> ALCS-2576 UI tweaks

- alcs-frontend/src/app/features/board/dialogs/card-dialog/card-dialog.component.ts
- alcs-frontend/src/app/features/home/subtask/subtask-table/subtask-table.component.ts
- alcs-frontend/src/app/services/user/user.dto.ts
- services/apps/alcs/src/common/authorization/authorization.service.spec.ts
- services/apps/alcs/src/common/authorization/authorization.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1741219585820-make_user_email_nullable.ts
- services/apps/alcs/src/user/user.dto.ts
- services/apps/alcs/src/user/user.entity.ts
- Make user email column nullable
- Make all user email DTO fields optional
- Disable subtask email filtering when email absent
- Check for email before sending new user request email
> ALCS-2522: Make user email optional

- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/shared/card/card.component.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.spec.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision-v2.module.ts
Show next decision meeting banner on application condition card when it is on "Ready for review sent / Going to next review discussion" column and not in "Application Conditions" board.
> Add Decision Meeting Banner to Application Condition Card

- portal-frontend/src/app/features/applications/view-submission/lfng-review/lfng-review.component.html
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.html
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.scss
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.ts
Move Start/Continue Application button outside the tabs, and add Return Application button
> ALCS-2528 Add Return Application button

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.ts
Sort condition pills on Apps and NOIs summary.
> ALCS-2460 Sort condition pills on summary

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.ts
Clear resolution number on changing the year.
> ALCS-2561 Clear resolution number on change

- alcs-frontend/src/app/features/search/search.component.ts
- alcs-frontend/src/app/shared/tags/tags-header/tags-header.component.ts
- **Filter tags by category in search**
- **Filter tags by category when adding tags**
> ALCS-2356: Filter tags by category when when adding tags and in advanced search

- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.html
- alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/release-dialog/release-dialog.component.html
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/release-dialog/release-dialog.component.scss
> ALCS-2562 Ui fixes

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/application/post-decision/post-decision.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/notice-of-intent/post-decision/post-decision.component.ts
- alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
- alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts
- services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision.dto.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
- services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.dto.ts
- services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts
- services/apps/alcs/src/common/automapper/notice-of-intent-decision.automapper.profile.ts
- Applies to applications and NOIs
- Add canBeDeleted field to application and NOI decision DTO
- refactor post decision components to refresh reconsiderations and modifications
> ALCS-881 QA #1: Fix user being able to delete mid chain decision after revert to draft

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.scss
Apply to applications and NOIs
> ALCS-2628: Fix paused and active days numbers misalignment on decision

- alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts
- alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.ts
> ALCS-2645 Added index on delete dialog

- alcs-frontend/src/app/features/search/search.component.ts
- alcs-frontend/src/app/services/search/decision-outcome/decision-outcome-data-source.service.ts
Remove NOI outcome from commissioner view on advanced search
> ALCS-2606 Remove NOI outcome from commissioner

- services/apps/alcs/src/providers/typeorm/migrations/1743115625509-change-soil-badges.ts
Migration to rename and change pills colors.
> ALCS-2225 Badges new labels and colors

- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.html
- portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.scss
Display the return button when the statuses are:
- IN_REVIEW_BY_LG
- RETURNED_TO_LG
- SUBMITTED_TO_LG
But disable and show tooltip if it is:
- SUBMITTED_TO_LG
> ALCS-2657 Added disable behavior on incorrect status

- alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts
Make sure the conditions are displayed on correct order on cards.
> ALCS-2652 Fix card order

- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.html
- alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.ts
- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/board.component.scss
- alcs-frontend/src/app/features/board/board.component.spec.ts
- alcs-frontend/src/app/features/board/board.component.ts
- alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.spec.ts
- alcs-frontend/src/app/features/board/dialogs/notification/notification-dialog.component.spec.ts
- alcs-frontend/src/app/services/admin-board-management/admin-board-management.service.spec.ts
- alcs-frontend/src/app/services/board/board.dto.ts
- alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.spec.ts
- services/apps/alcs/src/alcs/admin/board-management/board-management.controller.spec.ts
- services/apps/alcs/src/alcs/board/board.dto.ts
- services/apps/alcs/src/alcs/board/board.entity.ts
- services/apps/alcs/src/alcs/board/board.service.spec.ts
- services/apps/alcs/src/alcs/board/board.service.ts
- services/apps/alcs/src/providers/typeorm/migrations/1744385539178-add_assignee_filter_option_to_boards.ts
- services/apps/alcs/src/providers/typeorm/migrations/1744386506472-set_initial_board_assignee_filter_option_values.ts
- **Add hasAssigneeFilter flag to boards**
- **Set hasAssigneeFilter default for current boards**
- **Add filter UI to boards**
> Add assignee filter to boards

- alcs-frontend/src/app/features/board/board.component.html
- alcs-frontend/src/app/features/board/board.component.scss
- alcs-frontend/src/app/features/board/board.component.ts
- Replace 'Last, First' (`name` property) with 'First Last' (`prettyName` property)
- Layout create card button to the right of the assignee filter
> 2276 QA #1: Use pretty name (first + last) and layout filter and create card button

- portal-frontend/src/app/features/applications/application-details/application-details.component.html
- portal-frontend/src/app/features/applications/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.html
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/public/application/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/public/notice-of-intent/alc-review/submission-documents/submission-documents.component.html
- portal-frontend/src/app/features/public/notification/alc-review/submission-documents/submission-documents.component.html
- **Fix using wrong UUID**
- **Handle optional attachment clicks**
> QA #1 fixes for public/portal doc

- portal-frontend/src/app/features/applications/edit-submission/other-attachments/other-attachments.component.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/notice-of-intents/view-submission/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/notifications/view-submission/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/public/application/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/public/application/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/public/notice-of-intent/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/public/notice-of-intent/alc-review/submission-documents/submission-documents.component.ts
- portal-frontend/src/app/features/public/notification/alc-review/submission-documents/submission-documents.component.spec.ts
- portal-frontend/src/app/features/public/notification/alc-review/submission-documents/submission-documents.component.ts
- **Clean up stray debug log**
- **Fix additional bugs**
> QA #2 public/portal document fixes

- services/apps/alcs/src/alcs/alcs.module.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.automapper.profile.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.controller.spec.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.controller.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.entity.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.module.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.service.spec.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.service.ts
- services/apps/alcs/src/common/authorization/roles.ts
- services/apps/alcs/src/providers/typeorm/migrations/1747847477738-create_c_and_e_entity.ts
- **Set up DB table, backend service and controller**
- **Write tests for compliance backend**
> Set up C&E backend: DB table, service, controller

- services/apps/alcs/src/main.ts
- services/apps/alcs/src/s3-logger/s3-logger.ts
- services/package-lock.json
- services/package.json
- This replaces s3-streamlogger with a custom made `WritableStream`
> Remove s3-streamlogger to resolve dependency issues introduced fixing security vulnerabilities

- e2e/pages/portal/parcels-page.ts
Apparently this is a high risk security vulnerability
> Fix incorrectly escaped whitespace character

- alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/documents/document.dto.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/documents/document.service.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/property/property.dto.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/property/property.service.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/responsible-parties/responsible-parties.dto.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/responsible-parties/responsible-parties.service.ts
- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.ts
- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.interface.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.controller.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.entity.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.service.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.automapper.profile.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.controller.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.entity.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.service.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/responsible-parties/responsible-parties.automapper.profile.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/responsible-parties/responsible-parties.controller.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/responsible-parties/responsible-parties.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/responsible-parties/responsible-parties.service.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/responsible-parties/responsible-party.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1753915081494-add_ownership_section_option_to_c_and_e_docs.ts
- services/apps/alcs/src/providers/typeorm/migrations/1753980437474-add_certificate_of_title_to_c_and_e_properties.ts
- services/apps/alcs/src/providers/typeorm/migrations/1754453090029-add_corporate_summary_to_responsible_paries.ts
- Update responsible parties to meet interface reqs for upload dialog/document list
- Add certificate of title to properties
- Add corporate summary to responsible parties
- Update C&E docs to accept property and responsible party
- Add new section for ownership docs to draft
- Integrate updated docs component into new section
> Add new C&E ownership docs draft form section, adapt documents/component to this section

- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.module.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/header/details-header.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/header/details-header.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/header/details-header.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/header/details-header.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/overview/details-overview.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/overview/details-overview.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/overview/details-overview.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/overview/details-overview.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/compliance-and-enforcement.dto.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/compliance-and-enforcement.service.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/property/property.dto.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/property/property.service.ts
- alcs-frontend/src/styles/colors.scss
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.automapper.profile.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.controller.spec.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.controller.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.service.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1755105193848-relate_gov_to_c_and_e_property.ts
- Add status functionality to frontend service
- Allow getting property with C&E file
- Relate local government to property
- Add ability to update C&E file by UUID or file number
- Create details overview page component
- Create details header component
- Create parent C&E details component
> Create C&E header and overview tab from submission

- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/complaint-referral.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/property/property.service.ts
- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.html
- alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.interface.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/property/property.controller.ts
- Make a fixed property configurable in upload component
- Auto-assign property for COT
> 2395 QA 1: Auto-assign property to COT

- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.module.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/complaint-referral.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/complaint-referral.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/complaint-referral.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/complaint-referral.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/overview/overview.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/overview/overview.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/submitters/add-submitter-dialog/add-submitter-dialog.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/submitters/add-submitter-dialog/add-submitter-dialog.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/submitters/add-submitter-dialog/add-submitter-dialog.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/submitters/submitters.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/complaint-referral/submitters/submitters.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/submitter/submitter.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/submitter/submitter.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/submitter/submitter.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/submitter/submitter.component.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/submitter/submitter.service.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.service.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/submitter/submitter.controller.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/submitter/submitter.dto.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/submitter/submitter.service.ts
- Create add submitter modal component
- Add submitter add/edit buttons to complaint/referral tab
- Add submitters editing section to complaint/referral component
- Improve child form integration
- Move heading from submitter form to parent component(s)
- Have submitter form component broadcast its UUID with update DTO
- Make submitter title configurable
- Add optional delete button to submitter component
- Add bulk submitter update to API and services
- Add delete submitter to frontend service
> 2417 add many submitters edit submitter section

- alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.module.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/property-maps/property-maps.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/property-maps/property-maps.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/property-maps/property-maps.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/property-maps/property-maps.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/responsible-parties/responsible-parties.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/details/responsible-parties/responsible-parties.component.scss
- alcs-frontend/src/app/features/compliance-and-enforcement/details/responsible-parties/responsible-parties.component.spec.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/details/responsible-parties/responsible-parties.component.ts
- alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.html
- alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.ts
- alcs-frontend/src/app/services/compliance-and-enforcement/documents/document.service.ts
- alcs-frontend/src/app/shared/inline-editors/inline-text/inline-text.component.html
- alcs-frontend/src/app/shared/inline-editors/inline-text/inline-text.component.ts
- services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.entity.ts
- services/apps/alcs/src/providers/typeorm/migrations/1757633237935-AddMapsToDocumentSectionEnum.ts
- Added Property & Maps to submission
- Added Responsible Parties to submission
> 2540 Property & Maps Submission
