alcs-api/src/common/authorization/authorization.controller.spec.ts, alcs-api/src/common/authorization/authorization.controller.ts, alcs-api/src/common/authorization/authorization.service.spec.ts, alcs-api/src/common/authorization/authorization.service.ts, alcs-frontend/src/app/app-routing.module.ts, alcs-frontend/src/app/features/authorization/authorization.component.ts, alcs-frontend/src/app/features/home/home.component.html, alcs-frontend/src/app/features/home/home.component.spec.ts, alcs-frontend/src/app/features/home/home.component.ts, alcs-frontend/src/app/services/authentication/authentication.service.ts, alcs-frontend/src/app/services/authentication/hasRoles.guard.spec.ts, alcs-frontend/src/app/services/authentication/hasRoles.guard.ts, alcs-frontend/src/app/services/user/user.service.ts, alcs-frontend/src/app/shared/header/header.component.html, alcs-frontend/src/app/shared/header/header.component.ts
* Prevent users from loading home/boards/applications if they don't have roles set
* Take users to /provision page if they have no roles
* Setup header to render minimally when user has no roles
* Remove noroles flag from backend as frontend now has the logic
=> Add role guard to ensure users have roles

portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.ts
* Input fires on change event, selecting the same file twice does not fire a change event
* Clear input after we emit so the same file can be selected twice
=> Clear input after files emit

services/apps/alcs/src/main.ts, services/apps/portal/src/main.ts
* Do not buffer logs, this meant that logs were being held until the Logger finished initializing, turn off buffer so that it prints sooner (although not in correct format)
=> Turn off buffer logs

alcs-frontend/src/app/features/application/application.component.ts, alcs-frontend/src/app/services/application/application-detail.service.ts
* Clear the application from the pipe so that any initial subscribers will receive undefined instead of the previously loaded application
=> Clear Application when unloading application page

alcs-frontend/src/app/shared/pipes/fileSize.pipe.ts, portal-frontend/src/app/shared/pipes/fileSize.pipe.ts
Use native JS Math functions to calculate and compare file size instead of number to string conversion for improved performance
=> Display minimum file size to user

bin/migrate-oats-data/documents/documents.py, bin/migrate-oats-data/sql/documents/documents.sql
Documents created by PROXY_OATS_APPLICANT and PROXY_OATS_LOCGOV are considered to have come from the portal and given the system flag of 'OATS_P'. All other documents are assumed to have come from the oats system and given the flag of 'OATS'.
=> Added OATS and OATS_P flag to migrated OATS data in ALCS system

services/apps/alcs/src/alcs/board/board.controller.spec.ts, services/apps/alcs/src/alcs/board/board.controller.ts, services/apps/alcs/src/alcs/board/board.service.spec.ts, services/apps/alcs/src/alcs/board/board.service.ts, services/apps/alcs/src/alcs/card/card.service.ts, services/apps/alcs/src/alcs/import/import.service.spec.ts, services/apps/alcs/src/alcs/import/import.service.ts
* Changing the board was conflicting with the updates to notifications made earlier, since change board already has a full entity, save it directly instead of doing other stuff.
=> Update Change Board to use save directly

portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.html, portal-frontend/src/app/shared/file-drag-drop/file-drag-drop.component.scss
Found out why styling wasn't applied when deployed:
* `<div>` doesn't support `disabled` attribute
* Ng-Reflect attributes only exist as dev helpers, and they won't show up in non-debug env (prod)
=> Fix disabled upload area styling in non-local env

alcs-frontend/src/app/app-routing.module.ts, alcs-frontend/src/app/features/board/board.component.ts, alcs-frontend/src/app/shared/card/card.component.html
* Add soil office to allowed to see boards
* Fix paused calculation to check both are undefined
* Remove = so that both labels will not show
=> NOI Bugfixes

portal-frontend/src/app/features/application-details/application-details.component.html
Step 3 is unchanged
Step 8 is updated to show the same fields as app detail read only page
=> Show primary contact field validations in review if selected contact

alcs-frontend/src/app/features/application/applicant-info/application-details/application-details.component.spec.ts, alcs-frontend/src/app/features/application/application.component.html, alcs-frontend/src/app/features/application/application.component.spec.ts, alcs-frontend/src/app/features/application/application.component.ts, alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.html, alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.scss, alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.spec.ts, alcs-frontend/src/app/features/application/lfng-info/lfng-info.component.ts, alcs-frontend/src/app/services/application/application-submission/application-submission.service.spec.ts, alcs-frontend/src/app/services/application/application.dto.ts
- Retrieve app status using `ApplicationSubmissionService`
- Display L/FNG banner based on status
- Add app status enum to ALCS (same enum exist in `portal-frontend` and `services` directories)
=> ALCS View of under/pending LFNG Review and returned applications

alcs-frontend/src/app/features/admin/board-management/board-management-dialog/board-management-dialog.component.scss, alcs-frontend/src/styles.scss
* Remove manual scroll bac from board dialog
* Change max-height to 80vh so the dialog stays on the screen
=> Constrain dialogs to stay inside the screen

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.ts, alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.ts, alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts
* Copy over temp ID when we re-map components so that we can easily filter using TempID whenever their inputs change.
=> Copy over TempID when re-mapping and simplify filter logic

portal-frontend/src/app/features/edit-submission/edit-submission.component.ts, portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.html, portal-frontend/src/app/features/edit-submission/primary-contact/primary-contact.component.ts, portal-frontend/src/app/features/edit-submission/review-and-submit/review-and-submit.component.ts, services/apps/alcs/src/portal/application-submission/application-submission.service.ts
* Move confirmation dialog to edit-submission so it only shows for regular submission not ALCS edit submission
* Update Primary Contact component to show Government Contact if it was selected previously
* Re-apply previous bugfix to load proper relations after an update is made
=> Edit Submission Fixes

portal-frontend/src/app/features/applications/edit-submission/proposal/pfrs-proposal/pfrs-proposal.component.html, portal-frontend/src/app/features/applications/edit-submission/proposal/roso-proposal/roso-proposal.component.html, portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pfrs/pfrs-proposal.component.html, portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/pofo/pofo-proposal.component.html, portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.html, portal-frontend/src/app/features/notice-of-intents/edit-submission/proposal/roso/roso-proposal.component.ts
This prevents calling form.patchvalue from immediately calling the hooked functions, which we don't want.
=> Change valueChange -> Change

portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.html, portal-frontend/src/app/features/notifications/view-submission/view-notification-submission.component.ts, portal-frontend/src/app/services/notification-submission/notification-submission.dto.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-status-type.entity.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-status.dto.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-status.entity.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-submission-status.controller.spec.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-submission-status.controller.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-submission-status.module.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-submission-status.service.spec.ts, services/apps/alcs/src/alcs/notification/notification-submission-status/notification-submission-status.service.ts, services/apps/alcs/src/alcs/notification/notification.module.ts, services/apps/alcs/src/common/automapper/notice-of-intent-submission.automapper.profile.ts, services/apps/alcs/src/common/automapper/notification-submission.automapper.profile.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.controller.spec.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.controller.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.entity.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.module.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.spec.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts, services/apps/alcs/src/providers/typeorm/migrations/1693952313867-add_notification_statuses.ts, services/apps/alcs/src/providers/typeorm/migrations/1693952400742-seed_notification_statuses.ts
* Add statuses to notifications
=> Add Notification Statuses

services/apps/alcs/src/queues/scheduler/scheduler.service.spec.ts, services/apps/alcs/src/queues/scheduler/scheduler.service.ts, services/apps/alcs/src/utils/pacific-date-time-helper.spec.ts, services/apps/alcs/src/utils/pacific-date-time-helper.ts
- introduce isDST function
- use utc corn expression to match desired PST or PDT time
=> convert cron expression to utc to properly map to PST or PDT

portal-frontend/src/app/features/public/public.module.ts, portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.html, portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.ts, portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.html, portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts, portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.html, portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.ts, portal-frontend/src/app/features/public/search/public-search.component.html, portal-frontend/src/app/features/public/search/public-search.component.scss, portal-frontend/src/app/features/public/search/public-search.component.ts, portal-frontend/src/app/features/public/search/search-list/search-list.component.html, portal-frontend/src/app/features/public/search/search-list/search-list.component.scss, portal-frontend/src/app/features/public/search/search-list/search-list.component.spec.ts, portal-frontend/src/app/features/public/search/search-list/search-list.component.ts, portal-frontend/src/app/services/search/search.dto.ts, portal-frontend/src/app/shared/header/header.component.html, portal-frontend/src/app/shared/header/header.component.scss, portal-frontend/src/app/shared/header/header.component.ts, services/apps/alcs/src/portal/public/search/application/public-application-search.service.spec.ts, services/apps/alcs/src/portal/public/search/application/public-application-search.service.ts, services/apps/alcs/src/portal/public/search/notice-of-intent/public-notice-of-intent-search.service.spec.ts, services/apps/alcs/src/portal/public/search/notice-of-intent/public-notice-of-intent-search.service.ts, services/apps/alcs/src/portal/public/search/notification/public-notification-search.service.spec.ts, services/apps/alcs/src/portal/public/search/notification/public-notification-search.service.ts, services/apps/alcs/src/portal/public/search/public-search.dto.ts
* Add mobile layout
* Change region and status to multi-select
* Change results to open in same tab / window
* Change header to update based on current page and make clickable
=> Search Pt3

bin/migrate-oats-data/applications/application_submission_status_email/submission_status_email.py, bin/migrate-oats-data/noi/noi_submission_status_email/submission_status_email.py, bin/migrate-oats-data/noi/notice_of_intent_migration.py, bin/migrate-oats-data/noi/notice_of_intent_submissions/__init__.py, bin/migrate-oats-data/noi/notice_of_intent_submissions/notice_of_intent_proposal_fields.py, bin/migrate-oats-data/noi/sql/notice_of_intent_submission/proposal_fields/notice_of_intent_proposal_fields.sql, bin/migrate-oats-data/noi/sql/notice_of_intent_submission/proposal_fields/notice_of_intent_proposal_fields_count.sql, bin/migrate-oats-data/noi/sql/notice_of_intent_submission/proposal_fields/validation.sql
- NOIS proposal fields and soil fields with default values
- validation script
=> notice of intent submission proposal and soil default fields

portal-frontend/src/app/services/notification-document/notification-document.service.spec.ts, portal-frontend/src/app/services/notification-document/notification-document.service.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.spec.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts, services/apps/alcs/src/alcs/application/application-submission/application-submission.service.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.spec.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts, services/apps/alcs/src/portal/application-document/application-document.controller.spec.ts, services/apps/alcs/src/portal/application-document/application-document.controller.ts, services/apps/alcs/src/portal/application-submission/application-submission.service.spec.ts, services/apps/alcs/src/portal/application-submission/application-submission.service.ts, services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.spec.ts, services/apps/alcs/src/portal/notice-of-intent-document/notice-of-intent-document.controller.ts, services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.spec.ts, services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-submission.service.ts, services/apps/alcs/src/portal/notification-document/notification-document.controller.spec.ts, services/apps/alcs/src/portal/notification-document/notification-document.controller.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.entity.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.spec.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts, services/apps/alcs/src/portal/public/application/application-decision.controller.spec.ts, services/apps/alcs/src/portal/public/application/application-decision.controller.ts, services/apps/alcs/src/portal/public/notice-of-intent/notice-of-intent-decision.controller.spec.ts, services/apps/alcs/src/portal/public/notice-of-intent/notice-of-intent-decision.controller.ts
* Add logic to check that the current user has correct permissions in accordance with the documents visibility flags to access the documents
* Add logic so only people who have edit rights on a submission can delete its documents
=> Add Permissions Checks to Document Portal Endpoints

portal-frontend/src/app/features/notifications/edit-submission/proposal/proposal.component.ts
* Convert empty string to null when sending to back end
* Re-load documents after saving to reflect changes on Step 8
=> Fixes for Plan Numbers

services/apps/alcs/src/portal/public/application/public-application.service.spec.ts, services/apps/alcs/src/portal/public/application/public-application.service.ts
* Use get for portal instead which does not load draft decisions
=> Don't load draft decisions for Public APPs

services/apps/alcs/src/common/authorization/authorization.module.ts, services/apps/alcs/src/common/authorization/authorization.service.ts, services/apps/alcs/src/common/authorization/roles-guard.service.spec.ts, services/apps/alcs/src/portal/code/code.controller.spec.ts, services/apps/alcs/src/portal/code/code.controller.ts
* Controller is now public, so without the RolesGuard there is no req.user.entity
* Grab token from headers and decode it.
=> Manually decode token on Code Controller

portal-frontend/src/app/features/applications/edit-submission/select-government/select-government.component.ts
* If you type the full government name but do not select it, the warning banner was not showing
* By updating the value on Blur, this is fixed
=> Update Selected Own Governmment on Blur

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-conditions.component.spec.ts, alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts, alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.spec.ts, alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.spec.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.ts, alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts, alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.service.ts, alcs-frontend/src/app/services/notice-of-intent/decision/notice-of-intent-decision.dto.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision-v2.module.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.spec.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.controller.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.spec.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision.dto.ts, services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/linked-resolution-outcome-type.entity.ts, services/apps/alcs/src/alcs/application-decision/application-decision.entity.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.spec.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.dto.ts, services/apps/alcs/src/common/automapper/application-decision-v2.automapper.profile.ts, services/apps/alcs/src/providers/typeorm/migrations/1698076577193-update_decision_outcomes.ts, services/apps/alcs/src/providers/typeorm/migrations/1698104086542-remove_linked_outcome_for_app_decs.ts, services/apps/alcs/test/mocks/mockEntities.ts
* Remove certain outcomes
* Remove linked outcome resolution for App Decisions
* Add ability and unit tests for copying an existing decision
=> Update Decisions + Add Copying

bin/migrate-oats-data/noi/notice_of_intent_init.py, bin/migrate-oats-data/noi/oats_to_alcs_notice_of_intent_table_etl/oats_to_alcs_notice_of_intent_table_etl.py, bin/migrate-oats-data/noi/sql/notice_of_intent_base/validate_that_oats_does_not_override_alcs_with_null.sql
- do not override ALCS values with OATS NULL
- validation script
=> NOI COALESCE on update for fee_paid_date

bin/migrate-oats-data/applications/submissions/statuses/application_status_cancelled.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_in_progress.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_returned_incomplete_lfng.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_review_lfng.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_submitted_alc.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_submitted_incomplete_alc.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_submitted_lfng.py, bin/migrate-oats-data/applications/submissions/statuses/application_status_wrong_lfng.py, bin/migrate-oats-data/noi/notice_of_intent_submissions/statuses/notice_of_intent_status_cancelled.py, bin/migrate-oats-data/noi/notice_of_intent_submissions/statuses/notice_of_intent_status_in_progress.py, bin/migrate-oats-data/noi/notice_of_intent_submissions/statuses/notice_of_intent_status_submitted_to_alc.py, bin/migrate-oats-data/noi/notice_of_intent_submissions/statuses/notice_of_intent_status_submitted_to_alc_incomplete.py
Oats stores dates the way users selected them so it is safe to assume that the date is actually in PST and not in UTC
=> switch from covert_time to add_time_zone

portal-frontend/src/app/features/applications/view-submission/view-application-submission.component.html, portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.html, portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.ts
This is MR is fixing missed reqs caught by QA:
- Removed missed edit/cancel buttons that were missed
- Correct NOI cancel confirmation from 'application' to 'notice of intent'
=> Remove missed edit/cancel buttons, correct NOI cancel confirm text

portal-frontend/src/app/services/authentication/authentication.service.ts
* Our backend requires a valid token to use the refresh token, since the token expires first it should be checked instead
* Add logging
=> Use token expiry time

portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.html, portal-frontend/src/app/features/applications/edit-submission/parcel-details/parcel-entry/parcel-entry.component.ts, portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.html, portal-frontend/src/app/features/notice-of-intents/edit-submission/parcels/parcel-entry/parcel-entry.component.ts, portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.scss, portal-frontend/src/app/features/notifications/edit-submission/other-attachments/other-attachments.component.html, portal-frontend/src/app/features/notifications/edit-submission/proposal/proposal.component.html, portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.html, portal-frontend/src/app/features/notifications/edit-submission/review-and-submit/submit-confirmation-dialog/submit-confirmation-dialog.component.scss, portal-frontend/src/app/features/notifications/notification-details/parcel/parcel.component.html, portal-frontend/src/app/features/notifications/notification-details/proposal-details/proposal-details.component.html
- Scroll to owner info on owner select (parcel step)
- Missed from ALCS-1270
- Make save and step buttons sticky
- Remove redundant max file size notices
- Remove space to align with others
- Only show edit button when parcels > 1
- Show units for total area of SR
- Expand submit confirmation text
- Add contact link to submit confirmation
- Fix submit confirmation mobile button layout
=> Improvements for notifications buttons, uploader, review, and submit confirmation

portal-frontend/src/app/features/applications/alcs-edit-submission/alcs-edit-submission.component.ts, portal-frontend/src/app/features/applications/edit-submission/edit-submission.component.ts, portal-frontend/src/app/features/applications/review-submission/review-submission.component.ts, portal-frontend/src/app/features/notice-of-intents/alcs-edit-submission/alcs-edit-submission.component.ts, portal-frontend/src/app/features/notice-of-intents/edit-submission/edit-submission.component.ts, portal-frontend/src/app/features/notifications/edit-submission/edit-submission.component.ts, portal-frontend/src/app/services/authentication/alcs-auth.guard.ts, portal-frontend/src/app/services/authentication/auth.guard.spec.ts, portal-frontend/src/app/services/authentication/auth.guard.ts, portal-frontend/src/app/services/authentication/authentication.service.ts, portal-frontend/src/app/shared/guard/can-deactivate.guard.ts, services/apps/alcs/src/common/authorization/authorization.controller.ts
* Add new route for auth controller so that it triggers maintenance guard for portal
* Add logic to prevent deactivate from infinite looping when navigating to the maintenance page. Save fails triggering a redirect which triggers canDeactivate which calls save again.
=> Fixes for Portal Maintenance Mode

portal-frontend/src/app/features/applications/edit-submission/files-step.partial.ts, portal-frontend/src/app/features/notice-of-intents/edit-submission/files-step.partial.ts, portal-frontend/src/app/features/notice-of-intents/view-submission/view-notice-of-intent-submission.component.html, portal-frontend/src/app/features/notifications/edit-submission/files-step.partial.ts, portal-frontend/src/app/services/application-document/application-document.service.ts, portal-frontend/src/app/services/notice-of-intent-document/notice-of-intent-document.service.ts, portal-frontend/src/app/services/notification-document/notification-document.service.ts
* Green toast was replacing the yellow warning toast
* Move Cancel NOI into the button container so it looks correct
=> Prevent green success toast from firing when file is too large

bin/migrate-oats-data/README.md, bin/migrate-oats-data/applications/base_applications.py, bin/migrate-oats-data/applications/sql/insert-batch-application.sql, bin/migrate-oats-data/noi/notice_of_intent_init.py, bin/migrate-oats-data/noi/sql/insert_noi.sql, bin/migrate-oats-data/prod_db_obfuscation/oats/obfuscate.py
- do not obfuscate the organization name in OATS
- update readme file with backup and restore instructions for Postgres DB
- update batch insert script to correctly handle duplications of applications and NOIs if they are caused by local government duplications
- add filter to application batch insert
=> update obfuscation, update batch insert, update readme

services/apps/alcs/src/alcs/search/application/application-advanced-search.service.spec.ts, services/apps/alcs/src/alcs/search/application/application-advanced-search.service.ts, services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.spec.ts, services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts, services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.spec.ts, services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.ts
- Include submissions associated with soft-deleted app/NOI/notification types to be included in ALCS frontend search results
- Update query mocks to include `withDeleted` method
=> Include submissions associated with soft deleted types in ALCS frontend (ALCS-1459)

portal-frontend/src/app/features/home/home.module.ts, portal-frontend/src/app/features/home/inbox/inbox.component.html, portal-frontend/src/app/features/home/inbox/inbox.component.spec.ts, portal-frontend/src/app/features/home/inbox/inbox.component.ts
* Requiring the tabs to be rendered to get their order forces the page to default to application since they are not rendered on initial load, meaning it was always going to applications
=> Hardcode tab order for easier referencing

bin/migrate-oats-data/applications/submissions/parcels/primary_contact/application_primary_contact.py
Primary contact will now convert None to null as the first name, resulting in No Data
=> removing our friend None entirely

portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts, portal-frontend/src/app/shared/owner-dialogs/parcel-owners/parcel-owners.component.ts, services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts, services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.ts
* Only delete the corporate summary if a new one is being set
* Use the passed in document service so that it works for both NOI and APP
* Only call upload pending if there is a pending file
=> Owner Fixes

alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/naru-input/naru-input.component.html, alcs-frontend/src/app/features/application/proposal/proposal.component.html
- Changed to m^2 in NAUR input
- Added conditionals for proposal and component templates to change to m^2 just for NARU
=> Change ha to m^2 for NAUR decisions/proposal

portal-frontend/src/app/features/applications/review-submission/review-submit-fng/review-submit-fng.component.ts, portal-frontend/src/app/features/applications/review-submission/review-submit/review-submit.component.ts, portal-frontend/src/app/services/application-submission-review/application-submission-review.service.ts, services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts
* Skip validation if the submission is from OATS and has never been updated
* Return a response from finish so we can check in the front end
* Only redirect to success page if there is a response
=> Bypass validation for OATS Submissions

bin/migrate-oats-data/prod_db_obfuscation/alcs/application/application.py, bin/migrate-oats-data/prod_db_obfuscation/alcs/covenant/covenant.py, bin/migrate-oats-data/prod_db_obfuscation/alcs/notice_of_intent/notice_of_intent.py, bin/migrate-oats-data/prod_db_obfuscation/alcs/notification/notification.py
disable organization name obfuscation since it is not 'personally identifiable information' and as result not protected under Personal Information Protection Act
=> Disable organization name obfuscation

services/apps/alcs/src/providers/typeorm/migrations/1707852182314-set_purpose_on_app_from_oats.ts, services/apps/alcs/src/providers/typeorm/migrations/1707940567877-add_advanced_parcel_mapping_true.ts, services/apps/alcs/src/providers/typeorm/migrations/1707948028191-reset_REVG_status_if_no_review.ts
Run oats migrations conditionally. This will ensure that developers who work on local env do not need to introduce oats schema and related infrastructure. All hosted envs have "oats" as part of DB
=> execute oats related migrations conditionally

alcs-frontend/src/app/features/board/board.component.html, alcs-frontend/src/app/features/board/dialogs/app-modification/create/create-app-modification-dialog.component.spec.ts, alcs-frontend/src/app/features/board/dialogs/app-modification/create/create-app-modification-dialog.component.ts, alcs-frontend/src/app/features/board/dialogs/noi-modification/create/create-noi-modification-dialog.component.spec.ts, alcs-frontend/src/app/features/board/dialogs/noi-modification/create/create-noi-modification-dialog.component.ts, alcs-frontend/src/app/features/board/dialogs/planning-review/create/create-planning-review-dialog.component.spec.ts, alcs-frontend/src/app/features/board/dialogs/planning-review/create/create-planning-review-dialog.component.ts, alcs-frontend/src/app/features/board/dialogs/reconsiderations/create/create-reconsideration-dialog.component.spec.ts, alcs-frontend/src/app/features/board/dialogs/reconsiderations/create/create-reconsideration-dialog.component.ts, alcs-frontend/src/app/services/planning-review/planning-review.service.ts, services/apps/alcs/src/alcs/application-decision/application-modification/application-modification.controller.ts, services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.controller.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-modification/notice-of-intent-modification.controller.ts, services/apps/alcs/src/alcs/planning-review/planning-review.controller.ts, services/apps/alcs/src/alcs/planning-review/planning-review.service.ts
* Applies to Planning Reviews, Reconds, and App/NOI Modifications
* Update backend controllers to correctly return created objects
* Update dialogs to load card into URL triggering its opening
=> Open card after creating

services/apps/alcs/src/providers/typeorm/migrations/1709059569307-convert_ha_to_m2.ts
* convert ha fields from application to m2:
* application_submission
* nfu_total_fill_area
* soil_to_remove_area
* soil_to_place_area
* naru_to_place_area
* application_decision_component
* soil_to_remove_area
* soil_to_place_area
* convert ha fields from notice of intent to m2:
* notice_of_intent_submission, notice_of_intent_decision_component
* soil_to_remove_area
* soil_to_place_area
* create tmp tables in public schema so it will be easier to revert if necessary. Tmp tables will be deleted once confirmed that data looks good.
=> migration script to convert ha to m2

services/apps/alcs/src/portal/public/search/application/public-application-search-view.entity.ts, services/apps/alcs/src/providers/typeorm/migrations/1709669266230-use_query_builder_for_pub_app_search_view.ts
Public application search view entity was using the query builder originally, but I had temporarily switched to entering the query manually to save time before launch. This reverts that change, but with the same performance improvements applied.
=> Convert pub app search view entity to use query builder

bin/migrate-files/README.md, bin/migrate-files/application_docs/__init__.py, bin/migrate-files/application_docs/srw_docs_import.py, bin/migrate-files/migrate-files.py
=> add srw-only import

services/apps/alcs/src/main.module.ts, services/apps/alcs/src/main.ts, services/apps/alcs/src/providers/keycloak/keycloak-config.service.ts
* Don't log all headers, they have the auth key and don't really help anyway
* Prevent keycloak from logging every token expiry
=> Logging changes

.github/workflows/e2e-test.yml
- Checks out E2E tests from develop
- Runs against live dev environment
- Scheduled run against dev
- Can run manually against dev or test
**Note**: must be merged to main for `schedule` and `workflow_dispatch` to work.
=> Create initial E2E workflow

alcs-frontend/src/app/services/authentication/authentication.service.ts
In the original implementation, the refreshTokens method immediately redirects to /login if the expires time is reached, without considering the refreshExpires time. This means that even if the refresh token is still valid, the user will be redirected to /login prematurely.
=> login redirect fix

.github/workflows/e2e-test.yml
- Upload artifact does not support `working-directory`, so path needs to be relative to repo root
=> Fix report path

portal-frontend/src/app/features/public/search/public-search.component.html, portal-frontend/src/app/features/public/search/public-search.component.ts
- Remove duplicate spinner
- Restructure template conditionals so same spinner is used for both initial load and subsequent loads
- Show 'Search Results' title while loading to be consistent with subsequent loads
- Scroll to now always-visible wrapper div
- Use hack to delay scrolling until spinner is visible
=> Fix not scrolling to spinner on initial search

alcs-frontend/src/app/features/notification/intake/intake.component.html, alcs-frontend/src/app/features/notification/intake/intake.component.ts, alcs-frontend/src/app/shared/inline-editors/inline-text/inline-text.component.ts
- Add `updateOnSave` option to `inline-text` component
- Set `updateOnSave` to false for intake email
=> Fix ALC intake email updating even when not confirmed

services/apps/alcs/src/portal/guards/maintenance.guard.ts
* Production is set to have /api/ added to all routes breaking how the maintenance guard normally checks.
=> Add Production Routes to API Guard

services/apps/alcs/src/providers/typeorm/migrations/1712686499450-District_of_Barriere.ts
- remove redundant spaces in local government names
- update District Of Barriere applications and submissions
=> trim redundant space, update DistrictOfBarriere applications

services/apps/alcs/src/providers/typeorm/migrations/1713460391976-add_oats_property_ids_to_inquiry_parcels_check_exist.ts
Migration to fix double column adding issue due to typo in drop statement of a now deleted migration
=> add check if columns already exist in DB

alcs-frontend/src/app/features/application/documents/documents.component.html
* For some reason there was code hiding C flag if applicant was also checked
* Add missing space to , after G
=> Show commissioner flag when applicant is present

alcs-frontend/package-lock.json, alcs-frontend/package.json, portal-frontend/package-lock.json, portal-frontend/package.json
* Currrently open issue breaking NGX Mask when it has decimal separators https://github.com/JsDaddy/ngx-mask/issues/1349
* Downgrade to 17.0.4 which does not have the issue
=> Downgrade NGX Mask to avoid input Issues

alcs-frontend/src/app/shared/inline-editors/inline-number/inline-number.component.html, alcs-frontend/src/app/shared/inline-editors/inline-number/inline-number.component.ts
'0' evalutes to false so ngIf=value on '0' returns false. Check for null directly instead.
=> Change inline number input value to check for null

services/apps/alcs/src/portal/application-submission/application-submission-validator.service.spec.ts, services/apps/alcs/src/portal/application-submission/application-submission-validator.service.ts
- Floating point error can cause lot total to register as different than parcel size when they should be equal
- Rounding to the 5 decimals allowed by UI to account for thi
=> Compare rounded lot vs. parcel size to avoid floating non-equality

services/apps/alcs/src/alcs/notification/notification.controller.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts, services/apps/alcs/src/providers/email/email.service.ts
- Empty strings as emails were causing SRW government emails to fail
- Return email sent status to resend endpoint
- Fail resend endpoint if email not sent
=> Fix empty gov email causing emails to fail and success toast on fail

portal-frontend/src/app/features/public/search/application-search-table/application-search-table.component.ts, portal-frontend/src/app/features/public/search/notice-of-intent-search-table/notice-of-intent-search-table.component.ts, portal-frontend/src/app/features/public/search/notification-search-table/notification-search-table.component.ts, portal-frontend/src/app/features/public/search/public-search.component.ts, portal-frontend/src/app/features/public/search/search-list/search-list.component.html, portal-frontend/src/app/features/public/search/search-list/search-list.component.ts
* The input setters are called in any order, this results that even if all of the inputs are populated in the parent they may not be populated in the child yet
* Add logic so that when either the statuses or results are set, we re-hydrated the results
=> Allow statuses to come in later than results

.codeclimate.yml
exclude ora2pg and openshift from code climate report
=> exclude ora2pg and openshift file from code coverage

services/apps/alcs/src/providers/typeorm/migrations/1716400640726-add_lfng_reviews_to_cancelled.ts
* After review anything that was submitted to ALC correctly has a review, so we can use the same query but apply to ones currently cancelled
=> Add L/FNG reviews to Cancelled Applications that have REVG

portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.ts, portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts, services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.spec.ts, services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts, services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.dto.ts, services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.spec.ts, services/apps/alcs/src/portal/notice-of-intent-submission/notice-of-intent-owner/notice-of-intent-owner.service.ts
* Also fixed a bug where the corporate summary was not getting deleted
=> Keep organization name when changing from indv -> organization

alcs-frontend/src/app/features/commissioner/application/commissioner-application.component.scss
Added padding to the bottom of the Evidentiary Record table in the Commissioner view
=> Add padding to bottom of Evidentiary Record table

services/apps/alcs/src/providers/typeorm/migrations/1716834660249-map_legacy_id_to_inquiries.ts
- verified matching legacy_id to issue #
- only update if oats field is not null
- does not overwrite existing alcs value
- only changes oats_etl entries
=> Map legacy_id to inquiries

services/apps/alcs/src/providers/typeorm/migrations/1716916423632-map_optional_doc_description.ts, services/apps/alcs/src/providers/typeorm/migrations/1716925980113-map_optional_doc_description_NOI.ts, services/apps/alcs/src/providers/typeorm/migrations/1716926436980-map_optional_doc_description_SRW.ts
- Populate optional description field
- SRW was done already but migration will still run and catch anything was missed
- Does not touch inquiry or planning review
=> Application, NOI and SRW document description mapping

services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.spec.ts, services/apps/alcs/src/portal/application-submission/application-owner/application-owner.service.ts
Looks like Application / NOI now work differently and Application uses the returned owner. The returned owner was not being loaded with their corporate summary resulting in it showing as Not Applicable.
=> Return Owner with Corporate Summary on Save/Updated

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.ts
* This means subsequent decisions will have to come after the first rather than requiring each decision to come after the ones already done
=> Use lowest decision date as minimum instead of highest

alcs-frontend/src/app/shared/inline-editors/inline-textarea-edit/inline-textarea-edit.component.scss, alcs-frontend/src/styles/ngselect.scss
Following UI/UX bugs have been fixed:
- ng-select dropdown border, placeholder, and arrow colour fixed to ALCS primary instead of blue
- Fixed cursor remaining in the pointer state after clicking on proposal summary's inline text area
=> Fix ALCS UI/UX Bugs

services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision.dto.ts
Automap `wasReleased` from the decision entity to
the DTO when responding to API requests for decisions,
so that the frontend can read that value.
=> Automap `wasReleased` to get value in frontend

portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts
Fixed the bug that attached corporate summary file changing to not-applicable after opening the edit dialog and saving it without any changes.
=> Fix attached corporate summary going not-applicable

services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts
In NOIs Advanced search, the "Submitted to ALC - End Date" field used the beginning of the mentioned date (12:00 AM) as a filter. For example, If the AOI was submitted on June 6th, 2:00 PM, it would be after 12:00 AM so it would not be in results. To fix, the filter is now set to the beginning of the next day.
=> Fix NOI advanced search "submitted to" filter not working properly

portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.ts, portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts
By putting government user check first, it only
checks the parcel owners length if not a government
user.
=> Reorder condition for initial contact selection

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-components/decision-component/decision-component.component.ts
Fixed 500 server error on submitting decision component with cleared fields which had value before for NOIs and Applications.
The error was on the ALCS-frontend that instead of sending null values for empty fields used to sent '' value which caused 500 error on the server side.
=> Fix NOI Decision Component Empty Fields Errors

.github/workflows/e2e-test.yml, e2e/pages/alcs/alcs-login-page.ts, e2e/tests/tur.spec.ts
- Changed ALCS login to BCEID instead of IDIR
- e2e-test.yml workflow changes:
- Added ALCS Base URL input 
- Added branch input to manually trigger on any branch. It can be useful to manually trigger on develop before merging to main or triggering on branches before merging to develop
=> Fix E2E Testing workflow Failing

services/apps/alcs/src/alcs/notification/notification.service.spec.ts, services/apps/alcs/src/alcs/notification/notification.service.ts, services/apps/alcs/src/providers/typeorm/migrations/1719506636796-remove_incomplete_gis_subtasks.ts
- Stopped auto creation of GIS subtasks when submitting new SRW notifications to ALCS
- Removed previously automatically created GIS subtasks which were not completed yet
=> Stop Auto Creation of GIS Subtasks When Submitting New Notifications to ALCS

alcs-frontend/package-lock.json, alcs-frontend/package.json, alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.html, alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.scss, alcs-frontend/src/app/features/admin/local-government/dialog/local-government-dialog.component.ts, alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/release-dialog/release-dialog.component.ts, alcs-frontend/src/app/features/board/dialogs/inquiry/create/create-inquiry-dialog.component.ts, alcs-frontend/src/app/features/inquiry/detail/details.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/release-dialog/release-dialog.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/release-dialog/release-dialog.component.ts, alcs-frontend/src/app/features/notification/intake/intake.component.html, alcs-frontend/src/app/shared/inline-editors/inline-text/inline-text.component.html, alcs-frontend/src/app/shared/inline-editors/inline-text/inline-text.component.scss, alcs-frontend/src/app/shared/inline-editors/inline-text/inline-text.component.ts, alcs-frontend/src/app/shared/validators/email-validator.ts, portal-frontend/package-lock.json, portal-frontend/package.json, portal-frontend/src/app/features/applications/edit-submission/primary-contact/primary-contact.component.ts, portal-frontend/src/app/features/applications/edit-submission/proposal/cove-proposal/transferee-dialog/transferee-dialog.component.ts, portal-frontend/src/app/features/applications/review-submission/review-contact-information/review-contact-information.component.ts, portal-frontend/src/app/features/notice-of-intents/edit-submission/primary-contact/primary-contact.component.ts, portal-frontend/src/app/features/notifications/edit-submission/primary-contact/primary-contact.component.ts, portal-frontend/src/app/features/notifications/edit-submission/transferees/transferee-dialog/transferee-dialog.component.ts, portal-frontend/src/app/shared/owner-dialogs/crown-owner-dialog/crown-owner-dialog.component.ts, portal-frontend/src/app/shared/owner-dialogs/owner-dialog/owner-dialog.component.ts, portal-frontend/src/app/shared/validators/email-validator.ts
- **Install validator and type defs for portal**
- **Create custom stricter email validator**
- **Update all portal email validators with strict one**
- **Consider empty emails valid**
- **Install validator and type defs**
- **Add stricter email validator to ALCS**
- **Update Angular form validator to strict version in ALCS**
- **Add `isEmail` option to `app-inline-text`**
- **Make email inline fields email fields**
- **Add `OnInit` interface to inline text component**
- **Validate email chips and show warning if invalid**
=> Add CHES-like validation to all email fields

alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/decision-component/basic/basic.component.ts, alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-component/basic/basic.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-component/basic/basic.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html, alcs-frontend/src/app/shared/inline-editors/inline-number/inline-number.component.html, alcs-frontend/src/app/shared/inline-editors/inline-number/inline-number.component.scss, alcs-frontend/src/app/shared/inline-editors/inline-number/inline-number.component.ts, alcs-frontend/src/app/shared/validators/value-validator.ts
**This PR covers both ALCS-2065 and ALCS-2077 tickets requirements.**
Following changes have been made:
- Added non zero and required validators to detect zero and empty values on ALR inline edit
- Added form control to inline-number component to have validation and prevent user from submission
- Add conditions to decisions components to have validation only on released decisions in NOIs and Applications
=> Block Null and Zero Values for Released Decisions' ALR Inline Editor for Applications and NOIs

portal-frontend/src/app/features/applications/application-details/application-details.component.html, portal-frontend/src/app/features/notice-of-intents/notice-of-intent-details/notice-of-intent-details.component.html
Fixed the bug that prevented applications and NOIs being submitted to ALCS if no optional document is attached on mobile view
=> Fix Zero Optional Attachment Bug on Submission in Applications and NOIs

portal-frontend/src/app/features/notifications/notification-details/notification-details.component.html
Fixed the UI/UX bug that prevented users from submitting notifications when no optional attachment is attached on mobile view.
=> Fix Zero Optional Attachment Bug on Submission in Notifications

services/apps/alcs/src/portal/pdf-generation/generate-noi-submission-document.service.ts, services/apps/alcs/src/portal/pdf-generation/generate-submission-document.service.ts
- Fixed Applicant Submission PDF (Portal download and {DATE}_APP_Submission.pdf on ALCS) including 'other' documents with non-applicant source for applications and NOIs
- Documents added after submission by ALC or during L/FNG review.
=> Fix Submission PDF Including "Other" Documents with Non-Applicant Source

portal-frontend/src/app/services/application-parcel/application-parcel.service.ts, portal-frontend/src/app/services/notice-of-intent-parcel/notice-of-intent-parcel.service.ts, portal-frontend/src/app/services/notification-parcel/notification-parcel.service.ts
In parcel details step on portal submission, clearing "Approx. Map Area" field value and trying to save it after it has been saved before could cause 500 error on server side. This commit fixes the issue by sending null value instead of empty string to the server side.
=> Fix Error on Changing "Approx. Map Area" Field to Empty Value and Saving it

services/apps/alcs/src/alcs/search/application/application-advanced-search.service.ts, services/apps/alcs/src/alcs/search/inquiry/inquiry-advanced-search.service.ts, services/apps/alcs/src/alcs/search/notice-of-intent/notice-of-intent-advanced-search.service.ts, services/apps/alcs/src/alcs/search/notification/notification-advanced-search.service.ts, services/apps/alcs/src/alcs/search/planning-review/planning-review-advanced-search.service.ts
ALCS Advanced Search:
- Fixed search results showing for the next day after "Submitted to ALC - End Date" and "Decision - End Date" fields. 
- Fixed pacific time conversion not being used. (Changed `new Date()` to `getNextDayToPacific()` and `getStartOfDayToPacific()`)
- Added toISOString for standardizing.
=> Fix ALCS Advanced Search "Date Range" Results Bugs

alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.html, alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.scss, alcs-frontend/src/app/shared/meeting-overview/meeting-overview.component.ts
- Update previous and next meetings columns and subtexts with new values. 
- Update "For Discussion" (Next Meeting previously) column to show all upcoming meetings.
=> Update Schedule page's "Previous Meetings" and "Next Meeting" columns

services/apps/alcs/src/providers/typeorm/migrations/1724702115054-fix_chase_submit_dates.ts
The timezone was incorrect on the previous migration
for the missed Village of Chase inquiries.
=> Small fix for previous migration

services/apps/alcs/src/providers/typeorm/migrations/1724368028724-missed_chase_inquiries_etl.ts
It was possible for the extracted `mime_type` column to be null, but the documents table requires it be non-null. This makes sure it always has a value.
=> Prevent `mime_type` from being null

services/apps/alcs/src/alcs/application/application-decision-meeting/application-decision-meeting.service.ts, services/apps/alcs/src/alcs/planning-review/planning-review-meeting/planning-review-meeting.service.ts
- If file has only meetings in the past, show the latest one. 
- If file has meetings in the past and the future, show the closest future one. 
- If the file has only meetings in the future, show the closest future one.
=> Fix "For Discussion" Column Showing the Furthest Date Instead of Closest

services/templates/emails/index.ts, services/templates/emails/notifications/srw-notice.template.ts, services/templates/emails/partials/header.template.ts, services/templates/emails/partials/masthead.template.ts
Header template and masthead are now functions that accept an optional parameter, `isNotification`. If `true`, they display a different details section.
=> Create branching header for notifications

alcs-frontend/src/app/features/notification/intake/intake.component.ts
When the email is changed, the resend method is called.
This method resent the notification to the new email, but also changes the status of the Notification:
await this.updateStatus(
submission.uuid,
NOTIFICATION_STATUS.ALC_RESPONSE_SENT,
);
Which I believe will solve the sync issue displayed on the screen.
=> Resend the response when an email is changed

services/apps/alcs/src/portal/inbox/notification/inbox-notification.service.ts
Fixed the cache flags on SRW searches.
So if there is a cached search, the SRW query is not repeated anymore with empty params.
=> Fixed the cache flags on SRW searches

services/apps/alcs/src/alcs/incoming-files/incoming-file.controller.ts, services/apps/alcs/src/alcs/incoming-files/incoming-file.dto.ts
Since the assigned user in the incoming files comes from a LEFT JOIN query, the mapping doesn't check if the assigned is null always returning an user to the DTO (showing the unwanted NA).
If the incoming file can be unassigned, makes sense to make the DTO nullable, and check on map method the query output, if the assignee is null or not, and populate it properly.
With this api change, the frontend check doesn't need to be changed, and it's ngIf check:
<app-avatar-circle
*ngIf="incomingFile.assignee"
[initials]="incomingFile.assignee.initials"
[name]="incomingFile.assignee.prettyName"
></app-avatar-circle>
Will reflect the reality.
=> ALCS-2254 DTO and map change

alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html, portal-frontend/src/app/features/applications/application-details/naru-details/naru-details.component.html, portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.html, portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/naru-proposal.component.scss, portal-frontend/src/app/features/applications/edit-submission/proposal/naru-proposal/residence-dialog/residence-dialog.component.ts, portal-frontend/src/app/features/public/application/submission/naru-details/naru-details.component.html, portal-frontend/src/app/shared/mobile/naru-residence-mobile-card/naru-residence-mobile-card.component.html, portal-frontend/src/app/shared/mobile/naru-residence-mobile-card/naru-residence-mobile-card.component.scss, portal-frontend/src/app/shared/mobile/naru-residence-mobile-card/naru-residence-mobile-card.component.ts, services/apps/alcs/src/providers/typeorm/migrations/1728581017573-convert_naru_floor_area_and_existing_structuers.ts
This changes fixes the missing existing and proposed residence fields for in-progress and submitted files after NARU structure changes. 
**DB Migration**
- If data present in 'naru_existing_structures' -> add 'Existing Residence' and put the data into 'description'
- If data present in 'naru_floor_area' -> add 'Proposed Residence' and put the data into 'floor area'
**UI Changes:**
- Add Validation for in-progress files that are missing existing/proposed residences fields, so they have to complete them in order to submit the form.
- Show data in the new format (No Data for missing fields) for already submitted files on portal and alcs frontend.
=> Fix Missing NARU Proposed/Existing Residence Data for Files After the Migration

alcs-frontend/src/app/features/application/applicant-info/application-details/naru-details/naru-details.component.html
Previously, the building plans were hidden if not provided. Now, it shows"No Data".
=> Always show building plans w/ no data if empty in ALCS app info

services/apps/alcs/src/alcs/admin/admin.module.ts, services/apps/alcs/src/alcs/admin/tag-category/tag-category.controller.spec.ts, services/apps/alcs/src/alcs/admin/tag-category/tag-category.controller.ts, services/apps/alcs/src/alcs/admin/tag-category/tag-category.dto.ts, services/apps/alcs/src/alcs/admin/tag-category/tag-category.entity.ts, services/apps/alcs/src/alcs/admin/tag-category/tag-category.service.spec.ts, services/apps/alcs/src/alcs/admin/tag-category/tag-category.service.ts, services/apps/alcs/src/alcs/admin/tag/tag.controller.spec.ts, services/apps/alcs/src/alcs/admin/tag/tag.controller.ts, services/apps/alcs/src/alcs/admin/tag/tag.dto.ts, services/apps/alcs/src/alcs/admin/tag/tag.entity.ts, services/apps/alcs/src/alcs/admin/tag/tag.service.spec.ts, services/apps/alcs/src/alcs/admin/tag/tag.service.ts, services/apps/alcs/src/providers/typeorm/migrations/1729713891477-create_tag_category.ts, services/apps/alcs/src/providers/typeorm/migrations/1729723237404-create_tag.ts, services/apps/alcs/test/mocks/mockEntities.ts
- Created Category and Tag entities
- Basic API CRUD functions
=> ALCS-2325 Tag/Category entities and cruds

portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.html, portal-frontend/src/app/features/notice-of-intents/edit-submission/additional-information/additional-information.component.ts
Every time the desktop version changes the structure type, it persists on the FormProposedStructure array, and this array is used to render the mobile component.
It doesn't exist when the area is changed, that's why it was not carried to the mobile view.
Added two methods to replicate the behavior to the Area fields, and carry the changes to the mobile view.
=> ALCS-2327 Allow the changes on desktop version to reflect on mobile

services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.controller.spec.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.controller.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.dto.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.service.spec.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.service.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.entity.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.module.ts, services/apps/alcs/src/alcs/tag/tag.entity.ts, services/apps/alcs/src/alcs/tag/tag.module.ts, services/apps/alcs/src/providers/typeorm/migrations/1730326975258-add_tags_to_noi.ts
Backend implementation for NOI Tags
=> ALCS-2345 Backend implementation

services/apps/alcs/src/alcs/application/application-tag/application-tag.controller.spec.ts, services/apps/alcs/src/alcs/application/application-tag/application-tag.controller.ts, services/apps/alcs/src/alcs/application/application-tag/application-tag.dto.ts, services/apps/alcs/src/alcs/application/application-tag/application-tag.service.spec.ts, services/apps/alcs/src/alcs/application/application-tag/application-tag.service.ts, services/apps/alcs/src/alcs/application/application.entity.ts, services/apps/alcs/src/alcs/application/application.module.ts, services/apps/alcs/src/alcs/tag/tag.entity.ts, services/apps/alcs/src/alcs/tag/tag.module.ts, services/apps/alcs/src/providers/typeorm/migrations/1730319303783-add_application_tags.ts, services/apps/alcs/test/mocks/mockEntities.ts
Backend Changes:
- Application_Tag Table (Many to Many relationship between application and tag entities)
- ApplicationTagService
- ApplicationTagController
- ApplicationTagDTO
=> Add Application Tag Resource to Backend

services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.controller.spec.ts, services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent-tag/notice-of-intent-tag.service.spec.ts, services/apps/alcs/test/mocks/mockEntities.ts
=> ALCS-2345 Added unit tests

alcs-frontend/src/app/features/search/notification-search-table/notification-search-table.component.ts, alcs-frontend/src/app/features/search/search.component.ts
The search params were not being refresh correctly on subsequent searches.
Used array mapping to update.
Also found an unrelated bug that was firing some console errors, and fixed it.
=> ALCS-1874 Refresh tags params correctly

services/apps/alcs/src/alcs/notice-of-intent/notice-of-intent.service.ts
The map function would execute addTag function in an asynchronously that caused tags to be saved incorrectly.
=> QA Fix: Fix NOI Tags Not Being Saved Correctly Upon Submission

services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
The drop down on add condition should be ordered by label. Previously it was ordered by edited date.
=> ALCS-2399 Order by label on retrieving codes

portal-frontend/src/app/features/home/inbox/inbox-list/inbox-list.component.ts
Setting the total as the length was preventing the mobile view to paginate.
The total is set properly on component's input.
=> ALCS-2361 Leave total set on component

alcs-frontend/src/app/features/search/search.component.html
I couldn't find a particular reason for the dropdown to open.
With some research I read that angular material have some issues with overlays, and these two being the same component could make use of the same overlay. (and it triggers the first dropdown no matter where it's on the screen ... I tested it ... :( )
But the event.preventDefault stops the overlay actions, and triggers only the desired functionality.
=> ALCS-2416 Added  preventDefault on dropdowns

alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.html, alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts, alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types.component.ts, alcs-frontend/src/app/features/admin/decision-condition-types/decision-dialog-data.interface.ts, alcs-frontend/src/app/shared/validators/code-exists-validator.ts
We have a constraint that all the CODE based entities should have an unique description.
What was done:
Check the existence of a description and display a clear message to the user about the uniqueness of the description.
=> ALCS-2453 Handle unique descriptions on condition types

alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts, alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types.component.ts
Allow the checkboxes to be disabled if the stored value is zero.
There's also a minor fix on the edit dialog, to prevent the validation from unique description on the actual value.
=> ALCS-2451 Allow to remove check box if the value is zero

alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.html, alcs-frontend/src/app/features/search/file-type-filter-drop-down/file-type-filter-drop-down.component.ts, alcs-frontend/src/app/features/search/search.component.html
fix the advanced search bug that clicking on "File Type" text on dropdown would open the "Current Portal Status" dropdown
=> Fix Portal Status and File Type Dropdown Bugs

alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html, alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.html, alcs-frontend/src/app/features/board/dialogs/application/application-dialog.component.ts, alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.html, alcs-frontend/src/app/features/board/dialogs/notice-of-intent/notice-of-intent-dialog.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.html
Navigate to conditions when decision released for Applications and NOIs
=> ALCS-2426 Navigate to conditions when decision released

alcs-frontend/src/app/features/admin/decision-condition-types/decision-condition-types-dialog/decision-condition-types-dialog.component.ts, alcs-frontend/src/app/services/application/decision/application-decision-v2/application-decision-v2.dto.ts, alcs-frontend/src/app/services/notice-of-intent/decision-v2/notice-of-intent-decision.dto.ts, services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition.service.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition.service.ts
The validation was checking only for conditions, but there were some orphan rows that were invalidating the fees removal.
I added the decision relation on conditions methods, updated the DTOs, and filtered only the decision related conditions.
Maybe we should capture a technical debt to handle the conditions while deleting a decision.
=> ALCS-2467 Check decisions

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition/decision-condition.component.ts
While saving the whole condition, with already having updated the date in a single date condition, the date row was being updated only with the date portion but deleting the completedDate and the comment, since it was being send to the backend ONLY the date attribute, deleting the attributes added earlier, and changing the status in a wrong way.
The change checks if there's more data on that date and emits everything.
=> ALCS-2474 Fix single date updates

alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts
When a condition has a nullable single date, adding a date is only possible while adding the condition, or editing the draft.
This small fix enables the date to be added also at the conditions view component, also changing the statuses in real time.
=> ALCS-2478 Allow to add a new date on conditions component

alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html, alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts
Fix the bug that showed wrong "Due Date" on application decision condition card when a condition with multiple date type has no date value
=> QA Fixes #2: 1871

services/apps/alcs/src/providers/typeorm/migrations/1737579030699-adding_date_to_conditions.ts
This script looks for all the conditions that are from Single Date type, that have no dates associated, and add a date row, allowing the user to manage the date, they can update and also add the completion.
I decided not the make any UI/Backend changes to not introduce any workarounds, and keep the data integrity they way we projected to be.
=> ALCS-2478 Add date to the single date conditions

alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.scss
Edit draft and revert to draft buttons are separate, so grid settings were only being applied to one. This just adds the same grid column setting to the revert button, and aligns it right, so the button is flush.
=> Align revert button to right like edit button

alcs-frontend/src/app/features/board/board.component.ts, alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.html, alcs-frontend/src/app/features/board/dialogs/application-decision-condition-dialog/application-decision-condition-dialog.component.ts, alcs-frontend/src/app/shared/application-type-pill/application-type-pill.constants.ts, alcs-frontend/src/app/shared/card/card.component.html, alcs-frontend/src/app/shared/card/card.component.scss, alcs-frontend/src/app/shared/card/card.component.ts, services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.spec.ts, services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-card/application-decision-condition-card.service.ts, services/apps/alcs/src/alcs/application-decision/application-modification/application-modification.service.ts, services/apps/alcs/src/alcs/application-decision/application-reconsideration/application-reconsideration.service.ts, services/apps/alcs/src/providers/typeorm/migrations/1737750628423-add_application_condition_card_type_to_new_boards.ts
- Add application condition card type support to boards (CEO, Executive Committee, and all panels)
- Add condition, modification, and reconsideration pills when moving the condition card to other non-condition boards (and vice versa)
- Remove expired and past due pills when moving the condition card to other non-condition boards (and vice versa)
=> Move Application Conditions to Other Boards

portal-frontend/src/app/features/public/application/alc-review/submission-documents/submission-documents.component.ts
3 things were needed:
- The table source data needed to be updated via the `data` property rather than replaced
- Sorting needed to be initialized after view init (at this point, all columns were sortable except for type)
- A custom sorting accessor was needed to make the type column work (since its value was a sub property)
=> 2448: Fix public doc sorting

alcs-frontend/src/app/features/application/decision/decision-v2/decision-v2.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-v2.component.ts, alcs-frontend/src/app/shared/flag-dialog/flag-dialog.component.html, alcs-frontend/src/app/shared/shared.module.ts, alcs-frontend/src/app/shared/unflag-dialog/unflag-dialog.component.html, alcs-frontend/src/app/shared/unflag-dialog/unflag-dialog.component.scss, alcs-frontend/src/app/shared/unflag-dialog/unflag-dialog.component.spec.ts, alcs-frontend/src/app/shared/unflag-dialog/unflag-dialog.component.ts
New component for unflag dialog.
Warning added to flag dialog component.
=> ALCS-2570 New component for unflag dialog

alcs-frontend/src/app/shared/flag-dialog/flag-dialog.component.html
The warning should be visible all time.
=> ALCS-2507 Show warning also on edit

services/apps/alcs/src/alcs/application-decision/application-decision-v2/application-decision/application-decision-v2.service.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-v2/notice-of-intent-decision-v2.service.ts
Since we are hard deleting the conditions making it an empty array, there's no need to handle the dates individually anymore. TypeORM is making the deletion when saving the decision entity.
=> ALCS-2468 Remove the individual date method

services/apps/alcs/src/alcs/notification/notification.controller.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.controller.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.spec.ts, services/apps/alcs/src/portal/notification-submission/notification-submission.service.ts, services/apps/alcs/src/portal/pdf-generation/generate-srw-document.service.spec.ts, services/apps/alcs/src/portal/pdf-generation/generate-srw-document.service.ts
- This helps make sure notification, PDF, and email all have the same
submitted date
- It also allows them to execute in any order
=> 2546: Pass submitted date to upstream submission methods

alcs-frontend/src/styles/ngselect.scss
Match the ng-select disabled appearance with the other inputs.
=> ALCS-1987 Custom ng-select adjustments

alcs-frontend/src/app/features/application/proposal/naru/naru.component.html, alcs-frontend/src/app/features/application/proposal/nfu/nfu.component.html, alcs-frontend/src/app/features/application/proposal/soil/soil.component.html, alcs-frontend/src/app/features/notice-of-intent/proposal/soil/soil.component.html
- "Use End Date" from NARU, NFU, POFO, and ROSO applications
- "Use End Date" from POFO and ROSO NOIs
- "Use End Date (Placement of Fill/Removal of Soil)" from PFRS applications and NOIs
=> ALCS-2390: Remove "Use End Date" Field from Application and NOI Prep

alcs-frontend/src/app/features/application/overview/overview.component.html, alcs-frontend/src/app/features/notice-of-intent/overview/overview.component.html, alcs-frontend/src/app/shared/inline-editors/inline-textarea-edit/inline-textarea-edit.component.html
This pull request includes changes to the `alcs-frontend` project to enhance the functionality of inline editing components by allowing paragraph breaks in text areas. The most important changes include updates to the `overview.component.html` files and modifications to the `inline-textarea-edit.component.html` file to support this new feature.
Enhancements to inline editing components:
* [`alcs-frontend/src/app/features/application/overview/overview.component.html`](diffhunk://#diff-db7ecd942f621d74383de52c431e7cb1b83339871ec49fc4a7347227f8b2ea52R16): Added the `allowParagraphs` attribute to the `<app-inline-edit>` component to enable paragraph breaks in the proposal summary.
* [`alcs-frontend/src/app/features/notice-of-intent/overview/overview.component.html`](diffhunk://#diff-1ce5fff1e2 …
=> QA-2412: Disable Save on Enter Key When Paragraph is Allowed and Allow Paragraph on Proposal Summary 

alcs-frontend/src/app/features/application/decision/conditions/condition/condition.component.ts, alcs-frontend/src/app/features/application/decision/conditions/conditions.component.html, alcs-frontend/src/app/features/application/decision/conditions/conditions.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/conditions/condition/condition.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/conditions/conditions.component.ts
- There was a typo making complete filter fail
- When the status was updated in the single condition component, the change was not being propogated to the list condition component's data, so when the list redrew the single components, it used its old data
- Added an event emitted to update the list status when updating the single status
=> ALCS-2260: QA #2: Fix complete filter and update status properly

alcs-frontend/src/app/features/application/documents/documents.component.ts, alcs-frontend/src/app/features/inquiry/documents/documents.component.ts, alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.ts, alcs-frontend/src/app/features/notification/documents/documents.component.ts, alcs-frontend/src/app/features/planning-review/documents/documents.component.ts, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.html, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.ts, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.dto.ts, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.interface.ts
- Create interfaces for setting data to allow for
better validation
- Create a global options consts that can be used
for both add and edit to make sure they are
consistent
- Pass in parcel/owner services to avoid long
modal opening times
=> ALCS-2579: Make shared upload dialog more robust and performant

alcs-frontend/src/app/features/application/documents/documents.component.ts, alcs-frontend/src/app/features/notice-of-intent/documents/documents.component.ts, alcs-frontend/src/app/features/notification/documents/documents.component.ts, alcs-frontend/src/app/features/planning-review/documents/documents.component.ts
- Silly mistake
- I forgot `Object.assign()` overwrites the target object
- Replaced with spread operators
=> ALCS-2579: QA #1: Don't overwrite options object

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition-order-dialog/decision-condition-order-dialog.component.ts
The move up algorithm was switching the select record with the top one.
I changed the behavior bringing the selected row to the top, and bringing the subsequent ones down.
=> ALCS-2029 Change move up algorithm

services/apps/alcs/src/alcs/application-decision/application-decision-condition/application-decision-condition-financial-instrument/application-decision-condition-financial-instrument.entity.ts, services/apps/alcs/src/alcs/notice-of-intent-decision/notice-of-intent-decision-condition/notice-of-intent-decision-condition-financial-instrument/notice-of-intent-decision-condition-financial-instrument.entity.ts, services/apps/alcs/src/providers/typeorm/migrations/1741287102799-rename_financial_instrument_enums.ts, services/apps/alcs/src/providers/typeorm/migrations/1741289414578-add_default_to_app_instrument_status.ts
- Fix financial instruments' enum data types' names being truncated due to PostgreSQL's 63-byte limit for names. Applies to both applications and NOIs.
- Add default value to application financial instrument's status column
=> Rename Financial Instrument Data Type Enums and Add Default to Status Column

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition-order-dialog/decision-condition-order-dialog.component.ts
- Ordering was relying on UUID which doesn't exist if conditions haven't been saved
- Changed to use only order property, index not needed
- Also simplified updating order and sorting
=> ALCS-2603: Fix move to top/bottom

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-conditions/decision-condition-order-dialog/decision-condition-order-dialog.component.ts
- I had taken out a condition that I thought wasn't necessary, because it relied on the index which was causing the initial problem
- The condition prevented conditions that didn't move from having their orders updated
- I've put it back and it is now based on the record order, which should accomplish the same result
=> ALCS-2603 QA #1: Replace condition that kept sane order numbers

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.ts
Once the field was changed, it was only enabled again in case of an error.
The desired behavior was to enable once the processing is over.
=> ALCS-2561 Fix re-enabling the fields

alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.html, alcs-frontend/src/app/features/application/decision/decision-v2/decision-input/decision-input-v2.component.ts, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.html, alcs-frontend/src/app/features/notice-of-intent/decision/decision-v2/decision-input/decision-input-v2.component.ts, alcs-frontend/src/app/shared/inline-editors/inline-number/inline-number.component.ts
- When the resolution number editor is open and a release is attempted, it shows an error
- Now, when we save or cancel the resolution editor, and then re-edit it, the error is gone
=> ALCS-2455: Don't show resolution number save error when re-editing

.github/workflows/deploy.yml
Update the gitops repo directly in the main repo's workflow.
This allows deploy keys to be used instead of a PAT.
=> Update gitops repo directly

services/package-lock.json, services/package.json
We used to use MJML for emails. Due to a security issue, we switched to a custom solution in a previous ticket, but the package was never removed, so the issue is still showing up. This just cleans that up.
=> Remove MJML, since it's not used anymore

alcs-frontend/Dockerfile, portal-frontend/Dockerfile
libxml2 is not installed in base Docker image, but installing it should update the .so file in the `/usr/lib`.
=> Patch libxml2 in Dockerfiles for portal and ACLS frontends

alcs-frontend/src/app/features/compliance-and-enforcement/compliance-and-enforcement.module.ts, alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.html, alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.scss, alcs-frontend/src/app/features/compliance-and-enforcement/documents/documents.component.ts, alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.html, alcs-frontend/src/app/features/compliance-and-enforcement/draft/draft.component.ts, alcs-frontend/src/app/services/compliance-and-enforcement/documents/document.dto.ts, alcs-frontend/src/app/services/compliance-and-enforcement/documents/document.service.ts, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.html, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.component.ts, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.dto.ts, alcs-frontend/src/app/shared/document-upload-dialog/document-upload-dialog.interface.ts, alcs-frontend/src/app/shared/document/document.dto.ts, services/apps/alcs/src/alcs/compliance-and-enforcement/compliance-and-enforcement.module.ts, services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.automapper.profile.ts, services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.controller.ts, services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.dto.ts, services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.entity.ts, services/apps/alcs/src/alcs/compliance-and-enforcement/document/document.service.ts, services/apps/alcs/src/document/document-code.entity.ts, services/apps/alcs/src/document/document.automapper.profile.ts, services/apps/alcs/src/document/document.dto.ts, services/apps/alcs/src/document/document.module.ts, services/apps/alcs/src/providers/typeorm/migrations/1752168876435-add_complaint_doc_type.ts, services/apps/alcs/src/providers/typeorm/migrations/1752183361775-add_c_and_e_docs_table.ts, services/apps/alcs/src/providers/typeorm/migrations/1753386233493-add_section_column_to_c_and_e_docs.ts
- Backend
- Create C&E docs table/entity (to be reused for other C&E docs)
- Add DTO's, controller, service
- Frontend
- Add DTO's, service for new C&E docs
- Create new general-purpose C&E documents table (to be used for other documents sections)
- Update document upload component to accommodate new table component
- Add documents table to C&E draft
=> Add submission doc to C&E draft

services/apps/alcs/src/portal/application-submission-review/application-submission-review.controller.ts, services/apps/alcs/src/portal/application-submission/application-submission.service.ts
- Was only checking for gov business BCeID's and then defaulting to single user account
- I added a case to handle non-gov business BCeID's
- It checks if there is a gov:
- If there is, handle as it does now
- If not, use the user's business BCeID in query for submission
- Fixing the submission revealed that the same problem applied to L/FNG reviews
- Was able to reuse same function to fix review
=> Add case for to handle access to non-government BCeID's apps
